### ISSUE TITLE
skeleton of web component

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1]

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1843](https://github.com/yegor256/rultor/issues/1843), [#1844](https://github.com/yegor256/rultor/issues/1844) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#1843](https://github.com/yegor256/rultor/issues/1843), [#1844](https://github.com/yegor256/rultor/issues/1844).
