### ISSUE TITLE
Site Target Does not Execute Jekyll in Bundle Context Causes Jekyll-Sass to not Properly Load

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/rultor#1001]
It's in the title, the current site target executes Jekyll outright.
Not running Jekyll in the bundle context leads to Jekyll-Sass not loading and the site target failing.
Like for example in my PR here: #1000 where it throws:
```
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:exec (jekyll-build) @ rultor ---
Configuration file: /home/r/repo/src/jekyll/_config.yml
\u001b[31m  Dependency Error: Yikes! It looks like you don't have jekyll-sass or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-sass' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! \u001b[0m
jekyll 3.1.1 | Error:  jekyll-sass
```

This can be fixed by running Jekyll in the bundle context.

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear valid problem. I guess it's already fixed in #1002, right?

**Comment by original-brownbear** [comment]
@yegor256 yes #1002 should fix this

**Comment by original-brownbear** [comment]
@alex-palevsky I think this can just be closed right? It's evidently working again with #1002 :)

**Comment by alex-palevsky** [comment]
@original-brownbear attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now

**Comment by yegor256** [comment]
@original-brownbear let's close it?

**Comment by original-brownbear** [comment]
Jup, all done here :)

**Comment by alex-palevsky** [comment]
@yegor256 thank you, added **45 mins** to your acc, payment num is `000-8b89fcac`, 47 hours and 50 mins spent in total to complete. m=2870, that's why a bonus here for fast delivery. +45 added to your rating, at the moment it is: [+1600](http://www.netbout.com/b/35008?open=rating)
