### ISSUE TITLE
Rultor can't pull the image, 'pid' file is absent

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#1009]
Rulto failed with the error message
>Trying to pull repository docker.io/yegor256/rultor ... Repository docker.io/yegor256/rultor already being pulled by another client. Waiting.
'pid' file is absent, something was broken

see logs http://www.rultor.com/t/7069-184660714

I expect more clear error message if it is a temporary issue
otherwise please fix the problem

**Comment by original-brownbear** [comment]
@dmzaytsev I already mentioned this here https://github.com/yegor256/rultor/pull/1008 , this should in 99% of cases be resolvable by restarting the Docker daemon instantly.

Generally fixing this:
The log does not give away the Docker daemon version, but it looks to me that this is most likely this issue https://github.com/docker/docker/issues/15603 and updating to Docker 1.9.0+ should resolve it, if Rultor is in fact running an older Docker version which seems likely.

**Comment by original-brownbear** [comment]
@yegor256 forgot to ping you here, is Rultor in fact running on older than Docker 1.9 and this not an issue outside of having to update Docker maybe ?

**Comment by yegor256** [comment]
@original-brownbear this is what we have:

```
$ docker --version
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2
```

will try to upgrade now

**Comment by yegor256** [comment]
@original-brownbear I upgraded Docker:

```
$ docker --version
Docker version 1.10.1, build 9e83765
```

**Comment by original-brownbear** [comment]
@yegor256 alright :) I think this can simply be closed then, it was just a know bug in the old Docker version.

**Comment by dmzaytsev** [comment]
@original-brownbear @yegor256 thanks
