### ISSUE TITLE
Rultor Should Tag Docker Images on every Release

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/rultor#1033]
This is coming from here:
https://github.com/jcabi/jcabi-aether/issues/82#issuecomment-190294161

Rultor should push tagged versions of its Dockerfile when pushing it's release tags to Github, so that stability for projects using Rultor's own Docker image is ensured.

I'm afraid this is a job for you @yegor256, as this requires a setting in Dockerhub, not coding in Rultor.
You need to add a build type exactly like this (only set type to tag and the file path, other two fields stay empty):
![image](https://cloud.githubusercontent.com/assets/6490959/13403069/7f1cf238-df13-11e5-92f4-1f02801697b0.png)

Then we get builds like so:
![image](https://cloud.githubusercontent.com/assets/6490959/13403104/a00522ae-df13-11e5-801d-7aa08a3453d8.png)

And an people can simply put say:

```yaml
docker:
  image: "yegor256/rultor:1.61.4"
```

to keep using that specific version of the image forever, without having to fear it changing.

So this ticket only needs the setting in Dockerhub to be resolved.

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by original-brownbear** [comment]
@alex-palevsky assign @yegor256 please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear tagged this issue with "bug"

**Comment by alex-palevsky** [comment]
@original-brownbear milestone set to `2.0` (correct me if I am wrong)

**Comment by alex-palevsky** [comment]
@original-brownbear thank you for reporting this, I added 30 mins to your acc, transaction `AP-7V504626V1926542G`

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign @yegor256 please.

@original-brownbear too many tasks (10) are active in the project already, can't assign new ones

**Comment by yegor256** [comment]
@original-brownbear done:

<img width="1271" alt="screen shot 2016-03-01 at 8 59 49 pm" src="https://cloud.githubusercontent.com/assets/526301/13451086/9543263a-dff0-11e5-8174-a0bf14533187.png">

**Comment by yegor256** [comment]
@original-brownbear let's test?

**Comment by original-brownbear** [comment]
@yegor256 Sure :)

**Comment by original-brownbear** [comment]
@rultor release tag is `1.61.7`

**Comment by original-brownbear** [comment]
@yegor256 works :) https://hub.docker.com/r/yegor256/rultor/builds/ now builds by tag :)

**Comment by yegor256** [comment]
@original-brownbear perfect!
