### ISSUE TITLE
Improve TravisCI configuration

### ISSUE THREAD

**Issue by mkordas** [yegor256/rultor#1035]
Current [`.travis.yml`](https://github.com/yegor256/rultor/blob/master/.travis.yml) is very basic and not efficient one.
I see the following issues:
- it should have `sudo: false` in order to make cache working
- installation phase (`install:`) should be explicitly empty, as we don't have any modules to be prepared
- estimates and puzzles should be checked by Travis
- there is no need to invoke `clean` as Travis always starts with fresh container
- there is no need to `install` things to local repository, `verify` should be enough

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear added "bug" tag to this issue

**Comment by alex-palevsky** [comment]
@mkordas attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `56d6e8d43c541050b300042e`

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear OK, I will try to assign someone else

**Comment by yegor256** [comment]
@mkordas we use GitHub Actions now

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1035` is not assigned, can't get performer
