### ISSUE TITLE
Test case TailITCase failure

### ISSUE THREAD

**Issue by vkuchyn** [yegor256/rultor#1044]
After cloning project, running build script get next error 
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.135 sec <<< FAILURE! - in com.rultor.agents.daemons.TailITCase
tailsNonUtf(com.rultor.agents.daemons.TailITCase)  Time elapsed: 2.134 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "some outputê\n"
     but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.rultor.agents.daemons.TailITCase.tailsNonUtf(TailITCase.java:95)

```
Do you have any suggestions?
Run on environment:
Java version: 1.8.0_60, vendor: Oracle Corporation
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T22:59:23+05:30)

**Comment by original-brownbear** [comment]
@vkuchyn this is coming from the fact that this test is using http://ssh.jcabi.com/apidocs-1.5.2/index.html , which unfortunately only works on Linux as documented under that link.
I think your best bet for building this on a Mac is to simply install docker toolbox and run the build in via Docker or use Virtualbox + a Linux guest install.

**Comment by vkuchyn** [comment]
@original-brownbear thanks
