### ISSUE TITLE
StartsDaemonITCase.java:126-128: This test should not check...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1052]
Puzzle `1018-b83a728c` in `src/test/java/com/rultor/agents/daemons/StartsDaemonITCase.java:126-128` has to be resolved: This test should not check for start and end deprecation messages if when the repo is the actual Rultor repo: https://github.com/yegor256/rultor... The puzzle was created by Sebin George on 11-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear there is no milestone yet, so I set it to `2.0`

**Comment by original-brownbear** [comment]
@alex-palevsky this depends on #1055

**Comment by alex-palevsky** [comment]
> @alex-palevsky this depends on #1055

@original-brownbear ok, let's wait for #1055

**Comment by alex-palevsky** [comment]
@xupyprmv help us, the task is yours

**Comment by xupyprmv** [comment]
@alex-palevsky Nothing to do here right now, because of causal relationship defect. This ticket require first puzzle from https://github.com/yegor256/rultor/issues/1018#issuecomment-195495201 solved. Please add first puzzle to let me request waiting for it.

**Comment by xupyprmv** [comment]
@alex-palevsky Sorry, it is my mistake. Issue for first puzzle is already created.

I'm waiting for #1053 here.

**Comment by original-brownbear** [comment]
@alex-palevsky this is not urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is not urgent.

@original-brownbear right, I removed "urgent" tag

**Comment by xupyprmv** [comment]
> @original-brownbear ok, let's wait for #1055
@alex-palevsky Also this depends on #1053

**Comment by original-brownbear** [comment]
@alex-palevsky this is not urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is not urgent.

@original-brownbear got it, "urgent" tag removed from here

**Comment by original-brownbear** [comment]
@xupyprmv you didn't do any work here right ? Are you ok with postponing this and unassign so you're not blocked by it ?

**Comment by xupyprmv** [comment]
@original-brownbear I think I can close it without waiting of #1055. Because #1053 is already resolved. I will add PR soon.

**Comment by original-brownbear** [comment]
@xupyprmv right ! thanks!

**Comment by alex-palevsky** [comment]
@original-brownbear we waited for #1055, it is closed already

**Comment by xupyprmv** [comment]
@alex-palevsky PR #1076 was merged. Please close this issue.

**Comment by original-brownbear** [comment]
@alex-palevsky please pay attention here, this has been closed for 3 days now.

**Comment by alex-palevsky** [comment]
@original-brownbear Closing, thanks all

**Comment by alex-palevsky** [comment]
@xupyprmv Thank you, I have added **45 mins** to your account in payment/transaction "`AP-8C1346646U847963N`", time consumed: 47 hours and 53 mins. m=2873, that's why a bonus here for fast delivery. +45 to your rating, your total score is [+375](http://www.netbout.com/b/35999?open=rating)
