### ISSUE TITLE
StartsDaemonITCase.java:121-125: Implement a deprecation message at...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1053]
Puzzle `1018-15a5404e` in `src/test/java/com/rultor/agents/daemons/StartsDaemonITCase.java:121-125` has to be resolved: Implement a deprecation message at the start and end of the process if the project is using the default image 'yegor256/rultor'. Fix the issue using the xpath available in com.rultor.agents.daemons.StartsDaemon and com.rultor.agents.daemons.EndsDaemon.... The puzzle was created by Sebin George on 10-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by original-brownbear** [comment]
@alex-palevsky this depends on #1055

**Comment by alex-palevsky** [comment]
@original-brownbear since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
> @alex-palevsky this depends on #1055

@original-brownbear yes, of course, we'll wait for #1055

**Comment by alex-palevsky** [comment]
@essobedo you may proceed,it's yours

**Comment by essobedo** [comment]
@alex-palevsky waiting for #1058

**Comment by alex-palevsky** [comment]
> @alex-palevsky waiting for #1058 

@essobedo yes, of course, we'll wait for #1058

**Comment by alex-palevsky** [comment]
@original-brownbear FYI, issue #1058 is already closed, and we were waiting for it..

**Comment by essobedo** [comment]
@alex-palevsky Another question why do we need the notice in both StartsDaemon and EndsDaemon?

**Comment by essobedo** [comment]
@alex-palevsky @original-brownbear I had to reopen #1058 to have the answer of a new question

**Comment by essobedo** [comment]
@alex-palevsky here is my PR #1062, please find a reviewer

**Comment by alex-palevsky** [comment]
> @alex-palevsky here is my PR #1062, please find a reviewer

@essobedo OK

**Comment by essobedo** [comment]
@alex-palevsky The PR has been merged, could you please proceed, thank you in advance

**Comment by alex-palevsky** [comment]
@original-brownbear the code made here contains a puzzle `1053-dc86a5cc`/#1069, which will be resolved soon

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks all, closed

**Comment by alex-palevsky** [comment]
@essobedo thanks, paid, **30 mins** to your account, payment ID is `81394688`, task took 191 hours and 13 mins to complete; +30 added to your rating, at the moment it is: [+375](http://www.netbout.com/b/36421?open=rating)

**Comment by alex-palevsky** [comment]
@original-brownbear the last puzzle `1053-dc86a5cc`/#1069 originated from here solved

**Comment by 0pdd** [comment]
@alex-palevsky the puzzle [#1374](https://github.com/yegor256/rultor/issues/1374) is still not solved.

**Comment by 0pdd** [comment]
@alex-palevsky the only puzzle [#1161](https://github.com/yegor256/rultor/issues/1161) is solved here.
