### ISSUE TITLE
SSHD Tests Are Very Unsafe and not Portable => Implement SSH Tests using Docker Container Instead

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/rultor#1055]
We currently have a few integration test cases around SSH, all of which are problematic for obvious reasons.
They are using `com.jcabi.ssh.SSHD` documented [here](http://ssh.jcabi.com/apidocs-1.5.2/com/jcabi/ssh/SSHD.html).
This causes two issues:
* First off this thing only works on Linux, causing Mac developers to not be able to work on Rultor efficiently at the very least.
* Second of all and that's the important part :)
This class simply gives us a shell into our local machine on Linux. This makes it close to impossible to test issues revolving around the EC2 environment we SSH into. Like e.g. interaction with the git and docker command-line.
 * As a result the tests we're running here current are in no way able to prevent erroneous things from being merged when it comes to Rultor's bash scripting.

This needs to be fixed, currently we're simply relying on the best judgement of Architect and CR when it comes to fixes to the bash scripts associated with Docker and Git.

**We should simply use Docker to provide a clean container to shell into for testing instead.**
How to do this in a quick and reasonable way is laid out below and needs to be implemented here.

# Scope of this Task 

* Create a simple Dockerfile from the official `ubuntu:14.04` that contains an ssh daemon. Begin like so:

```docker
FROM ubuntu:14.04
RUN apt-get install -y ssh && \
  mkdir /var/run/sshd && \
  chmod 0755 /var/run/sshd
```
Then add a public ssh key to the root user via `COPY` (generate in on your machine) in it and configure it to have the `sshd` as `CMD` instruction so that the `ssh` service is running in it. The private keyfile for this key should become part of the repository.
Please also make this thing start in a way that does allow for deamonizing it.
I suggest this section at the end of the Dockerfile:

```docker
COPY run.sh /run.sh
CMD["/bin/bash", "-lc", "/run.sh"]
```

with `run.sh` looking like this:

```bash
#!/usr/bin/env bash

/usr/sbin/sshd -D
tail -f /dev/null
```
* Create a new Maven Profile `docker-tests` (ignore the existing with-live-docker please :) ) that:
* Builds a docker image from the above created Dockerfile on every run of the test (not an issue due to the build cache).
* Starts up a container from this image before the integration tests and tears it down afterwards by using the failsafe plugin. 
* This should work on every machine that has the docker CLI working for the currently logged in user.
 * Please do this in bash for portability, **do not use any Maven Docker plugins or the like!**

In order to get the IP and port of the ssh container started, don't overcomplicate things.
Simply start the ssh container to short the ssh port with the docker-host. Then all you need to get is the port. This is easy to script:
```
➜  /tmp docker run --name some-name-you-chose -d -p 22 rultor-ssh-image
5c20576a6520a7139ea8608e360a877a3c814fae6ff66d75d05544618072693d
➜  /tmp docker inspect --format='{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}' some-name-you-chose   
32769
```
Just run the container with a name and `-p 22` and it'll be just fine. Docker will automatically bind `22` to a free port on the Docker host. Above shown `docker inspect` use gets you the port.

* Expected Folder structure under the project root:
 * src
    * docker-it
       * Dockerfile
       * run.sh
       * id_rsa
       * id_rsa.pub

**Once this has been accomplished:** 

* Adjust com.rultor.agents.daemons.StartsDaemonITCase#talk to use ssh into the dockerized SSH daemon when the profile `docker-tests` is active.
* Add a quick explaination of this test feature to the readme containing what it does and how to run the tests with this profile active.

--------------------------------
Together with Travis now supporting Docker, see [here](https://docs.travis-ci.com/user/docker),  this will allow us to fix further tickets around the SSH functionality in a much safer way, with the now available clearly defined SSH environment.

If you have any questions ask. This should be a very quick task, given that I clearly laid out how to do this above. Still keep in mind the option of Puzzles ;)

* If you are unfamiliar with building a Dockerfile into an image see [here](https://docs.docker.com/engine/reference/commandline/build/).
* For running a Docker image see [here](https://docs.docker.com/engine/reference/commandline/run/), what you want here is the `-d` flag ;)
* If you need a quick and standard conform way of running Docker locally, see [here](https://docs.docker.com/machine/overview/)

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by original-brownbear** [comment]
@alex-palevsky this is urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear tag "bug" added

**Comment by alex-palevsky** [comment]
@original-brownbear there is no milestone yet, so I set it to `2.0`

**Comment by alex-palevsky** [comment]
@original-brownbear many thanks for the report, I topped your account for 30 mins, transaction AP-9D824169WF815933J

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is urgent.

@original-brownbear right, I added "urgent" label

**Comment by original-brownbear** [comment]
@vkuchyn would this interest you? You already did something similar for the `years.sh`,
so basic bash and Maven exec shouldn't be an issue for you imo :)

**Comment by vkuchyn** [comment]
@original-brownbear sounds interesting, I'll take it

**Comment by original-brownbear** [comment]
@alex-palevsky assign @vkuchyn please :)

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign @vkuchyn please :)

@original-brownbear OK @vkuchyn please go ahead, this task is yours

**Comment by original-brownbear** [comment]
@vkuchyn if possible please give this some priority :) As you can see a few tickets depend on this so I'm happy to answer questions on short notice too ;)

**Comment by vkuchyn** [comment]
@original-brownbear I am currently on it

**Comment by original-brownbear** [comment]
@vkuchyn thanks, let me know if you need anything! :)

**Comment by original-brownbear** [comment]
@vkuchyn got an update for me ? :)

**Comment by vkuchyn** [comment]
@original-brownbear Unfortunately not. I stuck with docker. I can build image and run container with sshd but have 2 problems:
1. Identify IP of container (my docker machine has IP 192.168.99.100, I am not sure everyone has the same - need to parametrize somehow)
2. Copied public key to ~/.ssh (BTW ssh requires 600 permissions for private key. This need to be configure locally, I cannot push permissions to github). But still ssh requires password. 

I am gonna to fix p. 2  after can make a puzzle for maven plugin. What will you suggest about p.1?

**Comment by original-brownbear** [comment]
@vkuchyn No problem, I'm specifically asking so that we can handle this quickly here, happy to help :)

**Lets start with 2 :)**

The public key goes to the server and needs to be in the /root/.ssh/authorized_keys.
I'd use this snipped in the Dockerfile for that(only need to adjust the local public key file name imo):

```
COPY id_rsa.pub /tmp/sshpub
RUN cat /tmp/sshpub >> /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys
```

**About the local private key:**
Yes you can push file permissions to GitHub :) Only possible issue that could come up here is if you configured your Git to automatically ignore file permissions.
In that case edit this file (relative to your Rultor repo):  `.git/config` to contain the `filemode = true`
setting under `[core]`. E.g. on my machine it looks like this:
```ini
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
```
In all likelihood the `filemode = true` will already be set and you don't need to worry about anything here ;). As a matter of fact you did push the `years.sh` and it's got executable permissions in the Git repository ... :) => all good out of the box.

**About part 1**

Added to the ticket description how to do this :)

**Comment by original-brownbear** [comment]
@vkuchyn careful with the time :
1. For your own good :) => Don't get penalised, please inform @alex-palevsky if you need more time.
2. For my good: Any ETA for me ? :)

**Comment by vkuchyn** [comment]
@original-brownbear thanks for your warning. I've got sickness and last few days out of job. I need couple days more to recover.
@alex-palevsky I've got sickness and need few days to recover. This may be cause of delaying with delivery. So, I need three days more for this task.

**Comment by vkuchyn** [comment]
@alex-palevsky I need more time for this task

**Comment by alex-palevsky** [comment]
> @alex-palevsky I need more time for this task

@vkuchyn of course, take your time

**Comment by original-brownbear** [comment]
@vkuchyn any update for me :) ? **4 days ago you asked for 3 more days ;)** 
This is a little urgent you know ... hence my being pushy here.

Please rather [cut corners](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) than stall this one :) 
I can help you with whatever issues you might come across really, but if this stalls completely (1 week without any movement in content here :/ ) then this becomes impossible and I will eventually have to ask for reassignment. So let's get this on track asap please :)

**Comment by vkuchyn** [comment]
@original-brownbear I'm gonna finish this task today, I've already recovered

**Comment by vkuchyn** [comment]
@original-brownbear the question is - if it is necessary to create run.sh file or I can run sshd (CMD ["/usr/sbin/sshd", "-D"] ) directly in build file as ENTRYPOINT. 
What is the reason to move daemon script to separate file?

**Comment by original-brownbear** [comment]
@vkuchyn that's fine too, but you need to make sure that the `sshd` is then properly started in a non-daemon way. Not sure `ssh -D` will work. But if you start it up with non-daemon arguments no need for the `run.sh` file. It's just there to keep the container open by tailing `/dev/null` forever ;) I'm good with a different solution to not having the container stop too though.

**Comment by vkuchyn** [comment]
@original-brownbear ok, thanks.
About previous question, number one https://github.com/yegor256/rultor/issues/1055#issuecomment-198642903
Your answer:

> In order to get the IP and port of the ssh container started, don't overcomplicate things.
> Simply start the ssh container to short the ssh port with the docker-host. Then all you need to get is the port. This is easy to script:
> 
> ➜  /tmp docker run --name some-name-you-chose -d -p 22 rultor-ssh-image
> 5c20576a6520a7139ea8608e360a877a3c814fae6ff66d75d05544618072693d
> ➜  /tmp docker inspect --format='{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}' some-name-you-chose   
> 32769
> Just run the container with a name and -p 22 and it'll be just fine. Docker will automatically bind 22 to a free port on the Docker host. Above shown docker inspect use gets you the port.

It is only about port, I was talking about IP address. I have docker machine (suppose, this is virtual machine with linux and docker onboard) hosted on IP 192.168.99.100. After running sshd docker image to connect via ssh I need to run command 
`ssh -i id_rsa root@192.168.99.100 -p 32772`
The question is - how to parametrize IP?
Also question, before integration tests we need somehow grab docker port to provide this information inside test. Whose responsibility is it?

**Comment by original-brownbear** [comment]
@vkuchyn this ip you can find the IP in the `DOCKER_HOST` environment variable.
I think in terms of providing this information, I think the easiest would be to have the bash script starting the container echo it into a file in the `target` directory and then read that from the Java tests.

**Comment by vkuchyn** [comment]
@alex-palevsky fixed in #1071. Need to be reviewed

**Comment by alex-palevsky** [comment]
> @alex-palevsky fixed in #1071. Need to be reviewed

@vkuchyn thanks for that

**Comment by original-brownbear** [comment]
@alex-palevsky merged :) Thanks all!

**Comment by alex-palevsky** [comment]
> @alex-palevsky merged :) Thanks all!

@original-brownbear no problem :)

**Comment by vkuchyn** [comment]
@alex-palevsky merged in #1071. Please, proceed payment

**Comment by original-brownbear** [comment]
@vkuchyn please don't forget to close the PR :)

**Comment by vkuchyn** [comment]
@original-brownbear already

**Comment by alex-palevsky** [comment]
@original-brownbear once `1055-4f9e2bff`/#1082 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by alex-palevsky** [comment]
@vkuchyn thanks, I just added **30 mins** to your account, payment `82125295`, 360 hours and 10 mins spent

+30 to your rating, your total score is [+180](http://www.netbout.com/b/36353?open=rating)

**Comment by alex-palevsky** [comment]
@original-brownbear the last puzzle `1055-4f9e2bff`/#1082 originated from here solved
