### ISSUE TITLE
ClosePullRequestTest.java:59-63: This class should only close...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1056]
Puzzle `918-89660440` in `src/test/java/com/rultor/agents/github/ClosePullRequestTest.java:59-63` has to be resolved: This class should only close pull requests for successful merges, that have not resulted in GitHub itself closing the PR, do nothing for any other kind of request. Once this is implemented here, implement this class acting on all pull requests by adding it to the active Agents.... The puzzle was created by Viktor Kuchyn on 11-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear got it, "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear right, I'll try to find someone else for this task

**Comment by alex-palevsky** [comment]
@original-brownbear Closing..
