### ISSUE TITLE
DockerHealthCheck.java:47-50: Add DockerHealthCheck to the running...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1057]
Puzzle `1041-7f83dd26` in `src/main/java/com/rultor/agents/docker/DockerHealthCheck.java:47-50` has to be resolved: Add DockerHealthCheck to the running SuperAgents. In doing so make sure that Rultor crashes throwing a meaningful exception as soon as DockerHealthCheck#execute throws and exception. #1041 has the details on the motivation behind this agent.... The puzzle was created by Armin Braun on 11-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear got it, someone else will be assigned soon

**Comment by alex-palevsky** [comment]
@original-brownbear Closing this issue now...
