### ISSUE TITLE
Substitute Dynamic EC2 Provisioning with ECS provisioning

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/rultor#1066]
# Background 

The constant possibility of the EC2 instance Rultor runs on crashing, in a manner Rultor cannot recover from itself, needs to be resolved. Implementing this was initiated in #629 .
Currently this leaves us with #825, #826 and #827.
With the advent of `AWS ECS` we have a significantly more performant ( in terms of boot time ) and hence much more economic alternative to bare `EC2` available. With bare `EC2` provisioning each build would take 2-5 minutes longer that would need to be paid for compared to ECS. ECS instances boot a lot faster.
ECS being specifically designed for the use case implied in #629 also makes implementing this a lot easier.
Hence we should adjust this plan slightly towards ECS.

# Task requires

* Adjust naming of EC2 interface and class stubs to ECS ( check #629 and associated code changes/PR for additional details here )
* Adjust puzzles to clearly state ECS to be used
 * Make sure that the adjusted puzzles reference the ticket id of the puzzle they're replacing please!
* In case of `com.rultor.agents.ec2.StartsEC2` also adjust Javadoc to clearly indicate the following plan
 * Provision instance running Docker + SSHd on ECS 
 * Instance needs to be configured in privileged mode
 * Instance config needs to be stored in S3, add a link to http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html#ecs-config-s3`to the docs here please to clear up any confusion on how this is to be done.
* Once finished replace dependency on `aws-java-sdk-ec2` with dependency on `aws-java-sdk-ecs`
 * As of now this dependency is not actually used anywhere functionally it seems, the types it defines are used in the stub implementations though, so this goes hand in hand with properly adjusting them.

**You are only supposed to adjust the puzzles, Javadoc and one dependency in this task, no implementation is asked for here!**

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear tagged this issue with "bug"

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by alex-palevsky** [comment]
@original-brownbear many thanks for the report, I topped your account for 30 mins, transaction AP-4PG902139H4099616

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by original-brownbear** [comment]
@alex-palevsky this is very urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear too many tasks already active in the project (7), can't have more

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is very urgent.

@original-brownbear thanks, I added "urgent" label

**Comment by alex-palevsky** [comment]
@xupyprmv it is in your hands now, proceed when you can

**Comment by xupyprmv** [comment]
@original-brownbear Do I have to resolve this issue or you will request to assign this ticket to you?

**Comment by original-brownbear** [comment]
@xupyprmv Alex assigned it to you know, so it's yours if you want :)

I think given that the task is mostly around rewording part of the puzzles and changing the dependencies,
this should go very quickly :)
=> if you think you can handle this in a timely manner go ahead please :)

**Comment by original-brownbear** [comment]
@xupyprmv please give me feedback asap if you can on whether you think this is something you want to and/or can handle ? :)
Thanks (sorry for being pushy here, but this is pretty much the most important task in Rultor now ;))

**Comment by xupyprmv** [comment]
@original-brownbear I will add PR ASAP.

**Comment by original-brownbear** [comment]
@xupyprmv thanks! :)

**Comment by xupyprmv** [comment]
@original-brownbear PR  #1083 was merged. Please close this ticket.

**Comment by original-brownbear** [comment]
@xupyprmv thanks!

**Comment by xupyprmv** [comment]
@alex-palevsky PR #1083 was merged. This ticket was closed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky PR #1083 was merged. This ticket was closed.

@xupyprmv thanks for that

**Comment by alex-palevsky** [comment]
@xupyprmv **30 mins** was added to your account, many thanks for your contribution (payment AP-55L90277B1501691H)! The task took 168 hours.. added +30 to your rating, now it is equal to [+360](http://www.netbout.com/b/35999?open=rating)
