### ISSUE TITLE
Puzzles and estimates are not verified for Travis and unnecessary install phase

### ISSUE THREAD

**Issue by mkordas** [yegor256/rultor#1068]
Despite of wrong format of puzzle in https://github.com/yegor256/rultor/pull/1062/files#diff-ea7114db89077c9c78dabe89a363b468R64 the builds were fine. We should have an immediate feedback about such mistakes from CIs, e.g. from Travis.

Tools `est` and `pdd` should be added like e.g. in https://github.com/yegor256/takes/blob/master/.travis.yml

Moreover, we have `install` phase on Travis, which takes almost 2 minutes and doesn't bring any value: https://travis-ci.org/yegor256/rultor/builds/117715010#L199

**Comment by original-brownbear** [comment]
@mkordas you already reported this here #1035 didn't you ? :)

**Comment by mkordas** [comment]
@original-brownbear thanks, closing this one. However #1035 shouldn't be postponed, as it strikes back in PRs :)

**Comment by original-brownbear** [comment]
@mkordas in a sense I agree, it's kind of a basic thing to have the .travis.yml right. 
But then again you can see the progress we're currently making here, partly in thanks to this issue teamed/xdsd#45 ... => I'd rather put in the steps towards better EC2 and Docker use with the resources available than block a task with this timing out. 
For better or for worse ... we really aren't dealing with a number of PR that this would really help much :)
