### ISSUE TITLE
EndsDaemon.java:64-66: Reduce the data abstraction coupling...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1069]
Puzzle `1053-dc86a5cc` in `src/main/java/com/rultor/agents/daemons/EndsDaemon.java:64-66` has to be resolved: Reduce the data abstraction coupling of EndsDaemon in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck... The puzzle was created by Nicolas Filotto on 22-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@alex-palevsky this is not urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is not urgent.

@original-brownbear right, I removed "urgent" tag

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear got it, "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear OK, I will try to assign someone else

**Comment by alex-palevsky** [comment]
@original-brownbear We are done here, thanks all
