### ISSUE TITLE
Profiles.java:108-115: Add integration test to be...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1072]
Puzzle `1039-d8a49c64` in `src/main/java/com/rultor/profiles/Profiles.java:108-115` has to be resolved: Add integration test to be sure that validation exception will eventually be posted as an Answer in GitHub. After you create integration test, add `validated` method call in `fetch` method: `...this.validated(master, this.merged(...`. Modify `merged` method implementation: merged profile is a `.rultor.yml` form result of real `git merge` of master branch and fork branch. We need real `git merge` result here. See some details here: https://github.com/yegor256/rultor/pull/1064/files#r56796959... The puzzle was created by Maksimenko Vladimir on 25-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear milestone set to `2.0` (correct me if I am wrong)

**Comment by original-brownbear** [comment]
@alex-palevsky assign someone if possible please :)

**Comment by original-brownbear** [comment]
@alex-palevsky this is not urgent.

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is not urgent.

@original-brownbear OK, I un-labeled it as "urgent" tag

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear no problem, I will try to find somebody else

**Comment by alex-palevsky** [comment]
@original-brownbear Closing this issue now...
