### ISSUE TITLE
Container name already used

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#1080]
Hi, I'm getting this on merge on https://github.com/coala-analyzer/coala/pull/1989 and https://github.com/coala-analyzer/coala-bears/pull/310:

```
docker: Error response from daemon: Conflict. The name "/coala-analyzer_coala-bears_310" is already in use by container 29212a1f7605cb4b52fbbc221f6d672b7dcdac25ca2a952aeacac043c03c7a29. You have to remove (or rename) that container to be able to reuse that name..
```

**Comment by original-brownbear** [comment]
@sils1297 this is a result of #1063 I'm afraid.
Rultor Docker daemon is out of disk space and likely that container was not properly killed because the daemon died at some point. Fixing the disk space issue will clean up that container for sure though.
Sorry for that, we're on it in #1063.

**Comment by sils1297** [comment]
This one seems to be resolved, may there be another issue behind this symptom?

**Comment by original-brownbear** [comment]
@sils1297 I don't think so, plus we're pushing hard for an infrastructure upgrade to move away from a single point of failure in the Docker runner, so very soon this thing happening again will be effectively impossible :)

**Comment by sils1297** [comment]
/me knows this problem well and is very happy gitmate.io doesn't need scaling yet :)
