### ISSUE TITLE
pom.xml:777-784: build docker image and run...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1082]
Puzzle `1055-4f9e2bff` in `pom.xml:777-784` has to be resolved: build docker image and run sshd container (see src/docker-it/run_docker_sshd.sh), run integration tests (port information located at target/sshd.port, host is predefined) and than tear down container (see src/docker-it/clear_docker_sshd.sh). Need to be configured to run in Travis. Adjust com.rultor.agents.daemons.StartsDaemonITCase#talk to use ssh into the dockerized SSH daemon when the profile docker-tests is active. Add a quick explaination of this test feature to the readme containing what it does and how to run the tests with this profile active.... The puzzle was created by Armin Braun on 30-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by original-brownbear** [comment]
@alex-palevsky lets wait on #1066 here.

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@alex-palevsky this is not urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is not urgent.

@original-brownbear sure, thanks, I removed "urgent" tag to it

**Comment by alex-palevsky** [comment]
@dalifreire the task is yours now go ahead

**Comment by dalifreire** [comment]
@alex-palevsky Please, stop assign me into no-java tasks!! I'm a Java developer with no experience with Docker or bash scripts. Pay attention to the skills of the people before assign a task and choose the right people for the tasks. You already penalizes me 30 points this week for the same reason.

**Comment by original-brownbear** [comment]
@alex-palevsky reassign this to me please.

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear sure, the ticket is yours, go ahead

**Comment by alex-palevsky** [comment]
@original-brownbear The issue should be closed..

**Comment by alex-palevsky** [comment]
@original-brownbear **30 mins** added to your account (payment number `AP-7NX09571YL959502W`), many thanks for your contribution! 96 hours and 13 mins spent here.. +30 added to your rating, current score is: [+3460](http://www.netbout.com/b/36646?open=rating)
