### ISSUE TITLE
StartsECS.java:54-57: RegistersShell must register SSH params...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1088]
Puzzle `629-bf520350` in `src/main/java/com/rultor/agents/ecs/StartsECS.java:54-57` has to be resolved: RegistersShell must register SSH params "host", "port", "login", "key" for ecs on-demand container, if this one was successfully started. Successfully start means that these parameters exist in /talk/ec2... The puzzle was created by alevohin on 18-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear done, the task is yours, go ahead

**Comment by original-brownbear** [comment]
@alex-palevsky PR here #1096 just to keep track, this has fortunately become obsolete.

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks, closed

**Comment by alex-palevsky** [comment]
@original-brownbear **30 mins** sent to your balance (ID `AP-1GJ62943MN921133F`), many thanks! It took 167 hours and 26 mins.... +30 to your rating, your total score is [+4149](http://www.netbout.com/b/36646?open=rating)
