### ISSUE TITLE
StartsECS.java:61-64: Implement the ability to use...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1089]
Puzzle `629-bb1a14ed` in `src/main/java/com/rultor/agents/ecs/StartsECS.java:61-64` has to be resolved: Implement the ability to use Rultor with any AWS account, by providing the credentials to it via the encrypted assets and a respective configuration setting in the .rultor.yml. Document the implementation properly in the Rultor documentation.... The puzzle was created by Maksimenko Vladimir on 7-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by alex-palevsky** [comment]
@original-brownbear since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@alex-palevsky assign me here please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me here please.

@original-brownbear sure, the task is yours now

**Comment by original-brownbear** [comment]
@alex-palevsky more time please, sorry will get to this asap (1-2days) but some high priority tasks interfered here.

**Comment by alex-palevsky** [comment]
> @alex-palevsky more time please, sorry will get to this asap (1-2days) but some high priority tasks interfered here.

@original-brownbear OK, no problem, take your time

**Comment by alex-palevsky** [comment]
@original-brownbear Closing..

**Comment by alex-palevsky** [comment]
@original-brownbear **30 mins** added to your account (payment number `AP-91P42200FA019602K`), many thanks for your contribution! 5903 hours and 35 mins spent here.. +30 to your rating, your total score is [+2573](http://www.netbout.com/b/36646?open=rating)
