### ISSUE TITLE
Rultor ignores changes in `.rultor.yml` from PR

### ISSUE THREAD

**Issue by mkanev** [yegor256/rultor#1099]
I've changed JDK version to 1.8 so I needed Rultor to use anoher Docker image. I've tried to change docker image in branch `develop` ([PR](https://github.com/waveaccess/msbotframework4j/pull/7) was `develop`->`master`). Every command to rultor ignored new configuration. Only the change in `master` branch affected the build process to go in the right path.
It would be great to mention this behavior somewhere in the [Reference guide](http://doc.rultor.com/reference.html) or fix it.

Link to PR: [here](https://github.com/waveaccess/msbotframework4j/pull/7)

**Comment by original-brownbear** [comment]
@mkanev actually we're close to changing this behaviour to be more like that of e.g. Travis and not ignore changes. Only issue #1072 remains and this will be resolved.

**Comment by original-brownbear** [comment]
@mkanev sorry missed this earlier, maybe take a look at #1039. This is what's being implemented right now, if it's in line what you're expecting in terms of functionality, could you please close this ticket ? :)
Thanks!

**Comment by mkanev** [comment]
@original-brownbear yeah, thats close enough. Thanks.
