### ISSUE TITLE
Refactor method Answer.post(...)

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1104]
Method [Answer.post(...)](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/github/Answer.java) can be refactored since now it **uselessly reverts** the list of comments to later iterate it using an enhanced for loop. 

The call ``Collections.reverse(comments);`` can be omitted and the list of comments can be iterated backwards, like this: 

```
for(int idx=comments.size()-1; idx>=0; idx--) {
     //....
}
```

This way, the method's complexity is reduced signifiantly since we get rid of the iterations done while reverting the list. Also, the logic is more visible this way.

**Comment by amihaiemil** [comment]
@alex-palevsky @original-brownbear I created PR #1107 for this.

**Comment by alex-palevsky** [comment]
@original-brownbear take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@amihaiemil sorry gotta shoot this one down according to http://at.teamed.io/policy.html#13 :/, also and more importantly I don't even necessarily see this as making things more readable.
Reverting the comments list is very clear to me, iterating over an Iterable the "old-school" way just to get the backwards in there is very strange to me.

**Comment by amihaiemil** [comment]
@original-brownbear sure, no worries
