### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by Hrabovszki1023** [yegor256/rultor#1108]
Hi @yegor256 

I find your article http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html and now try to implement this "one click" for my project.

now there is a point where i need some help.

i get following error from rultor: 

```
+ git push --all origin
ERROR: Permission to Hrabovszki1023/OKW.git denied to rultor.
fatal: Could not read from remote repository.
```

* maven executes all test without errors
* the files "/home/r/settings.xml", "/home/r/secring.gpg" and "/home/r/pubring.gpg" exists

My last idea is now: Must  rultor be a "collaborator" in the project? - I invite rultor to the project. is this correct?

Can you give me some hint?

Best greetings from germany

Zoltan

**Comment by original-brownbear** [comment]
@Hrabovszki1023 best greetings back from Germany :)

> My last idea is now: Must rultor be a "collaborator" in the project? - I invite rultor to the project. is this correct?

Yes this is the trick most likely, did you give Rultor write access to the repository ?

**Comment by Hrabovszki1023** [comment]
Hi @original-brownbear ,

THX for your response,
I have invited rultor to the repository "Hrabovszki1023/OKW" and it is now "awaiting for rultor's response".
i think the next step is: somebody has to accept the invitation at the rultor-user side: Is there someone, who can accept my invitation? -> then rultor has "Collaborator access" with read/write access...

https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account.

rainy day greetings from the lake constance :-(

Z

**Comment by original-brownbear** [comment]
@Hrabovszki1023 maybe try revoking and posting the invitation fresh?
You may have noticed massive issues with GitHub notifications a while back, maybe your invitation got "lost" ?
If that doesn't help, I'll look into what could have caused this :)

**Comment by Hrabovszki1023** [comment]
"Moin" Armin,

I revoke the invitation and add rultor as a new collaborator to the project.

Zoltan

**Comment by original-brownbear** [comment]
@Hrabovszki1023 worked ? :)

**Comment by Hrabovszki1023** [comment]
@original-brownbear  Yes! - It is "geil!" ;-)

THX for your help....
And many thanks to the team for rultor!

Zoltan

**Comment by original-brownbear** [comment]
@Hrabovszki1023 anytime :), could you please close the ticket ?

**Comment by Hrabovszki1023** [comment]
>>could you please close the ticket ?
Yepp!

**Comment by original-brownbear** [comment]
@Hrabovszki1023 thanks!
