### ISSUE TITLE
rultor_retry for commands that fail sometimes

### ISSUE THREAD

**Issue by AbdealiJK** [yegor256/rultor#1109]
It would be nice to provide a command which essentially runs a command multiple times if the first invocation of the command fails.

For example, uploading to pip fails frequently. - Example: https://github.com/coala-analyzer/coala-bears/pull/472

In such cases, what is needed is something to keep trying a command (if it fails) until it succeeds. Travis has a command called `travis_retry` [link](https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies)  which does this.

It would be nicer to provide a command like `rultor_retry 10 <command>` which retries the command to a maximum of 10 times.

Note: Yep, we can roll out our own solution for this, but it would be useful for other users if rultor provides a helper like travis does.

CC @sils1297

**Comment by original-brownbear** [comment]
@AbdealiJK bad news I fear :/ Rultor is designed to be an as simple as possible chatbot that merges your PRs :), this kind of functionality is not what we're currently aiming for sorry.

**Comment by AbdealiJK** [comment]
Hm, I understand @original-brownbear . Thanks for the reply :) . Closing this then
