### ISSUE TITLE
Frooze execution

### ISSUE THREAD

**Issue by velo** [yegor256/rultor#1110]
I managed to freeze rultor
http://www.rultor.com/t/8683-224512902

can someone kill my build?

**Comment by original-brownbear** [comment]
@velo just run `(at)rultor stop` :) that will kill the build for you ;)

**Comment by velo** [comment]
hey @original-brownbear 
seems our little buddy is out again

https://github.com/velo/apgdiff/issues/1

**Comment by original-brownbear** [comment]
@velo sorry bit late to the party here :), working fine for me now, can we close here or do you still have issues ?

**Comment by velo** [comment]
Seems to be fine now!

Thanks

**Comment by velo** [comment]
@original-brownbear  On a second though

Seems rultor is only running ```mvn clean test```, not my release script
https://github.com/velo/apgdiff/blob/develop/.rultor.yml#L40
http://www.rultor.com/t/8846-1

Any ideas?

**Comment by original-brownbear** [comment]
@velo sorry I'm a little confused with the question :)

I looked into the issue you linked and I can see that the release command did not perform the actions in the linked `.rultor.yml`. **But** looking at the Rultor build log you got there ( different from the one in the issue itself) it looks like all went well ?
Sorry, probably it's me :), but can you give me a link to the issue in which the above failed ? :)

**Comment by velo** [comment]
So, rultor ran, but instead of running mvn deploy it ran mvn test

**Comment by velo** [comment]
what, wait, crazy, nvm, it is correct, holy molyy...

**Comment by velo** [comment]
@original-brownbear 
what, I posted the wrong log link somehow!
This is my log:
http://www.rultor.com/t/8838-226967129
My yml:
https://github.com/velo/apgdiff/blob/develop/.rultor.yml#L40
Issue:
https://github.com/velo/apgdiff/issues/1


So, on the yml I declare deploy on the log it ran test only =/

**Comment by velo** [comment]
ha, I got it, on issue 2 @rultor gave me the wrong link =/
https://github.com/velo/apgdiff/issues/2

**Comment by velo** [comment]
Yeap, I tried again...
https://github.com/velo/apgdiff/issues/3

it ran mvn clean test insteadof mvn deploy

**Comment by original-brownbear** [comment]
@velo sorry for the late reply I finally figured it out though ... you're not using a `master` but the develop branch. Currently Rultor is only working with `master`, we are implementing other default branches though, there is an open issue for that. Please close this one as a duplicate .)

**Comment by velo** [comment]
Ok, thanks
