### ISSUE TITLE
Irrelevant CI?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1112]
Currently rultor uses a lot of CIs and most of them fail due to configuration issues.
They should be fixed or removed (not all of them, of course) since right now they are quite irrelevant. It will eventually lead bugs in production because at some point no one will open the failed builds anymore.

e.g. I make a PR, there are 5 checks out of which 3 fail due to some missing parameter or errors like "fail-on-windows" (but there isn't actually any fault with the project or the tests). Not to mention it looks bad to have a lot of failed builds on the front page.

**Comment by alex-palevsky** [comment]
@original-brownbear please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@amihaiemil just ignore it sorry :D, Yegor wants to keep these around ;)

**Comment by amihaiemil** [comment]
@original-brownbear I don't see why but ok :D
