### ISSUE TITLE
Pull out Action.message() into sepparate class

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1113]
Currently the way a message is built [here](https://github.com/yegor256/rultor/blob/7a5d5804649ee9847674c43e75ae284b5dedeb40/src/main/java/com/rultor/agents/github/Answer.java) is very **procedural**. The method 
`private String msg(final boolean success, final String text)` can be turned into the `Message` interface.

Then we have `AddressedMessage implements Message`,  which builds the message the same way as `msg(...)`

A `Message` also takes the original `Comment` (used in building the text message and accessing the Issue to to post the message)

With these changes, the class `Action` is refactored as follows: 

1) It has a `Message` attribute instead of a `Comment`
2) Method `post()` loses all its parameters (which are now obsolete):
- `success` boolean is gone  (whereever we previously had `new Answer(Comment).post(true, ...)` and `new Answer(Comment).post(false, ...)` we now have `new Answer(AddressedMessage(issueAuthorLogin, commentAuthorLogin)).post()`and `new Answer(AddressedMessage(commentAuthorLogin)).post()`
- `msg` will be returned by the method `Message.body()`
- `Objer args...` is obsolete anyway, since the `message` is formatted before the method call... it is already so, with the 1 single exception in `QnIfUnlocked`

3) method `private String msg(...)` is gone.

**Comment by alex-palevsky** [comment]
@original-brownbear dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@amihaiemil sorry but I don't get this at all, now instead of the just the `Answer`  class I also have to set up an instance of `AddressedMessage` for every comment Rultor makes, what are we really gaining here ?

**Comment by amihaiemil** [comment]
@original-brownbear a more modular, object oriented design?

I think it looks better like this and if you change the way a message is built you just work in ``AddressedMessage`` and you have unit tests for it . I made the PR as an example of how I would do the changes.

Not to mention you can have more types of ``Message``s without changing answering logic. Class ``Answer`` is also lighter. 

And we get rid of all those parameters.. you look at an ``Answer`` call right now and what does that ``true/false`` do? I have to go in that msg method to look around. What are those ``Object...`` parameters? - they are used only in 1 place and could be get rid of

**Comment by amihaiemil** [comment]
@original-brownbear Of course it would be another idea to make ``AddressedMessage`` implement interface ``Comment`` from jcabi-github... there are more options here to make it look cool and more decoupled :D

**Comment by amihaiemil** [comment]
@original-brownbear what do you think? Does it make more sense now? :D

**Comment by amihaiemil** [comment]
@original-brownbear ping

**Comment by original-brownbear** [comment]
@amihaiemil sorry for the delays, very crazy week :)
but ...
sorry I really don't see much value in this. I mean to me it already seems as though stacks are way too deep here, if we simply wrap another object around things without making any actual advances in the logic of processing GitHub comments.
I don't think I want to pursue this kind of change further without seeing an actual benefit in this, to me it seems like this is simply introducing another layer period.

**Comment by amihaiemil** [comment]
@original-brownbear well, to me its much cleaner with the change ^^ i don't know what else to say to endorse the change. What I've already said seem like good reasons to me.

**Comment by amihaiemil** [comment]
@yegor256 what do you think here?

**Comment by yegor256** [comment]
@amihaiemil I understand what you're trying to achieve, but your solution is even more procedural :) this `AnsweredMessage` is a DTO (data transfer object), which is a terrible thing in OOP. if you really want to improve the design, do it this way:

```java
Answer answer = new PersonalizedAnswer(
  new ParametrizedAnswer(
    new Answer(/*...*/),
    "hey, %s",
    "dude"
  ),
  { "yegor256", "amihaiemil" }
);
answer.post();
```

See?

**Comment by amihaiemil** [comment]
@yegor256 
By ``DTO`` should I understand an object that simply takes data when constructed and returns the same data through a method, for some other object to consume? 

If that's the case, I agree it's not a nice design, but  ``AddressedMessage`` actually builds the message in ``body()``, for ``Answer`` class to use (so it doesn't just hold data).  Then again, ``Answer`` class might use other types of ``Message``.

It's simply decoupling answering logic (which checks for 5 comments, some anti spam stuff etc) from the message building logic. 

Your idea looks nice, but I think it requires a lot more redesign then I pointed out.

**Comment by amihaiemil** [comment]
@yegor256 However, I'll look into it when I have some time

**Comment by yegor256** [comment]
@amihaiemil yes, a DTO is something that basically carries data from one place to another. doing some processing of data inside doesn't make it better. it's still a DTO. what I'm saying is that your changes are actually [Introduce Parameter Object](http://refactoring.com/catalog/introduceParameterObject.html)  refactoring, which, in my opinion, is an anti-pattern

**Comment by yegor256** [comment]
@amihaiemil is this still an issue? If not, please close this ticket.

**Comment by amihaiemil** [comment]
@yegor256 It was just a refactoring idea, which you guys didn't like :( 
Closing :D

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1113`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1113` is not in scope.
