### ISSUE TITLE
on which branches does rultor operate?

### ISSUE THREAD

**Issue by codejanovic** [yegor256/rultor#1115]
Hi there,

i was not able to find any information about on which exact branch/commit rultor is performing a tag/release/deploy, when trying to release or deploy a new version. 
After investigating various projects using `rultor`, i could not find a single project with more than a master branch - so yeah, in this case rultor will tag the latest commit from the master branch used in those projects. 

In my case my default-branch on Github is always called `develop`. This is the branch every feature is getting merged. The version i want to release is always tagged on `master` branch.

So what I am curious about is, **how do i tell rultor** ..
* .. to deploy the current state of `develop` to maven snapshot repository and ..
* .. to make a release based on the latest commit of branch `master` and deploy this one to maven staging

Thanks in advance,
Aleks

**Comment by original-brownbear** [comment]
@codejanovic it's all working on `master` at present, but work is being done to allow choosing another default branch. This can be closed therefore I think, sorry the functionality is not yet available :)

**Comment by codejanovic** [comment]
@original-brownbear okay thats nice. my fear was that rultor may only operate on the selected **default branch**, whether or not this is the master branch. I will close this issue, thanks for your reply.
