### ISSUE TITLE
new server

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1118]
I just migrated to a new EC2 machine and it is very unstable...

**Comment by yegor256** [comment]
@original-brownbear this is what I have now:

```
$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ip-172-30-0-11
ID: C7SX:L2XH:NSA7:ZQ7Y:X7ZE:MPHW:5G7L:O4FT:AES5:3GUQ:AI6W:66FP
Docker Root Dir: /mnt/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

It works fine for a few builds and then stops deleting containers with `--rm` option. Then I restart docker with `sudo service docker restart` and it stops answering anything on the command line (just hangs) and the entire machine becomes unresponsive. That's so sad.

**Comment by original-brownbear** [comment]
@yegor256 I think this is this bug https://github.com/docker/docker/issues/18758 which is essentially an issue with the AUFS file system. Heed my words (you may remember I wrote this elsewhere) and use direct lvm storage instead of AUFS. Installation is documented here: https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/ :)

**Comment by yegor256** [comment]
@original-brownbear OK, will try now. b3.rultor.com already points to the old server

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1118`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1118` is not in scope.
