### ISSUE TITLE
lack of specific versions in Dockerfile

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1119]
At the moment we don't have specific versions for apt-get and other packages in `src/docker/Dockerfile` and this leads to build instability, see: https://hub.docker.com/r/yegor256/rultor/builds/

Let's go through the entire Dockerfile and set versions to all packages.

**Comment by yegor256** [comment]
@alex-palevsky assign @original-brownbear to this pls

**Comment by original-brownbear** [comment]
@yegor256 duplicate issue ;) see https://github.com/yegor256/rultor/issues/1010, close this one and I'll handle #1010 ?

**Comment by yegor256** [comment]
@original-brownbear indeed is a duplicate, thanks
