### ISSUE TITLE
Support merging to any other branch than master

### ISSUE THREAD

**Issue by RomanTsegelskyi** [yegor256/rultor#1123]
I couldn't find it in any docs or past issue, so I am sorry if it is a duplicate, but does rultor support other git workflows than [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)? Is there any plan for that?. I am primarily interested in [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and merging into other branches than `master`

**Comment by alex-palevsky** [comment]
@original-brownbear please dispatch this issue

**Comment by adhikasp** [comment]
I vote on this issue 👍 

For search visibility
rultor merge on non master branch

**Comment by php-coder** [comment]
That's sad. I wanted to use it for merging into `prod` branch but I see that's impossible..

**Comment by yegor256** [comment]
@php-coder this is fixed, see https://github.com/yegor256/rultor/issues/1581
