### ISSUE TITLE
Command in a review summary doesn't work

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#1128]
Recently, Github introduced new way for reviewing PRs
Looks like rultor command doesn;t work if placed in the review summary

**Comment by alex-palevsky** [comment]
@original-brownbear please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by original-brownbear** [comment]
@longtimeago right just tried it ... doesn't work indeed

**Comment by original-brownbear** [comment]
@alex-palevsky valid bug.

**Comment by alex-palevsky** [comment]
> @alex-palevsky valid bug.

@original-brownbear added "bug" tag to this issue

**Comment by alex-palevsky** [comment]
@longtimeago since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
@longtimeago thank you for the ticket reported, I topped your account for 15 mins, transaction `102302377`

**Comment by pnatashap** [comment]
It will not work even now. 
Url for mentioning from review will be like https://github.com/USER/REPO/pull/5386/files#r1472829831
It is partially linked with #1074 because rultor will try to parse id after last / symbol and fail.

@yegor256 WDYT?

**Comment by yegor256** [comment]
@pnatashap what do you suggest?
