### ISSUE TITLE
Can't download dependency from remote maven repo

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1129]
Apparently the rultor [build](http://www.rultor.com/t/9932-259662917) fails because maven can't fetch a dependency. This dependency is in my custom mvn repo, not released yet in mvn central (the repo has no credentials, so it should  not be a problem of authentication)

This custom repo is declared in [pom.xml](https://github.com/opencharles/charles-github-ejb/blob/1bdc9c3bd63f1d57f28d23d942ad1f7b6f5a7029/charles-rest/pom.xml) and the project builds fine on travis and locally (after I remove the mvn tmp folder of course)

**Comment by amihaiemil** [comment]
@original-brownbear any clues about this? :D

**Comment by alex-palevsky** [comment]
@original-brownbear please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@amihaiemil can you link the line in your `pom.xml` that declares said repository ?  I can't see it? :)

**Comment by amihaiemil** [comment]
@original-brownbear Yes, [here](https://github.com/opencharles/charles-github-ejb/blob/1bdc9c3bd63f1d57f28d23d942ad1f7b6f5a7029/charles-rest/pom.xml) - it's from history... in the meantime I released that lib to maven central and got rid of the custom maven repo. 

So can't reproduce it now, but if you look [here](https://github.com/opencharles/charles-github-ejb/pull/132), I tried multiple times, with the same error... 

I saw a discussion in Yegor's blog somewhere and he said external jars should be ``wget`` in the ``install`` section, but that seems not natural to me - maven should be able to fetch dependencies if repos are declared :D

**Comment by amihaiemil** [comment]
@original-brownbear [Here](http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html#comment-2654542923) is the thread from the blog I was talking about

**Comment by original-brownbear** [comment]
@amihaiemil hmm yea it should and does work with Rultor.
I think your mistake was to not add the proper Maven repo sub path to the url of your Maven repository. Imo it should be like `http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:1452/releases` + you should put the `repositories` section at the top of your pom :) Then you should be good imo.

**Comment by amihaiemil** [comment]
@original-brownbear It was like that since a long time ago and it worked fine on travis and locally (after I removed the m2 folder too).

Anyway, it might be something with maven run in a container, I don't know - maybe that requires the repositories tag to be at the top. The path is ok, shouldn't matter - it has to be the root of the repo and then it looks after your groupid/artifact id (e.g. folder path com/amihaiemil/web/...).

It's not with rultor itself, I'm almost sure :D

**Comment by amihaiemil** [comment]
@original-brownbear anyway, I'll close this - if someone has the same problem at least they'll find this issue and see the ``wget`` option or try to put ``repositories`` on top.

Is that ok?

**Comment by original-brownbear** [comment]
@amihaiemil sure fine with me :)
