### ISSUE TITLE
Can I specify env variables to rultor?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1131]
Is it possible to specify variables to rultor, and use them in scripts? 

For instance, I would like to write a script for rultor to run in ``release`` process. The same as it commits a tag to the repo, I would like it to update the version of the projects in ``pom.xml``.

E.g. I release tag ``1.0.0``, then the version in pom.xml should automatically become ``1.0.1-SNAPSHOT``. 

I think I could write some logic in the script, take that ``tag`` variable and play with it, change it and use that, but I would rather specify ``tag`` and ``next``

**Comment by RoRoche** [comment]
Hi @amihaiemil , did you succeed using env var in .rultor.yml?

**Comment by amihaiemil** [comment]
@RoRoche I don't remember exactly, but I think you can specify any variable the way you specify the `tag` when you say "release".

I think he will take any variable when you sat ``X is `val` ``,  but I am not sure. Look over the doc files on Rultor's website, there is an example where the postgre version is specified,  if I remember well.

**Comment by RoRoche** [comment]
I need to configure secrets so can't write it clearly in the `.rultor.yml` file.

**Comment by amihaiemil** [comment]
@RoRoche you can encrypt a file using the ``rultor`` CLI tool. Write me an email and I will respond to tell you how.

**Comment by rocket-3** [comment]
>I need to configure secrets so can't write it clearly in the .rultor.yml file.

@amihaiemil, try [this answer](https://github.com/yegor256/rultor/issues/1338#issuecomment-854213711)

> Is it possible to specify variables to rultor, and use them in scripts?

> I think I could write some logic in the script, take that `tag` variable and play with it, change it and use that, but I would rather specify `tag` and `next`

You can use **any** variable from message to rultor, not only tag. You configure them in your .rultor.yml file [like that](https://github.com/databasegit/dbgit/blob/master/.rultor.yml) and pass to rultor in message, escaping value with `` chars:
>rultor deploy, tests=`*SlowTests*,!*SlowTests#*Wicked*`
