### ISSUE TITLE
Make ssh trust github.com by default?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1133]
Maybe this is a silly question (my experience in os stuff is rather average yet)

I'm trying to instruct rultor to push its commited changes to origin.
Everything seems to work as I expect, until it hits the ``git push`` command, then the command prompts for a ``yes or no`` answer, regarding the trust of host github.com

http://www.rultor.com/t/9994-261607805

I've been trying all afternoon to make it work (actually, I think I managed to crash rultor in the process - it was down for a little time). I tried using ``yes``, command, ``echo yes`` before the git push and all sorts of tricks I found on stackoverflow, but nothing worked.

Any help? :D

**Comment by amihaiemil** [comment]
@original-brownbear help? ^^

**Comment by original-brownbear** [comment]
@amihaiemil http://stackoverflow.com/questions/9008309/how-do-i-set-git-ssl-no-verify-for-specific-repos-only helpful ? :)

**Comment by amihaiemil** [comment]
@original-brownbear nope :( I tried but it doesn't work -  the same behaviour. But that thing is for ssl/https, here we are over ssh, right?

**Comment by original-brownbear** [comment]
@amihaiemil is Rultor added to your repo having write access ? :)

**Comment by amihaiemil** [comment]
@original-brownbear yes of coure.. there must be somthing, since it's able to push tags, why couldnt it push a branch? I'll look more into it tomorrow and let u know. I'm out for the evening ^^

**Comment by amihaiemil** [comment]
@original-brownbear I didn't find a workaround, but it turns out I don't need it anymore - rultor pushes all the branches (including master) right after removing branch ``__rultor`` :). I don't understand why rultor can push without being asked, but if I do it from my .sh file, it asks... eh, well :D

**Comment by amihaiemil** [comment]
@original-brownbear btw, all this I found while writing a [script](https://github.com/opencharles/charles/blob/master/rrv.sh) to update the version in pom.xml. Maybe we could start using something similar (maybe a little more complex)?

Right now teamed.io's projects only use mvn versions plugin to update the version in the released jar, but the pom.xml on master always stays the same, which is quite confusing - I personally never know what version to write in a since annotation.

**Comment by original-brownbear** [comment]
@amihaiemil yea I hear you with the versions, that stuff could be made a little more granular. 

Then again there's not only upsides to using like `0.7-SNAPSHOT`, `0.8-SNAPSHOT` and so on and so forth, relative to just sticking with `1.0-SNAPSHOT`. Makes working with snapshots locally a lot more cumbersome for one (always gotta watch for using the right snapshot version etc.), also I think it creates some other issues with the way we host the JavaDoc/Sites.

That said :) we can close here right, no issues regarding Rultor here?

**Comment by amihaiemil** [comment]
@original-brownbear sure, thanks a lot :)
