### ISSUE TITLE
Rultor should *always* prompt for architect confirmation for release command

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/rultor#1134]
Right now, Rultor will prompt for architect's confirmation under the following conditions:

* The messenger is a **commander**
* The messenger is **not** an architect
* The issue is a pull request which is **not** authored by an architect.

The third condition is the problematic one here. For merges, that is perfectly fine since we don't need the architect to confirm his own work. However, any commander can bypass the architect and release a new version by simply looking for the architect's old PRs.

We should prompt for confirmation all the time whenever we do `@rultor release`, regardless of whether the PR was created by the architect or not.

**Comment by amihaiemil** [comment]
@carlosmiranda I don't agree - I think no one should ever be able to give commands to rultor without an architect's approval. As an architect, I make a PR which is not yet ready or whatever - If someone merges it, releases or deploys without my permission, then it's a problem.

**Comment by carlosmiranda** [comment]
@amihaiemil that's up to @original-brownbear to decide

**Comment by amihaiemil** [comment]
@carlosmiranda of course, I was just adding my opinion :D

**Comment by original-brownbear** [comment]
@carlosmiranda yea @amihaiemil is right here, #1105 basically enocompasses this one. Sorry duplicate imo.
