### ISSUE TITLE
Rultor merge gives an error: 'cid' file is absent, container wasn't started correctly

### ISSUE THREAD

**Issue by meetmangukiya** [yegor256/rultor#1138]
Log link http://www.rultor.com/t/10226-266300430

**Comment by yegor256** [comment]
@meetmangukiya it can't decrypt your assets:

```
gpg: armor header:
gpg: CAST5 encrypted data
gpg: encrypted with 1 passphrase
gpg: decryption failed: Bad session key
```

Are you sure you encrypted them right?

**Comment by meetmangukiya** [comment]
Yes, just as suggested in the doc `rultor encrypt -p meetmangukiya/gistey`

**Comment by meetmangukiya** [comment]
I have this working with `gpg2`, you may close the issue if you want, though I don't think the bug is found :thinking:

**Comment by amihaiemil** [comment]
@meetmangukiya just for the record, it's the same issue as [this](https://github.com/yegor256/rultor/issues/853). You should close this issue, since you are its author :)

**Comment by jayvdb** [comment]
Note i've raised https://github.com/yegor256/rultor/issues/1221 about a similar problem.
