### ISSUE TITLE
Rultor not performing commands from valid user

### ISSUE THREAD

**Issue by Ardesco** [yegor256/rultor#1144]
My rultor.yml is here:

https://github.com/Ardesco/appium-maven-plugin/blob/master/.rultor.yml

My attempts to use rultor are here:

https://github.com/Ardesco/appium-maven-plugin/issues/1

For some reason it's not picking up that I have permission to give commands, I've gone through the docs and can't see anything wrong with my YAML.

It's worked fine for me on other projects, so I'm suspecting I may have done something dumb, but I can't see what it is.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by Ardesco** [comment]
Looks like it didn't like it needed an upper case A instead of a lower case a in Ardesco.

Strangely that's never mattered before in other projects.  It would be good to get this added to the documentation.

**Comment by yegor256** [comment]
@Ardesco this shouldn't matter, see this code: https://github.com/yegor256/rultor/blob/1.62.2/src/main/java/com/rultor/agents/github/qtn/QnByArchitect.java#L100-L115 We lower-case both your login and the text from YAML. Either case should work.

**Comment by Ardesco** [comment]
Not sure what was going on then, maybe look at the commands that were being sent over and check it with the logs to see why it couldn't understand me?  Either way it's working for me now.

**Comment by yegor256** [comment]
@Ardesco I'm closing, since it works fine
