### ISSUE TITLE
Could we have the role of "deputy" architect?

### ISSUE THREAD

**Issue by nqafield** [yegor256/rultor#1146]
This is maybe not the best name for the role, but the idea is to introduce a kind of sub-architect who has some "privileges" beyond the standard contributor.

For example, while the architect still has final say, maybe they could assign someone to a pull request who has the sub-architect role who could then kick off subsequent merges of a pull-request if the architect is not available and if the PR has already been approved (merge has been requested once already) by the architect but the build has failed for some minor reason and then been fixed by the contributor.

Having kicked off the initial merge the architect assigns someone to ask @rultor to request further merges.

What do you think?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@pa9ey sounds like an interesting idea, let's keep thinking about it.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1146` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
