### ISSUE TITLE
Usage of loopback devices is strongly discouraged for production use

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1147]
Hi there!
Every rultor log contains this warning:
```
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
```
Warning appears after `docker run` command.

This issue on stackoverflow: https://stackoverflow.com/q/31620825/1723695

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor release, tag is `1.64.1`

**Comment by yegor256** [comment]
@g4s8

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 this issue is gone

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1147`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1147` is not in scope.
