### ISSUE TITLE
Prevent rultor from doing anything extra on release

### ISSUE THREAD

**Issue by trajano** [yegor256/rultor#1149]
I am trying to do a rultor release on one of my projects to try the functionality and I noticed that it started to do something after it ran the `script` section.  https://github.com/trajano/reverse-proxy-auth-sonar-plugin/issues/10#issuecomment-285167050

Is there a way to prevent that?  My script will already perform the pushes needed to GitHub and I do not want the files committed into the master stream.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by trajano** [comment]
One thing to work around is to use "deploy" **but** it does not seem to accept any parameters.

**Comment by yegor256** [comment]
@trajano the idea of `release` command is to give you an isolated branch and then turn everything you create there into a Git "tag". If you don't want that, use `deploy`. It accepts (must accept) parameters without any issues. If it doesn't, please create a new ticket.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1149`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1149` is not in scope.
