### ISSUE TITLE
Rultor settings.xml with github.com

### ISSUE THREAD

**Issue by trajano** [yegor256/rultor#1150]
Can rultor have a settings.xml with github.com so we can use it with `mvn release:prepare` and have it commit there?  One thing to note though is the log should detect whether the API token is shown or somehow doing something malicious with it so it cannot be reused...

Another thing I can think of but I am not sure how is to have it automated so a new token is created just for the build and have it destroyed as soon as the build is done.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by trajano** [comment]
https://docs.travis-ci.com/api#creating-a-temporary-github-token shows how to create a temporary token on GitHub.

**Comment by yegor256** [comment]
@trajano what all this will be for? And another question: are you aware of "assets" in rultor? Look at how this `settings.xml` work in rultor deployment: https://github.com/yegor256/rultor/blob/master/.rultor.yml#L17

**Comment by trajano** [comment]
I saw assets, but that requires a private repository which I do not have.

The purpose is that `mvn release:prepare` with GitHub which will do a `git push` using the data in `settings.xml` so that we can use `rultor` as the user rather than our own.  It will also simplify the configuration so that the rultor user does not need to go though setting up additional keys and tokens and somehow merge it with the rultor.yml

**Comment by yegor256** [comment]
@trajano is this still an issue? If not, please close this ticket. Otherwise, let's continue the discussion, but please start your messages with my name, so I don't lose them.

**Comment by trajano** [comment]
Closing since I stopped using rultor already.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1150`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1150` is not in scope.
