### ISSUE TITLE
Is there a way to find out who called rultor?

### ISSUE THREAD

**Issue by adtac** [yegor256/rultor#1151]
From inside a script. Can this be made available as an env variable?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@adtac yes, it may. Should not be difficult to implement. Let me try...

**Comment by adtac** [comment]
@yegor256 any updates?

**Comment by yegor256** [comment]
@adtac fixed in b3e58634d Let me try to release it

**Comment by yegor256** [comment]
@adtac documented in 4c1e0948c

**Comment by yegor256** [comment]
@rultor release, tag is `1.65`

**Comment by yegor256** [comment]
@rultor status

**Comment by yegor256** [comment]
@rultor release, tag is `1.65`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.65`

**Comment by yegor256** [comment]
@adtac seems to be working, try it out

**Comment by adtac** [comment]
@yegor256 I can confirm this works pretty nicely :)

Closing this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1151` was not in scope

**Comment by yegor256** [comment]
@adtac thanks :)
