### ISSUE TITLE
Re-estimate project size

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#1152]
The latest estimate is rather old (created on 28-Feb-2017),we have to create a new one as explained [here](https://github.com/teamed/est)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by alex-palevsky** [comment]
@original-brownbear I set the milestone to 2.0 since there is nothing set yet

**Comment by alex-palevsky** [comment]
@yegor256 Closing this issue now...

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1152` was not in scope
