### ISSUE TITLE
Bug in QnVersion reply phase

### ISSUE THREAD

**Issue by valery1707** [yegor256/rultor#1154]
Then generating response to command `version` rultor make incorrect link to commit:
> My current version is 1.62.3, Git revision is [`ef166fc7f`](https://github.com/yegor256/rultor/commit/1.62.3)

Real example: https://github.com/valery1707/jcommander-ext/issues/2#issuecomment-295822793

I prepare PR with fix

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@valery1707 it's merged

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1154` was not in scope
