### ISSUE TITLE
EndsDaemon.java:64-66: Reduce the data abstraction coupling...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1161]
The puzzle `1053-dc86a5cc` in [`src/main/java/com/rultor/agents/daemons/EndsDaemon.java`](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/daemons/EndsDaemon.java) (lines 64-66) has to be resolved: Reduce the data abstraction coupling of EndsDaemon in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck

The puzzle was created by Nicolas Filotto on 22-Mar-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1053-dc86a5cc` has disappeared from the source code, that's why I closed this issue.
