### ISSUE TITLE
Amazon.java:42-45: Add implementation for...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1165]
The puzzle `629-3b4a7478` in [`src/main/java/com/rultor/agents/ecs/Amazon.java`](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/ecs/Amazon.java) (lines 42-45) has to be resolved: Add implementation for com.rultor.agents.ecs.Amazon. It must create com.amazonaws.services.ecs.AmazonECSClient with config params "credentials", "zone", "type", "key". Method runOnDemand must finally wait for started container and check if start was successful.

The puzzle was created by Maksimenko Vladimir on 02-Apr-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `629-3b4a7478` has disappeared from the source code, that's why I closed this issue.
