### ISSUE TITLE
StartsECS.java:51-53: Implement...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1166]
The puzzle `629-97e18362` in [`src/main/java/com/rultor/agents/ecs/StartsECS.java`](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/ecs/StartsECS.java) (lines 51-53) has to be resolved: Implement com.rultor.agents.ecs.StopsECS agent. It must stop ECS on-demand container if it was started at StartsECS agent. StopsECS must use container ARN from /talk/ec2/[@id] to stop it.

The puzzle was created by Maksimenko Vladimir on 02-Apr-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `629-97e18362` has disappeared from the source code, that's why I closed this issue.
