### ISSUE TITLE
StartsECS.java:58-60: Add new container creation classes...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1167]
The puzzle `629-efc8aa9c` in [`src/main/java/com/rultor/agents/ecs/StartsECS.java`](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/ecs/StartsECS.java) (lines 58-60) has to be resolved: Add new container creation classes for StartsECS and StopsECS to com.rultor.agents.Agents. StartsECS must be invoked before RegistersShell agent. StopsECS must be invoked after RemovesShell agent.

The puzzle was created by Maksimenko Vladimir on 05-Apr-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `629-efc8aa9c` has disappeared from the source code, that's why I closed this issue.
