### ISSUE TITLE
StartsECS.java:61-64: Implement the ability to use Rultor...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1168]
The puzzle `629-bb1a14ed` in [`src/main/java/com/rultor/agents/ecs/StartsECS.java`](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/agents/ecs/StartsECS.java) (lines 61-64) has to be resolved: Implement the ability to use Rultor with any AWS account, by providing the credentials to it via the encrypted assets and a respective configuration setting in the .rultor.yml. Document the implementation properly in the Rultor documentation.

The puzzle was created by Maksimenko Vladimir on 07-Apr-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `629-bb1a14ed` has disappeared from the source code, that's why I closed this issue.
