### ISSUE TITLE
Pull request isn't closed after Rultor's merge

### ISSUE THREAD

**Issue by extsoft** [yegor256/rultor#1171]
I merged https://github.com/extsoft/insight/pull/30 with Rultor. But pull request is still open. If I close this manually, it will be marked as unmerged. Finally, this leads to ambiguity of merge state. 

Steps to reproduce:
1. checkout new branch from `master` (`feature-x`)
2. add one commit to `feature-x`, push this and create pull request (`feature-x PR`)
3. add one more commit to remote `master`
4. ask Rultor to merge `feature-x PR`

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@extsoft rultor doesn't close pull requests. GitHub closes them automatically. And the way GitHub decides when to close it up to GitHub. We had this problem before, in some pull requests. You just have to close it manually. I believe this happens when the changes you merge are already in master.

**Comment by extsoft** [comment]
@yegor256 

> I believe this happens when the changes you merge are already in master.
No, changes were added by Rultor to the master.

If I understood correctly, Rultor rebases changes from `master` to `feature-x` branch before merge. And if rebased changes from `feature-x` will be pushed to remote `feature-x`, then pull request will be closed. I done it manually, and it works:
```
git checkout feature-x
git rebase origin/master
git push
```

**Comment by yegor256** [comment]
@extsoft no, Rultor doesn't rebase master into your branch. Instead, it takes your branch and merges it into `master`. You can see what happens right in the log Rultor publishes for you.

**Comment by extsoft** [comment]
@yegor256 this is not relevant anymore.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1171` was not in scope
