### ISSUE TITLE
su --login

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1174]
Let's add `--login` option to `su`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by yegor256** [comment]
@rultor release, tag is `1.64`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1174` was not in scope
