### ISSUE TITLE
Failing CI on GitHub commits for over a year

### ISSUE THREAD

**Issue by jayvdb** [yegor256/rultor#1178]
https://github.com/yegor256/rultor/commits/master every commit is red.  No green ticks.
This is **very** bad software engineering practise, as it makes it very unlikely that new failures will be noticed.

If there are tests which are reliably failing on a specific environment, issues should be raised about the problem, and the skip tested on that environment.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jayvdb indeed, this is not good. We will try to fix that ASAP. Thanks.

**Comment by filfreire** [comment]
@yegor256 FYI: 

**Wercker** fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project rultor: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```

example: https://app.wercker.com/buildstep/5a385d6a30acd801003cb105

---

**Travis CI** fails with:


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project rultor: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

example: https://api.travis-ci.org/v3/job/318375413/log.txt


---

**Shippable** fails:

can't find the download button to download the log files.

Language setup on shippable is  `java openjdk7`
example: https://app.shippable.com/github/yegor256/rultor/runs/1980/1/console

---

**AppVeyor** fails with:
```
[00:00:58] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.AlwaysFail failed with message:
[00:00:58] You should use Unix-like or Mac OS to successfully build Rultor.
[00:00:58]                                                 With an other OS you are still able to check sources with the command:
[00:00:58]                                                 'mvn qulice:check -Pqulice'
[00:00:58] Always fails!
```

example: https://ci.appveyor.com/project/yegor256/rultor/build/1082

we should probably do these:
- disable appveyor integration and delete badge from documentation;
- mention in documentation that building on Windows env is not supported;

---

@yegor256 should we create issues to handle each separately?

**Comment by yegor256** [comment]
@filfreire yes, please, let's create separate issues and fix this.

**Comment by filfreire** [comment]
@yegor256 
created separate issues to fix this:
#1233 - wercker 
#1234 - travis
#1235 - shippable
#1236 - appveyor

**Comment by Glusk2** [comment]
The common issue seems to be the fact that the minimum Java version required to build Rultor is Java 8.

**Comment by yegor256** [comment]
@jayvdb fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1178` is not assigned, can't get performer
