### ISSUE TITLE
bc: command not found

### ISSUE THREAD

**Issue by jayvdb** [yegor256/rultor#1180]
After working around the problems of https://github.com/yegor256/rultor/issues/1177 , [the log](http://www.rultor.com/t/11716-303335831) includes

```
++ bc
./run.sh: line 102: bc: command not found
+ '[' -eq 1 ']'
./run.sh: line 102: [: -eq: unary operator expected
+ echo 'load average is 0.01, low enough to run a new Docker container'
load average is 0.01, low enough to run a new Docker container
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jayvdb thanks for reporting, I believe it's fixed. Please check.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1180` was not in scope
