### ISSUE TITLE
"Could not find goal 'install-origin'"

### ISSUE THREAD

**Issue by driver733** [yegor256/rultor#1185]
Rultor started to fail all of a sudden.
`Could not find goal 'install-origin' in plugin org.apache.maven.plugins:maven-install-plugin:2.5.2 among available goals install, help, install-file -> 1m[Help 1]m`

[Full log](http://www.rultor.com/t/12012-309273523)

Everything was working fine [before](http://www.rultor.com/t/11958-308211089) (when the Maven command was`install-file`)

p.s. I am using default docker container provided by rultor.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by driver733** [comment]
Nevermind.
The error was in my config file

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1185` was not in scope
