### ISSUE TITLE
Add Git Lfs Support

### ISSUE THREAD

**Issue by smallcreep** [yegor256/rultor#1187]
Add [Git Lfs](https://git-lfs.github.com/) Support

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by pnatashap** [comment]
@yegor256 is it needed? the only thing that is needed - add it docker

**Comment by yegor256** [comment]
@smallcreep @pnatashap indeed, I think it's not related to Rultor. If something is required inside Docker container that we run -- just add it to `Dockerfile`
