### ISSUE TITLE
Cache folders/files (m2, etc.) (similar to TravisCI)

### ISSUE THREAD

**Issue by driver733** [yegor256/rultor#1192]
I would like to suggest a feature that would allow to cache the specified folders and/or files. (similar to what TravisCI allows to do). This feature is very convenient since it allows to cache m2 folder and, as a result, dramatically decrease the build time. In addition to that it frees up a lot of space in the build log.

As an example, by cacheing the m2 folder in dropbox for one of my pet projects  I was able to decrease the build time from [7 minutes](https://github.com/driver733/VKMusicUploader/pull/92#issuecomment-311467951) to [2 minutes](https://github.com/BIBO-RAM/VKMusicUploader/pull/2#issuecomment-311792283). Although this might not sound like a dramatic improvements, keep in mind that my project does not have a lot of dependencies (just apache commons, junit and gson), thus, the build time decrease should be expected to be much bigger in the projects with many dependencies.

p.s. I suggest using dropbox as a simple way to host cache files. (Using a bash [script](https://github.com/andreafabrizi/Dropbox-Uploader)) API key can be stored in a private repo and can be retrieved by Rultor. 

p.p.s [Rultor config file](https://pastebin.com/MNcrgrV7) with the caching procedure.

**Comment by yegor256** [comment]
@driver733 in order to do that, you just have to create your own Docker image and configure it in `.rultor.yml`. This image will contain everything you need to "cache".
