### ISSUE TITLE
Added Postgres to the Dockerfile

### ISSUE THREAD

**Issue by tannakartikey** [yegor256/rultor#1195]
For the application which requires a database to run tests, it would be great if the Postgresql is added to the default container.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@tannakartikey feel free to submit a pull request

**Comment by tannakartikey** [comment]
It's sent. Pls find it at https://github.com/yegor256/rultor/pull/1196


On 11-Jul-2017 12:00 AM, "Yegor Bugayenko" <notifications@github.com> wrote:

@tannakartikey <https://github.com/tannakartikey> feel free to submit a
pull request

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/yegor256/rultor/issues/1195#issuecomment-314194264>,
or mute
the thread

**Comment by yegor256** [comment]
@tannakartikey we have it in the container already

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1195` is not assigned, can't get performer
