### ISSUE TITLE
replace Guava with Cactoos

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1199]
Let's get rid of Guava entirely and migrate to Cactoos: www.cactoos.org

**Comment by filfreire** [comment]
I volunteer to work on this 👍

**Comment by filfreire** [comment]
@yegor256 assign me this issue

**Comment by yegor256** [comment]
@0crat assign @filfreire

**Comment by 0crat** [comment]
> @0crat assign @filfreire ([here](https://github.com/yegor256/rultor/issues/1199#issuecomment-333883148))

@yegor256 Job `gh:yegor256/rultor#1199` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @filfreire is not a member of this project yet, but can request to join. @filfreire check your [Zerocracy profile](http://www.0crat.com/u/filfreire) and follow the instructions.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3645](http://www.0crat.com/u/yegor256).

**Comment by filfreire** [comment]
@yegor256 this issue is not forgotten on my side, I'm working on it in
https://github.com/filfreire/rultor/tree/1199dev

**Comment by yegor256** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
@filfreire this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1199`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1199` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1199` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1199` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1199` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1199`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1199` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1199`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1199` assigned to @filfreire. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1199`, please stop working.

**Comment by filfreire** [comment]
@yegor256 - #1246 was merged, we can close this issue.

**Comment by yegor256** [comment]
@filfreire thanks a lot for your contribution!

**Comment by 0crat** [comment]
The job [#1199](https://github.com/yegor256/rultor/issues/1199) is now out of scope
