### ISSUE TITLE
sentry

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1200]
Let's add sentry.io for error tracking.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@rultor release, tag is `1.66`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/rultor/issues/1200#issuecomment-316659532))

@yegor256 Job `gh:yegor256/rultor#1200` assigned to @yegor256, please go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1200` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is +180
