### ISSUE TITLE
HTTPS is not supported

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1202]
Build logs may contain confidential information.
It's not secure to send them in plain text via internet, it would be better to use https.

BTW you can get free certificate here: https://letsencrypt.org/

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/yegor256/rultor/issues/1202#issuecomment-318157604))

@g4s8 Hey, what's up, how is it going?

**Comment by yegor256** [comment]
@g4s8 it's $20/mo at Heroku. Definitely worth it, but a bit later. Thanks.

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/rultor/issues/1202#issuecomment-318292555))

@yegor256 Job `gh:yegor256/rultor#1202` is in scope.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+165](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/rultor/issues/1202#issuecomment-318292738))

@yegor256 Job `gh:yegor256/rultor#1202` assigned to @yegor256, please go ahead.

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:yegor256/rultor#1202`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1202` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1202` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1202` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1202` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1202`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1202` assigned to @filfreire. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1202`, please stop working.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/rultor/issues/1202#issuecomment-450968282))

@paulodamaso This is what I know about this job in [C3SAYRPH9](https://www.0crat.com/p/C3SAYRPH9), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1202](https://github.com/yegor256/rultor/issues/1202) is [in scope](http://www.zerocracy.com/policy.html#14) for 17mon
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [1hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @filfreire[/z](https://www.0crat.com/u/filfreire): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3SAYRPH9?q=%7Bjob%3A%27gh%3Ayegor256%2Frultor%231202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 I'm afraid that I can't tinker with these configurations

**Comment by g4s8** [comment]
@paulodamaso it seems this bug is for rultor.com hosting owner, I suppose for @yegor256

**Comment by paulodamaso** [comment]
@yegor256 I agree with @g4s8 , please take a look at this

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/rultor/issues/1202#issuecomment-453595862))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1202](https://github.com/yegor256/rultor/issues/1202), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1202](https://github.com/yegor256/rultor/issues/1202); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@g4s8 fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1202` is not assigned, can't get performer
