### ISSUE TITLE
Link Rultor to GitCop

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1215]
Link rultor to https://gitcop.com/

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 follow-up

**Comment by yegor256** [comment]
@filfreire I tried, but their configuration options look very strange. I can't really put a regex there. Try it yourself.

**Comment by filfreire** [comment]
@yegor256 closing this issue, given the problems we had using GitCop as reported in https://github.com/yegor256/tacit/issues/84

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1215` was not in scope
