### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1216]
Tasks:
- Follow Github guideline https://github.com/blog/1184-contributing-guidelines of having a separate contributing file
- Replace "How to contribute" section's content with a link to CONTRIBUTING.md

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @filfreire

**Comment by 0crat** [comment]
> @0crat assign @filfreire  ([here](https://github.com/yegor256/rultor/issues/1216#issuecomment-335135672))

@yegor256 Job `gh:yegor256/rultor#1216` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @filfreire, total is [+150](http://www.0crat.com/u/filfreire).

**Comment by filfreire** [comment]
@yegor256 PR https://github.com/yegor256/rultor/pull/1217 closes this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1216` is now out of scope.

**Comment by yegor256** [comment]
@filfreire thanks!
