### ISSUE TITLE
GPG Issue

### ISSUE THREAD

**Issue by jloisel** [yegor256/rultor#1220]
See: https://github.com/jloisel/elastic-crud/issues/10

It was working fine back in february this year. No configuration has been changed:

> gpg: WARNING: unsafe permissions on homedir '/home/r'
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/home/r/secring.gpg' to gpg-agent
gpg: key 46A2D06531F96DB0: secret key imported
gpg: migration succeeded
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
[\u001b[1;34mINFO\u001b[m] Total time: 02:03 min
[\u001b[1;34mINFO\u001b[m] Finished at: 2017-10-30T09:48:35Z
[\u001b[1;34mINFO\u001b[m] Final Memory: 35M/721M
[\u001b[1;34mINFO\u001b[m] \u001b[1m------------------------------------------------------------------------\u001b[m
[\u001b[1;31mERROR\u001b[m] Failed to execute goal \u001b[32morg.apache.maven.plugins:maven-gpg-plugin:1.6:sign\u001b[m \u001b[1m(jcabi-sign-artifacts)\u001b[m on project \u001b[36melasticsearch-crud\u001b[m: \u001b[1;31mExit code: 2\u001b[m -> \u001b[1m[Help 1]\u001b[m
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] To see the full stack trace of the errors, re-run Maven with the \u001b[1m-e\u001b[m switch.
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
container 2d8f5f97a2ef8687d1f40f484490c5b84b3cc30cd199a169be1cf17afc6af4cf is dead
Mon Oct 30 10:48:41 CET 2017

**Comment by yegor256** [comment]
@jloisel this could be just a temporary network issue. Just try again please.

**Comment by jloisel** [comment]
I've managed to release it by myself, i'll try the next time I need to release it. Thanks for your time.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1220`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1220` is not in scope.
