### ISSUE TITLE
Tidy up "What is Rultor Section"

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1223]
Currently the "What is Rultor" section looks like this:

<img width="263" alt="screen shot 2017-11-30 at 23 53 32" src="https://user-images.githubusercontent.com/11976836/33461319-c98cfd86-d629-11e7-9f73-b8aef532c77a.png">

1) We should remove that "TBD - product statement" and put in a proper statement or paragraph explaining what is Rultor
2) The gitter badge is probably better next to other badges (suggestion)

@yegor256 FYI

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1223` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @filfreire, total is [+435](http://www.0crat.com/u/filfreire).

**Comment by filfreire** [comment]
Closing this issue. PR was merged.
