### ISSUE TITLE
Upgrade Travis and Rultor to Java 8

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1225]
**Task:** Upgrade Travis and Rultor to Java 8
@yegor256 FYI

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.67`

**Comment by filfreire** [comment]
@yegor256 thanks, can you try to merge PR #1222 again?

**Comment by yegor256** [comment]
@filfreire please close this one

**Comment by filfreire** [comment]
@yegor256 closed

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rultor#1225`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1225` is not in scope.
