### ISSUE TITLE
Setup Travis CI to work with Java 8

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1227]
Travis CI build is still working oriented to java 1.7

Looking at the raw log of a recent nightly build, https://api.travis-ci.org/v3/job/317869733/log.txt , 
it's still failing with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:
compile (default-compile) on project rultor:
Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```

(also found this issue on https://github.com/yegor256/rultor/pull/1222)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire I don't think you're right, but let's see the version: 00e13c11a

**Comment by filfreire** [comment]
@yegor256 I was wrong
```
java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
version seems to be okay, closing this issue. Thanks 👍
