### ISSUE TITLE
StartsECS.java:81-82: <body>Add Container params to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/rultor#1232]
The puzzle `629-ebd8dabe` from #629 has to be resolved:

https://github.com/yegor256/rultor/blob/4f68b94e29ee15c4d5289b367ac0fc5875c5a99c/src/main/java/com/rultor/agents/ecs/StartsECS.java#L81-L82

The puzzle was created by Yegor Bugayenko on 21-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `629-ebd8dabe` has disappeared from the source code, that's why I closed this issue.
