### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1234]
**Travis CI** fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project rultor: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```

example: https://api.travis-ci.org/v3/job/318375413/log.txt

**Comment by filfreire** [comment]
@yegor256 fyi

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire fixed, I believe

**Comment by filfreire** [comment]
@yegor256 there still seems to be problems: the execution of a given PR seems to be running from plain `master` and not from PR code. Example, the PR #1239 (to bump copyright dates), fails with this log https://travis-ci.org/yegor256/rultor/builds/324258183

**Comment by filfreire** [comment]
@yegor256 I'm closing this issue, the java 8 part seems OK. Still, I'd recommend paying attention to issue #1240

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1234` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1234` was not in scope
