### ISSUE TITLE
Bump year version to 2018

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1238]
/cc @yegor256 I'll tackle this issue.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 code was merged, closing this issue. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1238` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#1238](https://github.com/yegor256/rultor/issues/1238) was not in scope
