### ISSUE TITLE
'cid' file is absent, container wasn't started correctly

### ISSUE THREAD

**Issue by uklimaschewski** [yegor256/rultor#1242]
Just observed a keyserver timeout when building a new release:
```
+ gpgconf --reload gpg-agent
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
'cid' file is absent, container wasn't started correctly
```
See this failed build for a full log: https://github.com/uklimaschewski/EvalEx/issues/150

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by uklimaschewski** [comment]
Build is running now, looks like it was a temporary problem with contacting the keyserver

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1242` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1242` was not in scope
