### ISSUE TITLE
Rultor merged but PR is left open

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1243]
After rultor successfully merged PR #1239, the PR itself remained open.
Tipically I see the PRs automatically close after a rultor merge.

We should to figure out:
- If this was an issue on rultor side that we need to fix;
- Or an issue with github's api that could be reported on their side;

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire dup of https://github.com/yegor256/rultor/issues/1171 ?

**Comment by filfreire** [comment]
@yegor256, yup, spot on. Closing this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1243` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#1243](https://github.com/yegor256/rultor/issues/1243) was not in scope
