### ISSUE TITLE
Make next attempt when remote was changed

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/rultor#1245]
Rultor can not merge changes, this is because repository was updated at the same time when rultor was trying to merge. This was a few times in cactoos https://github.com/yegor256/cactoos/search?q=Updates+were+rejected+because+the+remote+contains+work+that+you+do&type=Issues&utf8=✓

Last log from rultor:
```log
Reading .gitattributes...
+ mv /home/r/repo .
++ whoami
+ chown -R root repo
+ '[' -n '' ']'
++ whoami
+ sudo chown -R rultor repo
+ cd repo
+ git push origin master
To git@github.com:yegor256/cactoos.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:yegor256/cactoos.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

May be in this case rultor can make next attempt to merge?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey you mean, run the full cycle again? That would be super slow and besides, how can we understand why script failed?

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1245` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#1245](https://github.com/yegor256/rultor/issues/1245) was not in scope

**Comment by nikialeksey** [comment]
Yes, I mean. Run the full cycle only if this error happens. In case of this error rultor can show message in pull request about this event: "There was some changes when I was merging pull request. Trying again...". 

Ok,  If this super slow, can we change error message from rultor of this error to something friendly without log?
