### ISSUE TITLE
gpg: signing failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by jonashackt** [yegor256/rultor#1249]
Hi, we keep running into this problem (see http://www.rultor.com/t/13123-369173456):

```
gpg: WARNING: unsafe permissions on homedir '/home/r'
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/home/r/secring.gpg' to gpg-agent
gpg: key 08ECA5BDD38EF5E0: secret key imported
gpg: migration succeeded
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
```
Before that issue, we used rultor many times to release our OpenSource project. 

Maybe this is a problem with the `maven-gpg-plugin`, where a similar issue is described here: https://issues.apache.org/jira/browse/MGPG-59

Any suggestions on this?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by jonashackt** [comment]
Ah, I think I found it. According to https://stackoverflow.com/questions/28859942/how-do-i-get-the-maven-gpg-plugin-to-use-a-passphrase-from-environment-variable. You have to add the following to your `maven-gpg-plugin` configuration: 

```
							<configuration>
							  <!-- This is necessary for gpg to not try to use the pinentry programs -->
							  <gpgArguments>
								  <arg>--pinentry-mode</arg>
								  <arg>loopback</arg>
							  </gpgArguments>
							</configuration>
```

See http://www.rultor.com/t/13123-369189407

**Comment by yegor256** [comment]
@jonashackt thanks for the hint. I believe, it's not a problem inside Rultor, but in the Java project you are releasing. This GPG configuration should be added to its `pom.xml`, right? I think we can add it to [jcabi-parent](https://github.com/jcabi/jcabi-parent), which many people are using as an example (or as a parent pom). Right?

**Comment by jonashackt** [comment]
Yeah, you´re right - it´s my own project´s `pom.xml`, where I had to add that configuration. Would be a good idea, if this can be added to the parent 👍

**Comment by yegor256** [comment]
@jonashackt could you please submit this ticket to https://github.com/jcabi/jcabi-parent ? I will fix it there. This one should be closed.

**Comment by jonashackt** [comment]
Oh, the problem only seems to be related to a different Docker base image I used inside my `.rultor.yml`. The problem occured only in [cxf-spring-boot-starter](https://github.com/codecentric/cxf-spring-boot-starter/issues/28), where I used `maven:3-jdk-8` - the same fix wasn´t necessary in [cxf-spring-boot-starter-maven-plugin](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin), where I used `yegor256/java8`. Therefor I don´t know, if it´s a good idea to put this into the parent anymore...
