### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1250]
Docker failed to start few times: https://github.com/zerocracy/farm/pull/693#issuecomment-369962292 https://github.com/zerocracy/farm/pull/685#issuecomment-369991899 with error:
>Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
'cid' file is absent, container wasn't started correctly

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it was a temporary issue, fixed already
