### ISSUE TITLE
Unable to specify next version on release

### ISSUE THREAD

**Issue by llorllale** [yegor256/rultor#1258]
I am currently manually updating SNAPSHOT version after doing `@rultor release, tag is XXX`. It would be nice to be able to do `@rultor release, tag is XXX, next version is YYY` and have rultor automatically set the new version to YYY after releasing.

To be clear, the intention is for `YYY` to be some SNAPSHOT version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale you can do all that inside your script. "version is `YYY`" will set `${version}` bash variable inside your script. What you will do with it later, is up to you.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
