### ISSUE TITLE
Rultor "commanders" section is not working

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1263]
I'm specified in `commanders` section in [.rultor.yml](https://github.com/zerocracy/farm/blob/master/.rultor.yml#L41) in `release` command, but Rultor doesn't listen me: https://github.com/zerocracy/farm/pull/1065#issuecomment-394090991 when I ask to release.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 still an issue?

**Comment by g4s8** [comment]
@yegor256 it's not an issue for me now, but I think this bug still exist.

**Comment by yegor256** [comment]
@g4s8 I think it's fixed already. if not, submit a new one

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1263` is not assigned, can't get performer
