### ISSUE TITLE
Rultor fails with odd error message

### ISSUE THREAD

**Issue by emilianodellacasa** [yegor256/rultor#1266]
After trying to merge a PR https://github.com/zold-io/zold/pull/336, Rultor fails with following error message:

"Your Ruby version is 2.3.3, but your Gemfile specified >= 2.3.3"

just after a _bundle install_ command

I don't understand whether this is a Rultor bug, on my machine the same command works fine and the error message is quite odd.

This is the full log http://www.rultor.com/t/15277-403503974

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@emilianodellacasa definitely not a problem with Rultor. You can try to run the build in Docker container that is used by Rultor and the problem will be reproduced.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1266` is not assigned, can't get performer
