### ISSUE TITLE
Rultor fails merging when Gemfile has an operator

### ISSUE THREAD

**Issue by emilianodellacasa** [yegor256/rultor#1267]
In the pull request https://github.com/zold-io/zold/pull/336 an operator is used inside Gemfile to specify that ruby versions >= 2.3.3 are accepted. 

I have tried both the ">=" and the "~>" operators, both should be accepted like shown in this article: https://www.devalot.com/articles/2012/04/gem-versions.html

However, as it can be seen in the PR, both are not accepted by rultor that fails with following message:

Your Ruby version is 2.3.3, but your Gemfile specified ~> 2.3

It is worth noticing that, on the countrary, Travis correctly understands those operators:

https://travis-ci.org/zold-io/zold/builds/402210387

If in the Gemfile i set

ruby '2.3.3'

so that, only this version is accepted, Travis fails for all other versions (as expected):

https://travis-ci.org/zold-io/zold/builds/402702506

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
@yegor256 Unfortunately, my knowledge on Docker is quite limited, but what I see here is that Travis can understand operators in Gemfile and Rultor (on Docker) cannot.

This is what I would do:
1) check bundler version on Docker and updating if necessary;
2) try another version of ruby on Docker;

**Comment by yegor256** [comment]
@emilianodellacasa you are right, but all of that is outside of Rultor scope. Rultor just starts a Docker container we tell it to start. What happens inside the container -- Rultor can't affect.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1267` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
