### ISSUE TITLE
Variables in rultor script

### ISSUE THREAD

**Issue by driver733** [yegor256/rultor#1268]
I am unable to use variable that are resolved (using inner statements) in rultor script. It is hard to write commands without variables at all.

[Log](https://github.com/driver733/VKUploader/pull/290#issuecomment-406810162)

.rultor.yml
```
# PROPERTY_FILE="/home/r/credentials.properties"
USER=`cat $PROPS | grep "vk.user"  | cut -d'=' -f2`
GROUP=`cat $PROPS | grep "vk.group" | cut -d'=' -f2`
TOKEN=`cat $PROPS | grep "vk.token" | cut -d'=' -f2`
echo $USER
echo $GROUP
echo $TOKEN
```
Error log.
```
+ PROPS=/home/r/credentials.properties
++ cat /home/r/credentials.properties
++ grep vk.user
++ cut -d= -f2
+ USER=
+ 438005213
/home/r/script.sh: line 9: 438005213: command not found
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@driver733 this is weird. Try this:

```
USER=$(cat $PROPS | grep "vk.user"  | cut -d'=' -f2)
```

**Comment by yegor256** [comment]
@driver733 I think it's not a bug. If it is, please reopen.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1268` is not assigned, can't get performer
