### ISSUE TITLE
merge conflict - false positive

### ISSUE THREAD

**Issue by driver733** [yegor256/rultor#1269]
rultor raises a merge conflict, although there are none (github allows to auto merge using web interface)

[Log](https://github.com/driver733/VKUploader/pull/292#issuecomment-406812310)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@driver733 it's not a Rultor bug. Just try to reproduce the same steps on your local machine and you will get the same merge conflict.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1269` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
