### ISSUE TITLE
Rultor is not working

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1279]
Rultor unable to start new docker on merge with error:
```
docker: Error response from daemon: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused".
```

Started to reproduce: 14 Nov 2018

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1279` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
