### ISSUE TITLE
Rultor does not accept my invitation for collaborate

### ISSUE THREAD

**Issue by eivinhb** [yegor256/rultor#1281]
The github-repo is bekkopen/NoCommons 

The release has worked but rultor failed while tagging the release.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@eivinhb[/z](https://www.0crat.com/u/eivinhb) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@eivinhb this may take a few minutes. Still not accepted?

**Comment by eivinhb** [comment]
Still not accepted.

**Comment by eivinhb** [comment]
This is working now and we made a release! 🎉

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1281` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
