### ISSUE TITLE
Maven Test Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

### ISSUE THREAD

**Issue by jonashackt** [yegor256/rultor#1283]
I'am using rultor to release my Open Source project https://github.com/codecentric/cxf-spring-boot-starter to Maven Central, which workes great most of the time. Only today I'am facing this error in rultor, popping up after a successful Maven compile phase ([full log here](http://www.rultor.com/t/16953-448572525)):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter
```

The tests won´t start up and [so seams to already have described the reason](https://stackoverflow.com/a/53016532/4964553): According to the answer (on Oct. 26 2018) this is an openJDK bug, which is fixed in `8u191-b12`.

The issue is more for documentation purposes since I guess rultor cannot do so much about it. Rultor uses (according to the log) the Docker image [maven:3-jdk-8](https://github.com/carlossg/docker-maven/blob/05f4802aa5c253dcf75fe967c6f45b3fb1e2f26e/jdk-8/Dockerfile) which it self is derived via `FROM openjdk:8-jdk` from [openjdk:8-jdk](https://github.com/docker-library/openjdk/blob/7a33416016b60c045cf0ba99e82617ed6c130595/8/jdk/Dockerfile), which has been build at Oct. 26 2018. My guess is, to either just wait for openJDK to bring a new Docker image to DockerHub which is based on `8u191-b12` or higher - or to change the used Docker image in Rultor (which I wouldn't really preferr, since I also use this image quite a lot in my own projects).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@jonashackt[/z](https://www.0crat.com/u/jonashackt) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@jonashackt you can submit a pull request with the changes to our [Dockerfile](https://github.com/yegor256/rultor/blob/master/src/docker/Dockerfile)

**Comment by pnatashap** [comment]
@yegor256 looks like this issue is not actual any more as JDK 11 and 17 are installed in docker 
https://github.com/yegor256/rultor-image/blob/master/Dockerfile#L155

**Comment by yegor256** [comment]
@jonashackt indeed, we have JDK inside our Docker image now
