### ISSUE TITLE
Rultor fails on fetching gpg keys

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1284]
Sometimes rultor is in a bad mood and fails due to pgp key retrieval failure, as seen on:
https://github.com/yegor256/takes/pull/903#issuecomment-448830201
https://github.com/yegor256/takes/pull/903#issuecomment-448830980
https://github.com/yegor256/takes/pull/883#issuecomment-446524796
https://github.com/yegor256/takes/pull/700#issuecomment-236999272

Maybe rultor should retry a few times when it could not retrieve the keys?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso that's a temporary problem, we can't do anything about it

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1284` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
