### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1289]
Travis build is failing, I'm getting the following log: https://api.travis-ci.org/v3/job/481625846/log.txt
The message is:
`{"message":"API rate limit exceeded for 35.188.1.99. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@paulodamaso fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1289` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
