### ISSUE TITLE
Parameters in deploy commands

### ISSUE THREAD

**Issue by emilianodellacasa** [yegor256/rultor#1295]
It would be very useful to pass some parameters to deploy, just the way it is done for release $tag.

It would be better to find a way that pass an arbitrary number of params, to make it more flexible.

For example: if I want to deploy to a staging environment, I would like to say:

@ rultor deploy, env=staging

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by pnatashap** [comment]
@yegor256 @emilianodellacasa this feature is already implemented, described at least in https://doc.rultor.com/basics.html in release part there is a description how to use tag. It can be used for for other variables

**Comment by yegor256** [comment]
@emilianodellacasa indeed, it works now
