### ISSUE TITLE
Rultor failing to initialize the container

### ISSUE THREAD

**Issue by ammaratef45** [yegor256/rultor#1297]
Out of the sudden rultor started to give me that log every time I try to deploy
It was working fine and I did change only a command of the deploy script

> > @rultor deploy
> 
> @ammaratef45 Oops, I failed. You can see the full log [here](http://www.rultor.com/t/18005-466789664) (spent 2min)
> 
> ```
> + set -e
> + set -o pipefail
> ++ dirname ./run.sh
> + cd .
> + echo 29743
> + echo '1.68.2 70c246ce3'
> 1.68.2 70c246ce3
> + date
> Sun Feb 24 17:05:02 CET 2019
> + uptime
>  17:05:02 up 71 days,  7:35,  0 users,  load average: 5.27, 5.10, 5.50
> + head=git@github.com:ammaratef45/zold-flutter-client.git
> + ff=default
> + image=adamantium/flutter
> + rebase=false
> + squash=false
> + head_branch=master
> + author=ammaratef45
> + vars=('--env=head=git@github.com:ammaratef45/zold-flutter-client.git' '--env=scripts=( '\''export '\''\'\'''\''head=git@github.com:ammaratef45/zold-flutter-client.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=ammaratef45'\''\'\'''\'''\'' '\'';'\'' '\''curl -sSL https://get.rvm.io | bash -s stable --ruby'\'' '\'';'\'' '\''source /usr/local/rvm/scripts/rvm'\'' '\'';'\'' '\''gem install pdd'\'' '\'';'\'' '\''gem install fastlane'\'' '\'';'\'' '\''flutter doctor'\'' '\'';'\'' '\''cd zold_wallet'\'' '\'';'\'' '\''flutter -v build apk'\'' '\'';'\'' '\''cd android'\'' '\'';'\'' '\''fastlane supply init'\'' '\'';'\'' '\''fastlane beta'\'' '\'';'\'' )' '--env=head_branch=master' '--env=author=ammaratef45')
> + scripts=('export '\''head=git@github.com:ammaratef45/zold-flutter-client.git'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''author=ammaratef45'\''' ';' 'curl -sSL https://get.rvm.io | bash -s stable --ruby' ';' 'source /usr/local/rvm/scripts/rvm' ';' 'gem install pdd' ';' 'gem install fastlane' ';' 'flutter doctor' ';' 'cd zold_wallet' ';' 'flutter -v build apk' ';' 'cd android' ';' 'fastlane supply init' ';' 'fastlane beta' ';')
> + directory=
> + container=ammaratef45_zold-flutter-client_8
> + as_root=true
> + mkdir -p /home/rultor/.ssh
> + echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
> + chmod 600 /home/rultor/.ssh/config
> + git clone git@github.com:ammaratef45/zold-flutter-client.git repo
> Cloning into 'repo'...
> + cd repo
> + git config user.email me@rultor.com
> + git config user.name rultor
> + '[' -z 'export '\''head=git@github.com:ammaratef45/zold-flutter-client.git'\''' ']'
> + cd ..
> + cat
> + '[' true = true ']'
> + cat
> + chmod a+x entry.sh
> + cat
> + echo 'export '\''head=git@github.com:ammaratef45/zold-flutter-client.git'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''author=ammaratef45'\''' ';' 'curl -sSL https://get.rvm.io | bash -s stable --ruby' ';' 'source /usr/local/rvm/scripts/rvm' ';' 'gem install pdd' ';' 'gem install fastlane' ';' 'flutter doctor' ';' 'cd zold_wallet' ';' 'flutter -v build apk' ';' 'cd android' ';' 'fastlane supply init' ';' 'fastlane beta' ';'
> + gpgconf --reload gpg-agent
> + gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
> gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
> gpgkeys: key 9AF0FA4C can't be retrieved
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> gpg: keyserver communications error: keyserver helper general error
> gpg: keyserver communications error: unknown pubkey algorithm
> gpg: keyserver receive failed: unknown pubkey algorithm
> 'cid' file is absent, container wasn't started correctly
> ```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@yegor256 It's working again (without changing anything)

**Comment by pnatashap** [comment]
@yegor256  @ammaratef45 according to the last message issue can be closed
