### ISSUE TITLE
rultor docker image is too fat

### ISSUE THREAD

**Issue by wholegroup** [yegor256/rultor#1298]
Current rultor docker image (1.68.2) is too fat. 
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
yegor256/rultor         latest              233d6d168c87        4 weeks ago         3.16GB
```

e.g. you can remove ```/usr/share/doc/texlive-doc``` (https://askubuntu.com/questions/129566/remove-documentation-to-save-hard-drive-space)
```
root@537006717f33:/tmp# du -h -d 1 /usr/share/doc | sort -hr
860M	/usr/share/doc
822M	/usr/share/doc/texlive-doc
```

and some other unnecessary files (.m2, installers)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@wholegroup you are right. Would you be interested in submitting a pull request to fix this?

**Comment by wholegroup** [comment]
@yegor256 I wouldn't. Just want to get my bonus according to https://www.yegor256.com/2014/04/17/how-xdsd-is-different.html#we-pay-for-bugs

**Comment by yegor256** [comment]
@wholegroup you got it)

**Comment by 0crat** [comment]
Job [#1298](https://github.com/yegor256/rultor/issues/1298) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @wholegroup[/z](https://www.0crat.com/u/wholegroup)

**Comment by yegor256** [comment]
@wholegroup now we use `yegor256/rultor-image`, you are free to modify it or use another image
