### ISSUE TITLE
Rultor is not deploying

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1299]
I cant' deploy wioth rultor, it can't fetch github rsa fingerprint

Here's the message:
`
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
`

|'m trying to execute a script to automate a branch copy, from `master` into `staging` into my branch (`origin`)

I can normally use `merge` and `release` commands, including in the original branch (`upstream`), e.g, I can use `@rultor merge` and rultor successfully merges `origin/master` onto `upstream/master`, just `deploy` script doesn't work

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1299` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
