### ISSUE TITLE
Steps to upload the single Jar file to the Maven Central Repository

### ISSUE THREAD

**Issue by rshankarkony** [yegor256/rultor#1300]
Hi Team,

we are looking for the steps to upload jar file to the maven central repository. so that we will download it at build time using pom.xml.

I tried to upload from the below url
https://oss.sonatype.org
upload mode: Artifact with GAV

let me know if this correct way of doing.

Thanks,
Naresh.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@rshankarkony[/z](https://www.0crat.com/u/rshankarkony) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by pnatashap** [comment]
@rshankarkony release is described in documentation https://doc.rultor.com/commands.html and in this article http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html
If you faced with some specific error in using rultor, please open an issue with specific problem

**Comment by pnatashap** [comment]
@yegor256 issue is not connected to specific problem and looks like can be closed
