### ISSUE TITLE
The link to CONTRIBUTING.md in README.MD is broken

### ISSUE THREAD

**Issue by aivinog1** [yegor256/rultor#1301]
The link to CONTRIBUTING.md in section https://github.com/yegor256/rultor#how-to-contribute is broken.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 thanks, fixed in 711c5daab

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1301` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
