### ISSUE TITLE
Rultor can release only from master branch

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1302]
It's not possible to specify the branch for release, I'm expecting to be able to release from any branch (e.g. from rc-branch), but `master` branch name is hard-coded in `QnRelease`: https://github.com/yegor256/rultor/blob/1a79ef08ae8fbc31aabfe7b9f54a65ba13cbd827/src/main/java/com/rultor/agents/github/qtn/QnRelease.java#L124
moreover this value (`head_branch`) is never used in release script: https://github.com/yegor256/rultor/blob/c8dd8ed962a0acf934c026370b3140e2611afa4e/src/main/resources/com/rultor/agents/req/release.sh
same for `deploy`.

I think it may look like:
```
@rultor release from=`rc-1.0`, tag=`1.0`
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1302](https://github.com/yegor256/rultor/issues/1302) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
