### ISSUE TITLE
Rultor merge is showing errors

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1305]
I'm receiveing this error upon `merge` command:

Strangely looks like rultor contionues to do its job and merges the PRs

> ~~ Copyright (c) 2009-2019, rultor.com ~~ All rights reserved. ~~ ~~ Redistribution and use in source and binary forms, with or without ~~ modification, are permitted provided that the following conditions ~~ are met: 1) Redistributions of source code must retain the above ~~ copyright notice, this list of conditions and the following ~~ disclaimer. 2) Redistributions in binary form must reproduce the above ~~ copyright notice, this list of conditions and the following ~~ disclaimer in the documentation and/or other materials provided ~~ with the distribution. 3) Neither the name of the Qulice.com nor ~~ the names of its contributors may be used to endorse or promote ~~ products derived from this software without specific prior written ~~ permission. ~~ ~~ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ~~ "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT ~~ NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND ~~ FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ~~ THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, ~~ INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ~~ (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR ~~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ~~ HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, ~~ STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ~~ ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED ~~ OF THE POSSIBILITY OF SUCH DAMAGE.
> R
> 94cea69d9
> Internal Application Error
> Something went terribly wrong. The system can't serve your request at the moment. We've been already notified about this situation and will start working on it really soon. In the meantime, please get back to the site and try to do the same operation again. Maybe it will work, you know :)
> 
> The text below is a detailed description of your HTTP request and a stacktrace of the runtime exception thrown by JVM. If you want to help us, please post this text as a new issue to Github.
> 
> java.lang.IllegalStateException: [GET http://www.rultor.com/t/18898-492419107] failed in 586ms: #urn()
> 	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
> 	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
> 	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
> 	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
> 	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.http.BkBasic.print(BkBasic.java:108)
> 	at org.takes.http.BkBasic.accept(BkBasic.java:84)
> 	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
> 	at org.takes.http.BkWrap.accept(BkWrap.java:52)
> 	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
> 	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.UnsupportedOperationException: #urn()
> 	at org.takes.facets.auth.Identity$1.urn(Identity.java:50)
> 	at com.rultor.web.RqUser.toString(RqUser.java:66)
> 	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
> 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
> 	at java.util.Formatter.format(Formatter.java:2520)
> 	at java.util.Formatter.format(Formatter.java:2455)
> 	at java.lang.String.format(String.java:2940)
> 	at com.rultor.web.TkDaemon.act(TkDaemon.java:95)
> 	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
> 	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
> 	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
> 	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
> 	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
> 	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
> 	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
> 	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
> 	at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
> 	... 23 more

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso where it's happening? Do you have a link?

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.4`

**Comment by yegor256** [comment]
@paulodamaso I think it's fixed. Try again.
