### ISSUE TITLE
Let's create and publish json schema for .rultor.yml

### ISSUE THREAD

**Issue by aivinog1** [yegor256/rultor#1307]
It will be very convenient to me checking my `.rultor.yml ` via some schema, for example in my IDE. Intellij IDEA, for example, has the ability of autocompletion if the schema is present, for example.

Or I can even create a test in my project, that verifies that `.rultor.yml` is valid.

I think that this page: https://doc.rultor.com/reference.html should have a link to such schema.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
