### ISSUE TITLE
Do merge and run checks as soon as the PR appears (improvement)

### ISSUE THREAD

**Issue by agorlov** [yegor256/rultor#1311]
@yegor256 
How do you feel about the improvement of the rultor, so that it does checks as soon as the PR appears, before the code review?

So as not to waste architects time on what the machine will reveal on its own.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@agorlov[/z](https://www.0crat.com/u/agorlov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@agorlov this is what CI is for, like Travis. No need to repeat the same functionality in Rultor.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1311` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
