### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by Glusk2** [yegor256/rultor#1313]
The travis build is failing (branch `master`, commit 5db4123):
https://travis-ci.org/yegor256/rultor/jobs/598137826

Error message:
``` code
Expected feature release number in range of 9 to 14, but got: 8
```

This is a common problem among the Java 8 projects (https://github.com/yegor256/cactoos/issues/1172).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1313` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
