### ISSUE TITLE
deploy to Dokku

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1315]

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.6`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.6`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.6`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.6`

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1315` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
