### ISSUE TITLE
Enable TLSv1.2 on Java 7 builds

### ISSUE THREAD

**Issue by Glusk2** [yegor256/rultor#1317]
Appveyor and Shippable builds fail.

For example [28311685](https://ci.appveyor.com/project/yegor256/rultor/builds/28311685):

``` ps
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.rultor:rultor:2.0-SNAPSHOT (C:\projects\rultor\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact com.jcabi:parent:pom:0.37.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 35, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Command exited with code 1
```

According to this [SO answer](https://stackoverflow.com/a/50956622) and this [sonatype blog post](https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/) there are two solutions:
``` bash
mvn -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 <goals>
```
or
``` bash
export MAVEN_OPTS=-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1317` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
