### ISSUE TITLE
Can't login to www.rultor.com

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/rultor#1319]
1) Go to https://www.rultor.com/
2) Click "login" at the top of the page.

What happens:
I get redirected to OAuth2 error URL:
`https://www.rultor.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vzurauskas fixed
