### ISSUE TITLE
Main page of rultor.com show private repos

### ISSUE THREAD

**Issue by theruziev** [yegor256/rultor#1320]
Main page of rultor.com show private repositories name in recent conversation. Is it ok? 

![image](https://user-images.githubusercontent.com/32102033/70239997-733dc400-177d-11ea-8bba-72551baeaf55.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@theruziev[/z](https://www.0crat.com/u/theruziev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.8`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.9`

**Comment by theruziev** [comment]
doesn't show private repos thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1320` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@theruziev thanks!
