### ISSUE TITLE
move Docker image to another repo

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1322]

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.7`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.7`

**Comment by Glusk2** [comment]
@yegor256 Shouldn't the `README.md` be updated as well? Currently it's still:

>Default Docker image is [yegor256/rultor](https://hub.docker.com/r/yegor256/rultor/)

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1322` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
