### ISSUE TITLE
Rultor doesn't download assets from the linked repository

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/rultor#1323]
I've configured Rultor in [my project](https://github.com/proshin-roman/finapi-java-client/blob/master/.rultor.yml) to use assets from a private repository (as it's explained here - https://doc.rultor.com/reference.html#assets).

But then I've tried to make a release, and it seems like Rultor didn't download those assets. At least I could see anything in the log file about the assetts: https://www.rultor.com/t/21089-568294030

Is the "assets" deprecated or broken? Or is something configured incorrectly?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@proshin-roman use the lastes `yegor256/rultor-image` and the problem will disappear
