### ISSUE TITLE
Rultor is failing to merge

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1324]
I'm having problems to merge pull requests using rultor:
- https://github.com/yegor256/cactoos/pull/1272#issuecomment-573692180

Also, when trying to see the logs, rultor shows me this:
![image](https://user-images.githubusercontent.com/33915433/72264289-404ae380-35f9-11ea-936e-b061a1511027.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@paulodamaso same here, right now. However, rultor replied with "Ok, I'll try to merge..."

**Comment by amihaiemil** [comment]
@paulodamaso However, I see that rultor replied to your command entirely. This could mean that only the website is having issues, not the chatbot itself.

**Comment by amihaiemil** [comment]
@paulodamaso I think it's a bigger problem. Rultor can't even download the Maven plugins and dependencies. See [here](https://github.com/jcabi/jcabi-github/issues/1507#issuecomment-575051164).

**Comment by paulodamaso** [comment]
@amihaiemil I agree with you, looks like something bigger. I'm also having problemin merging [this](https://github.com/yegor256/takes/pull/1020#issuecomment-577477184).

**Comment by paulodamaso** [comment]
@yegor256 please take a look at this

**Comment by amihaiemil** [comment]
@paulodamaso your problem is most likely related to [this](https://github.com/yegor256/rultor/issues/1325) Issue. 

I think we can close the ticket here :)

**Comment by paulodamaso** [comment]
@amihaiemil Thanks for the info. Lets wait for https://github.com/yegor256/dockers/issues/11 and if things get right I'll close this one

**Comment by paulodamaso** [comment]
@amihaiemil I still having problems to merge:
- https://github.com/yegor256/cactoos/pull/1289#issuecomment-583699858
- https://github.com/yegor256/takes/pull/1028#issuecomment-582913537

**Comment by yegor256** [comment]
@paulodamaso just make sure you use `yegor256/rultor-image` Docker image and the problem will be resolved.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1324` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
