### ISSUE TITLE
Update Maven in Rultor Image

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1325]
We need to update the ``mvn`` version installed in the ``yegor256/rultor`` Docker image! 

Maven builds are now failing to download the dependencies with the error: ``Return code is: 501 , ReasonPhrase:HTTPS Required`` (see [log](https://www.rultor.com/t/21188-575207768)). 

According to SO, Sonatype started enforcing ``HTTPS`` requests since a few days ago. 
https://stackoverflow.com/questions/59763531/maven-dependencies-are-failing-with-501-error

According to the first response, Maven 3.6.0 fixes the Issue. At the moment, Maven 3.3.9 is being used: https://hub.docker.com/r/yegor256/rultor/dockerfile

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@yegor256 pls have a look, it's urgent :)

**Comment by amihaiemil** [comment]
Waiting for [this](https://github.com/yegor256/dockers/pull/10) to be merged.

**Comment by yegor256** [comment]
@amihaiemil fixed already. use the latest `yegor256/rultor-image` image, it works fine

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1325` is not assigned, can't get performer
