### ISSUE TITLE
How to get the Issue where the command was given?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1327]
Is there a way to get the Issue Number where the command was given, within rultor's running script? Perhaps something similar to how we have the ${tag} variable.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@yegor256 when you have time, pls have a look here :D

**Comment by amihaiemil** [comment]
Nevermind, I just realized we can specify any environment variable in the comments, not just ``tag``.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1327` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
