### ISSUE TITLE
remove --entrypoint

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1329]
It was added in #1309 (I can't understand why). Let's remove it since it conflicts with `ENTRYPOINT` from `Dockerfile` of the image.

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.10`

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1329` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
