### ISSUE TITLE
add R user to RVM group

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1331]
Let's add the user `r` to `rvm` group on login

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.11`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
It doesn't help

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1331` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `1.68.12`
