### ISSUE TITLE
Rultor failed cause no changes comparing to previous release

### ISSUE THREAD

**Issue by RoRoche** [yegor256/rultor#1336]
I made no changes comparing to previous release/master. It seems like a bug in Rultor though.

- https://github.com/RoRoche/elegant-android/issues/3
- https://www.rultor.com/t/21951-622787881

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@RoRoche the bug is in your script: https://github.com/RoRoche/elegant-android/blob/master/.rultor.yml#L9 Replace this line with this:

```
git commit -am --allow-empty ${tag}
```

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1336` is not assigned, can't get performer

**Comment by RoRoche** [comment]
Still failing, please see https://github.com/yegor256/rultor/issues/1337
