### ISSUE TITLE
Rultor failed: fatal: Paths with -a does not make sense

### ISSUE THREAD

**Issue by RoRoche** [yegor256/rultor#1337]
Rultor failed with the following message:

```
+ git commit -am --allow-empty 0.0.3
fatal: Paths with -a does not make sense.
```

Here is the issue:
- https://github.com/RoRoche/elegant-android/issues/3

Here are the logs:
- https://www.rultor.com/t/21951-622869333

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@RoRoche try this:

```
git commit --allow-empty -am `0.0.3`
```

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1337` is not assigned, can't get performer
