### ISSUE TITLE
Docker image for Android with Build Tools revision 29.0.2

### ISSUE THREAD

**Issue by RoRoche** [yegor256/rultor#1339]
I reach the following error:

```shell
* What went wrong:0K
Could not determine the dependencies of task ':eoandroidconcurrency:compileBuildTypesJavaWithJavac'.0K
33m> 39mFailed to find Build Tools revision 29.0.2
```

See https://www.rultor.com/t/21951-622998562

I'm using [g4s8/rultor-android](https://hub.docker.com/r/g4s8/rultor-android) but it seems to not be up-to-date.

Does another Android Docker image exist for Rultor?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by pnatashap** [comment]
@yegor256 looks like this issue can be closed, custom docker should be used for Android and there is no supported image for it
