### ISSUE TITLE
Github link to revision leads to 404

### ISSUE THREAD

**Issue by ArtemijRodionov** [yegor256/rultor#1340]
<img width="420" alt="изображение" src="https://user-images.githubusercontent.com/13870342/81318153-77586f80-9096-11ea-91d8-701c69881594.png">
<img width="420" alt="изображение" src="https://user-images.githubusercontent.com/13870342/81318175-80494100-9096-11ea-8db3-c4e16c6c70d2.png">

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by pnatashap** [comment]
@yegor256 for now only version is displayed in the page, do we need any changes for it?

**Comment by yegor256** [comment]
@ArtemijRodionov it's not relevant anymore
