### ISSUE TITLE
Rultor Cannot Connect to GPG Server

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor#1346]
There is a known bug in Rultor, where it sometimes fails to connect to the GPG Server and the merge/deploy/release operation fails because it cannot decrypt the private assets. See an example [here](https://github.com/self-xdsd/self-storage/pull/195#issuecomment-740802544).

I suppose this is the GPG Server's fault, but this behaviour is more and more frequent in the last period (lately, 2 out of 3 merges are failing because of this). 

Maybe you could work with another GPG Server which has better availability?

**Comment by yegor256** [comment]
@amihaiemil do you know how this can be solved?

**Comment by amihaiemil** [comment]
@yegor256 not really, but it couldbe at least mitigated: at the moment rultor decrypts the assets at each operation, but for instance I need private assets only on release.

So we could have an option (decrypt: true|false) for each operation.

**Comment by yegor256** [comment]
@amihaiemil that's a good idea. Can you make a PR? Should be easy, I believe.

**Comment by amihaiemil** [comment]
@yegor256 I'll look into it this week

**Comment by pnatashap** [comment]
@yegor256 issue can be closed as now `gpg --keyserver keyserver.ubuntu.com` is used
