### ISSUE TITLE
new keyserver

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1353]
Let's use the one from openpgp

**Comment by yegor256** [comment]
@rultor release, tag is `1.70.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.70.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1353` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `1.70.5`

**Comment by yegor256** [comment]
@rultor release, tag is `1.70.6`
