### ISSUE TITLE
error: pathspec 'master' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by dgroup** [yegor256/rultor#1356]
By GitHub policies `master` branch is deprecated and now for newly created repositories the mainline branch has the name `main`:
https://www.rultor.com/t/25430-1012352750
```bash
...
+ git clean -fd
+ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
container 554d9c972f0814a8f97953a1d8755241385dcec079b0c9ae254c2c57bf74856d is dead
...
```
Can you please support both branches `master` or `main`...

**Comment by pnatashap** [comment]
This problem is already fixed, defaultBranch is used https://github.com/yegor256/rultor/blob/e8e078aca097cb257a40877fcc894ec3ba1e64f8/src/main/resources/com/rultor/agents/req/release.sh#L41

**Comment by pnatashap** [comment]
@yegor256 I think we can close this ticket, as it is resolved

**Comment by yegor256** [comment]
@dgroup fixed, I'm closing
