### ISSUE TITLE
Use change log contained in `CHANGELOG.md` file

### ISSUE THREAD

**Issue by baudoliver7** [yegor256/rultor#1364]
Like it is done in Github Actions. You format your change log in `CHANGELOG.md` file specifying in title your version. Rultor will be based on the version to find the changelog.
I suggest to use this command to enable this feature:

```shell
rultor release, tag is `0.1.1` with changelog
```

**Comment by yegor256** [comment]
@baudoliver7 we don't need this file anymore

**Comment by yegor256** [comment]
@rultor release, tag is `1.74.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1364` is not assigned, can't get performer
