### ISSUE TITLE
feature request: parse more suitable patterns

### ISSUE THREAD

**Issue by Doldrums** [yegor256/rultor#1464]
ex: 
not only 
@rultor release, tag=`0.1.0`
but also 
@rultor release, tag=0.1.0
@rultor release tag=0.1.0
@rultor release, tag 0.1.0
@rultor release 0.1.0
etc....

make rultor more user-friendly !

**Comment by yegor256** [comment]
@Doldrums you can use any text you like, if "release" is there and the version number is inside back-quotes

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1464` is not assigned, can't get performer
