### ISSUE TITLE
error: release version 17 not supported

### ISSUE THREAD

**Issue by h1alexbel** [yegor256/rultor#1529]
![image](https://user-images.githubusercontent.com/83453843/209661714-497ffa31-9415-49c3-ab59-c2675f4f7f53.png)
![image](https://user-images.githubusercontent.com/83453843/209663928-d6a03dae-6c1f-43d6-bae7-a1be86f70b97.png)

As you can see here, Maven Java version is different from installed Java version
@yegor256

**Comment by yegor256** [comment]
@h1alexbel `rultor-image` Docker image is used by Rultor: https://github.com/yegor256/rultor-image You can configure it any way you want.

**Comment by h1alexbel** [comment]
docker image with java 17 support is [here](https://github.com/eo-cqrs/eo-kafka-rultor-image)
