### ISSUE TITLE
Can I use `GitHub Actions` together with Rultor?

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1565]
I'm developing the open source [project](https://github.com/volodya-lombrozo/test-naming-conventions) in `GitHub`  and I already have some `GitHub Actions` in my project. For example, I'm already have [the action](https://github.com/volodya-lombrozo/test-naming-conventions/blob/main/.github/workflows/maven.release.yml) for deployment to `Maven Central`.
I like the ideas behind Rultor and want to implement it in my project, but I checked the documentation and it seems I have to create a VM with Docker in order to give Rultor the space for running pipelines, but, to be honest, I don't want to do so.
So, here are my questions::

1. Can I use Rultor together with GitHub Actions somehow?
2. Can I reuse already existed pipelines and link them with `release` and `merge` commands?

**Comment by volodya-lombrozo** [comment]
@yegor256

**Comment by yegor256** [comment]
@volodya-lombrozo you don't need to create a VM. Rultor gives you a server out of the box. Just configure `.rultor.yml` and chat with rultor in your tickets.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo you don't need to create a VM. Rultor gives you a server out of the box. Just configure `.rultor.yml` and chat with rultor in your tickets.

@yegor256 what about GitHub Actions?

**Comment by yegor256** [comment]
@volodya-lombrozo rultor doesn't understand GHA config files anyhow

**Comment by volodya-lombrozo** [comment]
@yegor256 What do you think if we add that feature to Rulor? I mean instead of running pipelines in docker, we will delegate it to `GHA`? It could be useful.

**Comment by yegor256** [comment]
@volodya-lombrozo this may be pretty hard to implement, since we use totally different mechanism of setting up the environment. We use Docker, while they use actions that have their own Dockerfile. I think it's better to keep them separately.
