### ISSUE TITLE
Rultor release doesn't work with branch `main`.

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1612]
I can't release a new version using Rultor. Here is my [failed](https://github.com/volodya-lombrozo/test-naming-conventions/pull/54#issuecomment-1440286083) pipeline. Logs (short):
```
++ whoami
+ chown -R root repo
+ '[' -n '' ']'
++ whoami
+ sudo chown -R rultor repo
+ cd repo
+ git checkout __rultor
Already on '__rultor'
+ git tag 0.1.8 -m '0.1.8: tagged by rultor.com'
+ git reset --hard
HEAD is now at 299847f 0.1.8
+ git clean -fd
Removing pom.xml.versionsBackup
+ git checkout master
error: pathspec 'master' did not match any file(s) known to git
container 80957a6e5ede9bec84ba9510d27958b10b0140527f549a671f009e448d008064 is dead
Wed 22 Feb 2023 04:46:30 PM CET
```

**Comment by volodya-lombrozo** [comment]
As I understand when Rultor is trying to release a new version it uses that shell [script](https://github.com/yegor256/rultor/blob/master/src/main/resources/com/rultor/agents/req/release.sh). Please, correct me if I'm wrong. 
And here is hardcoded branch "master":
```sh
git reset --hard
git clean -fd
git checkout master
git branch -D "${BRANCH_NAME}"
git push --all origin
git push --tags origin
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you assign the issue to me, please?

**Comment by yegor256** [comment]
@volodya-lombrozo yes, this is a bug, please help to fix it, if you can
