### ISSUE TITLE
Rultor doesn't merge changes to default branch after release

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1617]
I have the next command in my `merge` section in `.rultor.yml`:
```
mvn versions:set "-DnewVersion=${tag}"
```
When Rultor deploy a new version everything is working fine except updating default branch. For example:

1. In the master branch in `pom.xml` I have the version `0.1.7`
2. I run Rultor with the command `rultor release, tag is 0.1.8`
3. Release happens normally (new library version is deployed successfully)
4. In the master branch I still have `0.1.7` version.

Should I change version by hands? Or Do I have to add merge command to `.rultor.yml`? 
How should I implement that? Maybe some best-practice exists?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by yegor256** [comment]
@volodya-lombrozo conventionally, you should keep version `1.0-SNAPSHOT` or `0.0.0` in `master` branch. When you release, the version is set to `0.1.8`, released, and then pushed to the Git tag (open the tag created in your repository, you will see the updated version there). The version `0.0.0` is _not_ changed in the `master` ever. It's always a "snapshot". Check this out: https://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you, it's more or less clear now. However according to the SO thread `SNAPSHOT` version is a version that in development phase. if I release a new version, `0.1.8` for example, it means that in my `pom.xml` repository I have to put `0.1.9-SNAPSHOT` or `0.2.0-SNAPSHOT` since it is the next possible version which is under under development right now. I don't clearly understand why I should keep `0.0.0` or even `1.0-SNAPSHOT` - it looks misleading (`1.0-SNAPSHOT` it is `0.1.8` or `2.1.3`, or it's just a latest development version).

**Comment by yegor256** [comment]
@volodya-lombrozo usually people don't change SNAPSHOT versions very often. Usually, you keep `1.0-SNAPSHOT` for years, while releasing `0.1.0`, `0.2.0`, `0.55.0` and so on. You only switch to `2.0-SNAPSHOT` when you release `1.0.0`. I've never seen `0.1.9-SNAPSHOT` version :)

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for the comprehensive explanation :) Apparently that issue doesn't make sense then.
