### ISSUE TITLE
Specify release title

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1682]
As far as I know, when Rultor creates a release, the release has a name of the last commit, for example like:
- [here](https://github.com/volodya-lombrozo/jtcop/releases/tag/0.1.9)
- or [here](https://github.com/objectionary/eo/releases/tag/0.29.3)

It's not so beautiful and I have to search for the tag that was attached to that release, I believe it would be better to give more meaningful name to a release, for example:
- "Version 1.6.4"
- Or just "1.6.4" 

Also we can allow to pass the custom release name in rultor command:
```
@rultor please, release, tag is '0.1.2' and title 'Awesome Version 0.1.2'
```

**Comment by volodya-lombrozo** [comment]
@yegor256 What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo I like this one:

```
@rultor release tag is `0.0.0` and title is `hello, world`
```

**Comment by volodya-lombrozo** [comment]
@yegor256 What about the default behaviour? Do you want to leave it as is (== "the last commit message")?

**Comment by yegor256** [comment]
@volodya-lombrozo yes, it would be most logical, since there could be users who expect this behavior
