### ISSUE TITLE
Release with title and version doesn't work together

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1700]
Recently I've tried to release the one projects of mine by using the next command:
```
@rultor release, tag is `0.1.14`, title is `Version 0.1.14`
```
And Rultor answered me the next:
```
@volodya-lombrozo My current version is 1.75.0, Git revision is [3d8a1a748](https://github.com/yegor256/rultor/commit/3d8a1a748)
```
Looks like it understood "version" command instead of "release" command.

Expected behaviour: Rultor releases the new version with title `Version 0.1.14` and tag `0.1.14`.

Here is the conversation: https://github.com/volodya-lombrozo/jtcop/pull/140#issuecomment-1556168716

**Comment by yegor256** [comment]
@volodya-lombrozo indeed, it's not so smart. It just tries to find one of the keywords in your message and then treat it as a command

**Comment by volodya-lombrozo** [comment]
@yegor256 Maybe Rultor has to ignore everything inside single quotes?

**Comment by pnatashap** [comment]
@volodya-lombrozo please try when needed again, should work now

**Comment by volodya-lombrozo** [comment]
@pnatashap Thank you, I'll try it soon.

**Comment by volodya-lombrozo** [comment]
@pnatashap Works like a [charm](https://github.com/objectionary/opeo-maven-plugin/releases/tag/0.1.10). Thank you.
