### ISSUE TITLE
Specify latest release

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1701]
I believe that it would be nice to add an option to specify the latest release for the "release" command. Maybe something like the next:
```
@rultor release latest, tag is `0.1.14`, title is `v0.1.14`
```
or 
```
@rultor release, tag is `0.1.14`, title is `v0.1.14`, is latest
```
By utilizing the `latest` option, you can eliminate the need to manually switch from pre-release to release versions using the user interface. This option is particularly useful when working with software or libraries that have frequent updates and releases. 

Similar to the #1682

**Comment by volodya-lombrozo** [comment]
@yegor256 What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo you know that you can configure this behavior in `.rultor.yml`: e363d4877

**Comment by volodya-lombrozo** [comment]
@yegor256 Ok, looks good. You can assign the issue to me, I will try to implement it.
