### ISSUE TITLE
Rultor don't see messages from code review

### ISSUE THREAD

**Issue by l3r8yJ** [yegor256/rultor#1779]
@yegor256 Just ignores this one

<img width="862" alt="image" src="https://github.com/yegor256/rultor/assets/46355873/79e1f85e-db75-45b4-bb43-9f686f2a711c">

**Comment by yegor256** [comment]
@l3r8yJ this is by design. Only issue messages are taken into account.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1779` is not assigned, can't get performer
