### ISSUE TITLE
let's star every project we touch

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#498]
Let's add a star to every project we work with, just for fun

**Comment by krzyk** [comment]
@yegor256 could you release new version of jcabi-github?  There are two fixes there in master that could be used in rultor. Thanks

**Comment by yegor256** [comment]
@krzyk sure, 0.18.3 will be ready soon, see https://github.com/jcabi/jcabi-github/issues/919

**Comment by krzyk** [comment]
PR  #720

**Comment by krzyk** [comment]
@yegor256 repo starring has been added to master, please close this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.47`

**Comment by yegor256** [comment]
thanks!

**Comment by alex-palevsky** [comment]
once `498-a06fa417` puzzle is resolved, this ticket will be complete

**Comment by alex-palevsky** [comment]
@krzyk Much appreciated! **30 mins** was added to your account, payment ID `50266299`; added +30 to your rating, now it is equal to [+1599](http://www.netbout.com/b/35035?open=rating)

**Comment by alex-palevsky** [comment]
the last puzzle `498-a06fa417`/#734 solved
