### ISSUE TITLE
command line tool

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#549]
Let's create a command line tool, which should simulate the server. I should be able to run it locally:

```
$ rultor deploy
```

It should understand its location, and fetch `.rultor.yml` correctly.

**Comment by yegor256** [comment]
done already

**Comment by alex-palevsky** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by alex-palevsky** [comment]
we will find someone to do this task, soon

**Comment by alex-palevsky** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-75728b3b`

**Comment by pecko** [comment]
I have to build rultor and call this command from OS prompt in the project's (jcabi-github, for instance) directory. (there isn't this command in docker image yegor256/rultor). Right?

Should we add this in rultor's README or doc.rultor.com?

**Comment by yegor256** [comment]
@pecko who are you talking to? Keep in mind that it's important to address your messages, if you want them to be answered :)

**Comment by yegor256** [comment]
@pecko this tool is not yet implemented, it's just a suggestion to create it

**Comment by pecko** [comment]
@yegor256 

I'm sorry, but I'm not learn to address each comment yet :(

It means that currently we can simulate rultor's merge command locally. Right?

If so, could you, please, answer on my question in https://github.com/jcabi/jcabi-github/issues/1172 or tell me where is 'yegor256/home#assets/jcabi/settings.xml' mentioned in https://github.com/jcabi/jcabi-github/blob/master/.rultor.yml?

I just want to run all integration tests in jcabi-github project.

**Comment by yegor256** [comment]
@pecko the tool does NOT exist yet. You can't use it. You can't simulate rultor locally.

**Comment by yegor256** [comment]
@pecko read more about Rultor configuration here: http://doc.rultor.com/reference.html

**Comment by pecko** [comment]
@yegor256 

OK. Thanks. As I understand, we can write rultor commands in some git repository, but can't simulate that.

My real issue/question is related to jcabi-github: https://github.com/jcabi/jcabi-github/issues/1172

**Comment by yegor256** [comment]
@pecko to run rultor locally, you can just do something like this:

```
docker run -i -t --rm yegor256/rultor mvn clean install
```

I assume here that `yegor256/rultor` is Docker image you're using (it's the default one) and `mvn clean install` is basically what you have in `.rultor.yml`

**Comment by alex-palevsky** [comment]
@rfqu this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by rfqu** [comment]
@yegor256 @alex-palevsky I do not understand what to do with this issue. Please give me another task.

**Comment by yegor256** [comment]
@alex-palevsky please assign someone else

**Comment by alex-palevsky** [comment]
> @alex-palevsky please assign someone else

@yegor256 I will assign somebody else to this issue

**Comment by alex-palevsky** [comment]
@xupyprmv this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by xupyprmv** [comment]
@yegor256 I have some questions about Command Line Tools (CLT) mentioned in description of current ticket:

1. Is CLT a separate application or just a script? 
2. OS support. Linux + Windows + MacOS or only some of them?
3. After I installed tool and typed `rultor [command]` I want to use next logic:
1) Check that current folder contains file `.rultor.yml`
2) Set options that mentioned in `env` section of `[command]` description.
3) Execute lines that mentioned in `script` section of `[command]` description.
Is that logic correct?

**Comment by yegor256** [comment]
@xupyprmv I think this ticket is not correct. all this should be implemented here: https://github.com/yegor256/rultor-remote (in Ruby). Sorry. I'm closing.

**Comment by ekondrashev** [comment]
@yegor256 Could you please clarify how exactly to use rultor-remote to simulate the server?

**Comment by yegor256** [comment]
@ekondrashev it's not possible at the moment, but we have to implement it, in rultor-remote
