### ISSUE TITLE
add tags to tweets

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#561]
Let's add language tags to tweets, getting them from here: https://developer.github.com/v3/repos/#list-languages

**Comment by krzyk** [comment]
PR #761

**Comment by krzyk** [comment]
@yegor256 change has been merged to master, please close this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.48`

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `1.48`

**Comment by alex-palevsky** [comment]
@krzyk **30 mins** sent to your balance (ID `50961141`), many thanks!; +30 added to your rating, at the moment it is: [+3312](http://www.netbout.com/b/35035?open=rating)

**Comment by alex-palevsky** [comment]
the last puzzle `561-e08f2fc3`/#698 originated from here solved
