### ISSUE TITLE
show status bar in PNG

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#562]
Let's expose status bar in PNG format (instead of SVG). It will be more compatible with different browsers.

**Comment by yegor256** [comment]
@rultor release, tag is `1.51.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.51.1`

**Comment by yegor256** [comment]
seems to be working

**Comment by alex-palevsky** [comment]
@yegor256 thanks, paid, **30 mins** to your account, payment ID is `000-209d8656`, task took 4588 hours and 27 mins to complete; +30 added to your rating, current score is: [+8453](http://www.netbout.com/b/35008?open=rating)
