### ISSUE TITLE
kwalify for YAML validation

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#570]
let's use kwalify for `.rultor.yml` validation before processing: http://www.kuwata-lab.com/kwalify/ruby/users-guide.html

**Comment by krzyk** [comment]
@yegor256 PR has been merged, please close this issue, thanks

**Comment by yegor256** [comment]
thanks!

**Comment by alex-palevsky** [comment]
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `50000653`... +30 added to your rating, current score is: [+1342](http://www.netbout.com/b/35035?open=rating)

**Comment by alex-palevsky** [comment]
@yegor256 the last puzzle `570-b7bcc1c2`/#699 originated from here solved

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1369](https://github.com/yegor256/rultor/issues/1369) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2411](https://github.com/yegor256/rultor/issues/2411) is still not solved; solved: [#1156](https://github.com/yegor256/rultor/issues/1156), [#2239](https://github.com/yegor256/rultor/issues/2239).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#1156](https://github.com/yegor256/rultor/issues/1156), [#2239](https://github.com/yegor256/rultor/issues/2239), [#2411](https://github.com/yegor256/rultor/issues/2411).
