### ISSUE TITLE
configurable dockerfile

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#594]
Let's make it possible to configure location of a docker file, e.g.:

``` yaml
docker:
  directory: repo/my_docker_config
```

This means that we should start the build like this:

``` bash
$ sudo docker build repo/my_docker_config -t some_temp_name
$ ( sudo docker run -i -t some_temp_name ... )
$ sudo docker rmi some_temp_name
```

We should make sure that the image we build in the first step gets destroyed at the third one.

**Comment by alex-palevsky** [comment]
the last puzzle `633-705a6074`/#648 solved
