### ISSUE TITLE
start/stop EC2 instances for every build

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#629]
Let's try to use EC2 on-demand instances for every build, instead of a fixed host

**Comment by alex-palevsky** [comment]
@nathansgreen just a reminder that you are working with this task for 8 days already

-5 added to your rating, current score is: +50

**Comment by nathansgreen** [comment]
@alex-palevsky please assign to someone else.

**Comment by alex-palevsky** [comment]
> @alex-palevsky please assign to someone else.

@nathansgreen someone else will help in this task, no problem at all

**Comment by alex-palevsky** [comment]
@palyuga it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by palyuga** [comment]
@alex-palevsky assign to someone else, please

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign to someone else, please

@palyuga no problem, I'll try to find somebody else

**Comment by alex-palevsky** [comment]
@alevohin help us, the task is yours

**Comment by alevohin** [comment]
@yegor256 fixed host right now - is it "b1.rultor.com"?
>ec2:
>  key: my-key
What is this key for?

**Comment by yegor256** [comment]
@alevohin it's a typo, ignore it. yes, fixed host now is `b1.rultor.com`

**Comment by alevohin** [comment]
@alex-palevsky PR was merged. Please check and close issue.

**Comment by yegor256** [comment]
@alevohin it's my ticket, I'm the reporter :) thanks, closing

**Comment by alex-palevsky** [comment]
5 puzzles were created here: `629-e67af157`, `629-7845a57e`, `629-1e130e87`, `629-50db40cf`, `629-b8fe2cc2`

**Comment by alex-palevsky** [comment]
@alevohin I just added **30 mins** to your account, many thanks for your contribution..

+30 to your rating, your total score is [+300](http://www.netbout.com/b/35105?open=rating)

**Comment by alex-palevsky** [comment]
@yegor256 last 4 puzzles `629-3b4a7478`/#1091, `629-97e18362`/#1090, `629-efc8aa9c`/#1087, `629-bb1a14ed`/#1089 originated from here were solved

**Comment by 0pdd** [comment]
@yegor256 all 11 puzzles are solved here: [#1165](https://github.com/yegor256/rultor/issues/1165), [#1166](https://github.com/yegor256/rultor/issues/1166), [#1167](https://github.com/yegor256/rultor/issues/1167), [#1168](https://github.com/yegor256/rultor/issues/1168), [#1232](https://github.com/yegor256/rultor/issues/1232), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().
