### ISSUE TITLE
give Docker a storage quota of 20Gb

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#669]

**Comment by original-brownbear** [comment]
@yegor256 can you close this?, to me it looks like this is long obsolete given we're on docker 1.9.x now.

**Comment by original-brownbear** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@original-brownbear but it's not fixed, right? we don't have 20Gb storage quota now.

**Comment by original-brownbear** [comment]
@yegor256 soory I fear I've misinterpreted this.

My understanding was that Docker 1.3.x broke the setting of a non-default `dm.basesize=20G` here. 

This should be resolved in 1.9+ as far as I could research this.
But thinking about it now, likely you long gave up on setting this setting for the daemon right ? ...
Still I think simply setting this option now and restarting the Docker daemon should put the quote in place.
Maybe give it a try ? ( and in the unlikely case it fails, paste the output of `docker info` here ?)

**Comment by yegor256** [comment]
@original-brownbear I didn't understand what do you want me to do

**Comment by original-brownbear** [comment]
@yegor256 sorry, just wanted you to try running the Docker daemon with the `--storage-opt dm.basesize=20G` flag :)

**Comment by yegor256** [comment]
@original-brownbear well, I run it like this:

```
$ sudo service docker start
```

I think it's better to provide all flag/params from rultor, instead of configuring Docker on the server. Since there are other project, which are using Docker. They may not need these settings.

**Comment by original-brownbear** [comment]
@yegor256 bad news then I fear, storage quote can only be set globally for the Docker daemon at this point. Per container settings are being implemented here https://github.com/docker/docker/issues/3804. If we only want this for some containers coming from Rultor we'll have to wait I fear.

**Comment by yegor256** [comment]
@original-brownbear let's wait

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear tag bug added to this issue

**Comment by alex-palevsky** [comment]
@yegor256 attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-59cec294

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear OK, I put "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear I will assign somebody else to this issue

**Comment by yegor256** [comment]
@original-brownbear we won't fix this, since we move to EC2
