### ISSUE TITLE
release log still has NULLs

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#671]
Release log is still not rendered correctly, see this one for example: https://github.com/jcabi/jcabi-immutable/releases/tag/1.4

We tried to solve this problem in #659 but it seems that the problem is still there. I suspect that the bug is actually in jcabi-github.

**Comment by krzyk** [comment]
PR #721

**Comment by krzyk** [comment]
@yegor256 could you check if the problems is solved?

**Comment by yegor256** [comment]
@rultor release, tag is `1.46.5`

**Comment by yegor256** [comment]
@krzyk looks like this change broke something in production... I'll investigate and report in another ticket. thanks for now.

**Comment by yegor256** [comment]
@krzyk this is what got broken: https://github.com/jcabi/jcabi-github/issues/980

**Comment by yegor256** [comment]
@krzyk just released a new version of rultor, still the same `@null` instead of author names :( see https://github.com/yegor256/rultor/releases/tag/1.46.6

**Comment by alex-palevsky** [comment]
@krzyk Much appreciated! **30 mins** was added to your account, payment ID `50264752`. +30 to your rating, your total score is [+1534](http://www.netbout.com/b/35035?open=rating)
