### ISSUE TITLE
track the index of a request in Understands

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#674]
Let's track the index number of every request, inside a repo, in `Understands`. Every time we start a new request, we should get the latest `archive/log` from current `/talk` and retrieve index from it: `/talk/archive/log[last()]/@index`. If it is absent, we should get the last sibling from `Talks` and try to do the same there. If it is absent there, we set the index to `1` and save to `/talk/request/@index`

**Comment by alex-palevsky** [comment]
the last puzzle `674-74d6c10e`/#681 solved
