### ISSUE TITLE
IndexesRequestsTest.java:46-48: Implement behavior tested in storeIndexIfNone,...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#681]
Puzzle `674-74d6c10e` in `src/test/java/com/rultor/agents/github/IndexesRequestsTest.java:46-48` has to be resolved: Implement behavior tested in storeIndexIfNone, retrievesIndexFromLog, retrievesIndexFromSibling and remove Ignore annotation. Add this SuperAgent to com.rultor.agents.Agents.starter method.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@dpisarenko just a reminder that you are working with this task for 8 days already

added -5 to your rating, now it is equal to [+160](http://www.netbout.com/b/35089?open=rating)

**Comment by alex-palevsky** [comment]
@dpisarenko stop where you are, the task is not yours any more, thanks!

**Comment by alex-palevsky** [comment]
@marczeeee it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by Marczeeee** [comment]
@alex-palevsky Pull request #715 is merged and closed. I think the issue can be closed.

**Comment by alex-palevsky** [comment]
@marczeeee check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 10 days. If you can't close it within the next 48 hours I'll have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget that you should remove the `@todo` puzzle from the source code

-30 added to your rating, current score is: -30

**Comment by Marczeeee** [comment]
@alex-palevsky Created a new PR to remove `@todo` annotation from code. With that I think the issue will be completed.

**Comment by Marczeeee** [comment]
@alex-palevsky Pull request #740 was merged. Please close the issue.

**Comment by alex-palevsky** [comment]
Closing this issue now...

**Comment by alex-palevsky** [comment]
@marczeeee paid, thanks, added **30 mins** to your account, payment `50525583`; +30 added to your rating, at the moment it is: +30
