### ISSUE TITLE
Rultor should understand commands inside messages

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#683]
For now rultor can understand commands if message starts from it, for example this works:
```
@rultor merge
@otherguy Thanks
```
But it would be cool if rultor understand following:
```
Good pull request. @rultor please, merge. Thanks to all
```

**Comment by alex-palevsky** [comment]
@jenya the ticket is with you for 8 days already. If it's not finished in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; added -5 to your rating, now it is equal to [-5](http://www.netbout.com/b/35092?open=rating)

**Comment by yegor256** [comment]
@dmarkov please assign someone else

**Comment by alex-palevsky** [comment]
@jenya the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)

-60 added to your rating, current score is: [-165](http://www.netbout.com/b/35092?open=rating)

**Comment by alex-palevsky** [comment]
@alevohin your task now plz proceed when you have time

**Comment by alevohin** [comment]
@longtimeago PR merged to master. Please check and close issue.

**Comment by yegor256** [comment]
hey @rultor, can you hear me?

**Comment by alevohin** [comment]
Wow! Looks that wrong comment used as quote. I'll check it.

**Comment by yegor256** [comment]
@alevohin no no, everything is fine. there is another bug in rultor now, that's why it didn't answer to all (!) messages

**Comment by yegor256** [comment]
FYI, this is the bug https://github.com/yegor256/rultor/issues/730 Should be fixed soon

**Comment by alevohin** [comment]
@yegor256 thanks! So do you think could close this issue?

**Comment by longtimeago** [comment]
@alevohin Let's try. @rultor please, take us to Mars

**Comment by longtimeago** [comment]
@alevohin Cool, thanks!

**Comment by alex-palevsky** [comment]
@alevohin done, I added **30 mins** in payment `50267454`... +30 added to your rating, at the moment it is: [+165](http://www.netbout.com/b/35105?open=rating)
