### ISSUE TITLE
exclude @rultor from the list of authorized commanders

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#690]
`QnAskedBy` shall exclude `@rultor` from the list of `logins`

**Comment by alex-palevsky** [comment]
@nathansgreen you are holding this task for 8 days already... -5 added to your rating, at the moment it is: +45

**Comment by nathansgreen** [comment]
@yegor256 #693 has been merged successfully. Can you close this issue?

**Comment by yegor256** [comment]
@nathansgreen sure, many thanks!

**Comment by alex-palevsky** [comment]
@nathansgreen paid, thanks, added **30 mins** to your account, payment `AP-63113681VF627252T`. +30 added to your rating, at the moment it is: [+100](http://www.netbout.com/b/35107?open=rating)
