### ISSUE TITLE
Doc is missing the list for mandatory phases in rultor.yaml

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#692]
Doc is missing the list for mandatory phases in ```rultor.yaml```.
For example, can ```.rultor.yaml```, contains only
```
deploy:
   script: whoami
```
?

**Comment by alex-palevsky** [comment]
@nathansgreen you're working with this task for 8 days already

added -5 to your rating, now it is equal to +40

**Comment by nathansgreen** [comment]
@alex-palevsky please assign to someone else.

**Comment by alex-palevsky** [comment]
> @alex-palevsky please assign to someone else.

@nathansgreen I will assign somebody else to this issue

**Comment by alex-palevsky** [comment]
@alevohin your task now please proceed when you have time

**Comment by alevohin** [comment]
@longtimeago PR was merged. Please check and close issue.

**Comment by longtimeago** [comment]
@alevohin Sure, thanks!

**Comment by alex-palevsky** [comment]
@alevohin thank you, added **30 mins** to your acc, payment num is `50577981`... +30 to your rating, your total score is [+300](http://www.netbout.com/b/35105?open=rating)
