### ISSUE TITLE
Rultor's pom.xml points to a non-existent license URL

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#695]
The URL http://doc.rultor.com/LICENSE.txt in `pom.xml` points to a non-existent page.

```
<licenses>
    <license>
        <name>BSD</name>
        <url>http://doc.rultor.com/LICENSE.txt</url>
        <distribution>site</distribution>
    </license>
</licenses>
```

Please change the URL to the page with the real license.

**Comment by php-coder** [comment]
@alex-palevsky Please, assign it to someone else.

**Comment by alex-palevsky** [comment]
> @alex-palevsky Please, assign it to someone else.

@php-coder someone else will help in this task, no problem at all

**Comment by alex-palevsky** [comment]
@oruam85 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by oruam85** [comment]
Can you give me the ftp credentials of this domain? we need to make public this page.

**Comment by yegor256** [comment]
@oruam85 no, it's not like this :) the page gets deployed together with the rest of the Maven site. run `mvn clean site` and you will see the site generated in `target/site`. The page should be there in order to be visible in web. You have to add it there

**Comment by oruam85** [comment]
Ok, i take this bug

**Comment by oruam85** [comment]
I made some changes, please review

**Comment by oruam85** [comment]
This bug was resolved. https://github.com/yegor256/rultor/pull/703#issuecomment-68630636

**Comment by yegor256** [comment]
@oruam85 you should ask ticket reporter to close the issue, once it's fixed, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#2.-close-it!

**Comment by alex-palevsky** [comment]
@oruam85 done, I added **30 mins** in payment `49911526`... +30 added to your rating, current score is: +60
