### ISSUE TITLE
GithubProfileValidationTest.java:48-49: Implement validation tests based on...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#698]
Puzzle `561-e08f2fc3` in `src/test/java/com/rultor/profiles/GithubProfileValidationTest.java:48-49` has to be resolved: Implement validation tests based on 2014-07-13-basics.md file.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dpisarenko** [comment]
@alex-palevsky Please assign someone else to this issue.

**Comment by alex-palevsky** [comment]
> @alex-palevsky Please assign someone else to this issue.

@dpisarenko all right, we'll find someone else for this task

**Comment by alex-palevsky** [comment]
@oruam85 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by oruam85** [comment]
@alex-palevsky. I need more info about this class. What do you need validate?

**Comment by yegor256** [comment]
@oruam85 don't ask here, submit new tickets is something is not clear, see http://www.yegor256.com/2014/04/13/bugs-are-welcome.html

**Comment by oruam85** [comment]
@alex-palevsky the PR is already https://github.com/yegor256/rultor/pull/728

**Comment by oruam85** [comment]
@alex-palevsky merged

**Comment by alex-palevsky** [comment]
@oruam85 just a reminder, the task is yours for 10 days already..

do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch

added -30 to your rating, now it is equal to +120

**Comment by oruam85** [comment]
@alex-palevsky why? this bug was merged 16 hours ago. The PR was created 3 days ago.

**Comment by oruam85** [comment]
@alex-palevsky i am waiting for the payment and my +30 points added to my raiting.

**Comment by oruam85** [comment]
@yegor256 here too? the reporter was @alex-palevsky and i tell him that the PR was merged.

**Comment by oruam85** [comment]
@alex-palevsky  And the todo was removed in my PR.

**Comment by yegor256** [comment]
@oruam85 the issue will be closed soon, since your PR removed the todo from the master branch. In the future, try to complete tasks in the beginning of that 10 days timeframe, to avoid notifications

**Comment by oruam85** [comment]
@yegor256 1 day more and @alex-palevsky does not close this bug. But i loose raiting for that... Justice? i can not force him to close :/

**Comment by alex-palevsky** [comment]
Thanks all, I'm closing

**Comment by alex-palevsky** [comment]
@oruam85 done, I added **30 mins** in payment `50331018`

+30 to your rating, your total score is +90
