### ISSUE TITLE
test StartsRequestTest.runsReleaseWithDockerfile failed

### ISSUE THREAD

**Issue by apocarteres** [yegor256/rultor#702]
Environments:
<code>
 JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home" MAVEN_OPTS="-Xms1g -Xmx1g -XX:MaxPermSize=256m" mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 22:22:22+0700)
Maven home: /opt/apache-maven-3.1.1
Java version: 1.7.0_09, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
</code>

Clear repo checkout (head on commit 010def897af0052147785688f27bc138b69a2e6f), try to build with command:
<code>
JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home" MAVEN_OPTS="-Xms1g -Xmx1g -XX:MaxPermSize=256m" mvn clean install -Pqulice
</code>

build process ran into exception:
<pre>
Running com.rultor.agents.github.qtn.QnReferredToTest
[INFO] com.jcabi.github.mock.MkRepos: repository jeff/dxHPzXjDOE created by jeff
[INFO] com.jcabi.github.mock.MkIssues: issue #1 created in jeff/dxHPzXjDOE by jeff: 
[INFO] com.jcabi.github.mock.MkComments: comment #1 posted to issue #1 by jeff:   @xx deploy
[INFO] com.jcabi.github.mock.MkComments: comment #2 posted to issue #1 by jeff: >   @xx deploy\n\n@jeff OK, I'll try to deploy now. You can check the progress [here](#)
[INFO] com.rultor.agents.github.qtn.QnDeploy: deploy request found in jeff/dxHPzXjDOE#1 comment #1
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.676 sec - in com.rultor.agents.github.qtn.QnReferredToTest
Running com.rultor.agents.shells.RegistersShellTest
[INFO] com.rultor.agents.shells.RegistersShell: shell abcd registered as local:221 in test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.072 sec - in com.rultor.agents.shells.RegistersShellTest

Results :

Tests in error: 
  StartsRequestTest.runsReleaseWithDockerfile:284->exec:404 » IllegalArgument No...

Tests run: 84, Failures: 0, Errors: 1, Skipped: 9

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.598s
[INFO] Finished at: Sun Jan 04 00:13:38 OMST 2015
[INFO] Final Memory: 47M/989M
</pre>

**Comment by yegor256** [comment]
@apocarteres can you please post the stacktrace of the failing test?

**Comment by alex-palevsky** [comment]
@adko-pl it is in your hands now, proceed when you can

**Comment by alex-palevsky** [comment]
@apocarteres many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `49911687`

**Comment by adko-pl** [comment]
@alex-palevsky I am unable to reproduce this issue. I have tried the commit @apocarteres has provided, the head commit, Java 1.7, 1.8. On my Mac it always works.

**Comment by yegor256** [comment]
@adko-pl works for me too. but what happened? how the issue was solved?

**Comment by adko-pl** [comment]
@yegor256 as I have written in the previous comment, this test has always worked on my machine. In https://github.com/yegor256/rultor/pull/775 i have removed the @Ignore for this test.

**Comment by yegor256** [comment]
@adko-pl ask ticket reporter to close it than

**Comment by adko-pl** [comment]
@apocarteres can you close this ticket as the issue is not reproducible?

**Comment by apocarteres** [comment]
not reproducing for me now too. thanks.

**Comment by alex-palevsky** [comment]
@adko-pl thank you, added **30 mins** to your acc, payment num is `AP-1V688508YW061625K`... +30 to your rating, your total score is [+60](http://www.netbout.com/b/35150?open=rating)
