### ISSUE TITLE
mvn clean install -Pqulice fail

### ISSUE THREAD

**Issue by oruam85** [yegor256/rultor#704]
BUILD FAILURE with mvn clean install -Pqulice

message:
Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project rultor: Failure: 3 dependency problem(s) found

**Comment by yegor256** [comment]
@oruam85 please post a longer part of the log. this is not enough to understand what's going on

**Comment by oruam85** [comment]
``` 
[INFO] No Checkstyle violations found in 236 files
[INFO] No PMD violations found in 153 files
[INFO] /src/test/webapp/xml/home.xml: skipped
[INFO] /src/main/webapp/WEB-INF/web.xml: skipped
[INFO] /src/site/site.xml: to be validated
[INFO] jcabi-aspects 0.17.1/8b0e260 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)
[INFO] CodeNarc not required since no groovy files in /home/mauricio/git/rultor/src
[INFO] Calling org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1:enforce...
[INFO] Calling org.codehaus.mojo:cobertura-maven-plugin:2.5.1:check...
[INFO] Cannot perform check, instrumentation not performed - skipping.
[INFO] This is not an SVN project
[WARNING] Unused declared dependencies found:
	org.hamcrest:hamcrest-library:jar:1.3:compile
	org.hamcrest:hamcrest-core:jar:1.3:compile
	com.jcabi:jcabi-matchers:jar:1.3:compile
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2015-01-04T11:46:17-04:30
[INFO] Final Memory: 55M/686M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project rultor: Failure: 3 dependency problem(s) found -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

May be we can try change the scope of this dependencies to provided

**Comment by yegor256** [comment]
@oruam85 are you sure you didn't touch any files before running the build? the build is clean in Travis now..

**Comment by oruam85** [comment]
Yes i am sure. i run the command with skip test flag: mvn clean install -Dmaven.test.skip=true -Pqulice

mvn version 3.2.1
qulice version 0.10

BTW the pom.xml not include the version of qulice. Is this a bug?

**Comment by yegor256** [comment]
It's not a bug, qulice version is inherited from our parent POM. 

funny, when I run

```
mvn clean install -Dmaven.test.skip=true -Pqulice
```

I see the problem you see. When I run this

```
mvn clean install -DskipTests -Pqulice
```

I don't see the problem...

**Comment by yegor256** [comment]
@oruam85 thanks for reporting this. In the mean time, use `-DskipTests`. I think we should fix this by explaining this situation in README (unless we find a proper solution).

**Comment by alex-palevsky** [comment]
@peterarsentev you may proceed, it's yours

**Comment by alex-palevsky** [comment]
@oruam85 thanks for this report, I added 15 mins to your account, in transaction `49866668`

**Comment by peterarsentev** [comment]
@alex-palevsky 
I don't such error.
My environments:
mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T21:29:23+04:00)
Maven home: /home/parsentev/Tools/apache-maven-3.2.5
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /home/parsentev/Tools/jdk1.7.0_65/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-43-generic", arch: "amd64", family: "unix"

Shell I reproduce this case with mvn 3.2.1?

**Comment by yegor256** [comment]
@peterarsentev discuss this with the reporter of the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by peterarsentev** [comment]
@oruam85 Please look at my comment above.
I use maven 3.2.5. It works good for such version. if it is ok for you let's close the ticket.

**Comment by oruam85** [comment]
@peterarsentev Can you try to reproduce this case with mvn 3.2.1?

**Comment by peterarsentev** [comment]
@oruam85 I tried to use maven 3.2.1 but it still works correctly.
mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T21:37:52+04:00)
Maven home: /home/parsentev/Tools/apache-maven-3.2.1
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /home/parsentev/Tools/jdk1.7.0_71/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-32-generic", arch: "amd64", family: "unix"

All project was built successfully and the qulice does not show any problems.

It looks like this problems connect to environments configurations.

Please can you show your output from mvn --version?
Thanks.

**Comment by oruam85** [comment]
My output is this:
```
$ mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T13:07:52-04:30)
Maven home: /usr/share/maven3
Java version: 1.7.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-32-generic", arch: "amd64", family: "unix"
```

**Comment by peterarsentev** [comment]
@oruam85 The output looks the same as my.

@yegor256 Please assign someone else because I could not reproduce this behaviour on my PC.

**Comment by yegor256** [comment]
@alex-palevsky assign somebody else here pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign somebody else here pls

@yegor256 no problem, I'll try to find somebody else

**Comment by alex-palevsky** [comment]
@wb14123 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by wb14123** [comment]
I build error because of #707 , I will work on this after #707 is resolved.

**Comment by oruam85** [comment]
@wb14123 the bug https://github.com/yegor256/rultor/issues/707 was resolved. Go ahead with this bug

**Comment by alex-palevsky** [comment]
@wb14123 check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I'll have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; added -30 to your rating, now it is equal to -165

**Comment by yegor256** [comment]
@alex-palevsky assign someone else

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else

@yegor256 all right, we'll find someone else for this task

**Comment by yegor256** [comment]
@oruam85 do you still have this problem or we can close the ticket?

**Comment by oruam85** [comment]
@yegor256 when I run
`mvn clean install -Dmaven.test.skip=true -Pqulice`

I see the problem but if i run 
`mvn clean install -DskipTests -Pqulice`

the build finish without errors

**Comment by yegor256** [comment]
@oruam85 yes, it's a known issue. just use `-DskipTests` and you'll be fine

**Comment by alex-palevsky** [comment]
@oruam85 there is no milestone yet, so I set it to `0.3`

**Comment by alex-palevsky** [comment]
@rfqu this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by rfqu** [comment]
The build fails because of a failing test. Pull request #965 created which excludes this test. Bug #966 created to fix this test. I believe I am done with this issue.

**Comment by rfqu** [comment]
Version tagged 1.59.5 (dated 12/24/2015) builds successfully.
I suggest to close this issue as not reproducible.

**Comment by yegor256** [comment]
@rfqu keep in mind that it's a good practice to address your messages to those who must read them. Just posting messages into tickets/discussions is not personal and in most cases nobody will answer you.

**Comment by rfqu** [comment]
@yegor256 Version tagged 1.59.5 (dated 12/24/2015) builds successfully.
I suggest to close this issue as not reproducible.

**Comment by yegor256** [comment]
@rfqu let's ask @oruam85 to close it, he is the reporter (see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by rfqu** [comment]
@oruam85 Version tagged 1.59.5 (dated 12/24/2015) builds successfully.
I suggest to close this issue as not reproducible.

**Comment by oruam85** [comment]
@rfqu i can not find the tag 1.59.5 of this project.

**Comment by rfqu** [comment]
@oruam85 Strange, I just checked out repository "rultor" and see tag 1.59.5 is present. The last commit is "SHA 61970f30 by alex-palevsky, 01/12/2016 12:11 AM - updated merge/commanders list", and this commit also passed the build command "mvn clean install -Pqulice".

**Comment by yegor256** [comment]
@oruam85 @rfqu here is the list of all recent tags/releases: https://github.com/yegor256/rultor/releases

**Comment by rfqu** [comment]
@oruam85 @yegor256 this is the list of releases, here are tags: https://github.com/yegor256/rultor/tags
tag 1.59.5 is present.

**Comment by original-brownbear** [comment]
@oruam85  is this still an issue for you ? Keep in mind that since the original creation of this ticket the minimum Maven version required has moved up to 3.2.5.

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid now, @oruam85 was asked for feedback more than a month ago, I tried again and the build setup he used when initially reporting this is not supported anymore. 
That and the fact that the dependency versions were changed too meanwhile make reproducing this issue logically impossible anyways.

**Comment by oruam85** [comment]
@original-brownbear is not an issue now. i will close this bug. Thanks

**Comment by original-brownbear** [comment]
@oruam85 thanks :)

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is invalid now, @oruam85 was asked for feedback more than a month ago, I tried again and the build setup he used when initially reporting this is not supported anymore. 
> That and the fact that the dependency versions were changed too meanwhile make reproducing this issue logically impossible anyways.

@original-brownbear got it, "invalid" label here
