### ISSUE TITLE
Update the Copyright year

### ISSUE THREAD

**Issue by oruam85** [yegor256/rultor#705]
In the license.txt file the Copyright year should be 2015

**Comment by alex-palevsky** [comment]
I'll ask someone to take care of this task soon

**Comment by alex-palevsky** [comment]
@maurezen can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by alex-palevsky** [comment]
@oruam85 thank you for the ticket reported, I topped your account for 15 mins, transaction `49746937`

**Comment by maurezen** [comment]
@oruam85 @alex-palevsky there are 100+ other occurences of "2014" in copyright context, should anything be done about that?

**Comment by yegor256** [comment]
@maurezen let's update them all

**Comment by maurezen** [comment]
created a pull request here: #711

**Comment by alex-palevsky** [comment]
@maurezen Thank you, I've added **30 mins** to your account in payment/transaction "`49911555`"... +30 added to your rating, current score is: [+45](http://www.netbout.com/b/35102?open=rating)
