### ISSUE TITLE
Ticket 698 not clear

### ISSUE THREAD

**Issue by oruam85** [yegor256/rultor#714]
@alex-palevsky ` Implement validation tests based on 2014-07-13-basics.md file. `

 I need more information about this class. What do you need validate?

**Comment by oruam85** [comment]
i need this information fot his bug https://github.com/yegor256/rultor/issues/698

**Comment by yegor256** [comment]
@oruam85 the `basics.md` file explains what configuration options are acceptable in the `.rultor.yml` file. According to this information we should create a YAML validator. Make sense?

**Comment by oruam85** [comment]
@yegor256 In other words, test over YAML for the 3 commands (release,deploy and merge) right?

**Comment by yegor256** [comment]
@oruam85 there are other configuration options in the YAML file, not just three commands. They all are explained in `basics.md`

**Comment by oruam85** [comment]
@yegor256 if i have in YAML file the asset jeff/fail#exist.txt. The name of the repo is fail right?

**Comment by yegor256** [comment]
@oruam85 yes

**Comment by oruam85** [comment]
@yegor256 fine, the PR is https://github.com/yegor256/rultor/pull/728#issuecomment-69756901
