### ISSUE TITLE
no reponse from rultor

### ISSUE THREAD

**Issue by sadnanalmanir** [yegor256/rultor#716]
I am getting no response from rultor for the maven central release through sonatype JIRA for my github project PSOARuleML-API

**Comment by sadnanalmanir** [comment]
@yegor256, I am following your instructions at http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html . Regarding "Post a message", could you please elaborate a little more? How can I do that?

**Comment by yegor256** [comment]
by posting a message I mean posting "comments", just like we're doing it here :) I'm sure you got it

**Comment by sadnanalmanir** [comment]
As I am not an expert on github, to make sure I don't post somewhere I am
not supposed to: should I create an issue
https://github.com/yegor256/rultor/issues/new and write the release command
in the title or just reply here with the release command?

**Comment by yegor256** [comment]
@sadnanalmanir you should give commands to rultor inside the tickets you created. I'll help you there now

**Comment by sadnanalmanir** [comment]
@yegor256, thank you very much. I am wondering if you could take a look at
the configulation below to see if there is anything I am missing.

The release failed with error here at http://www.rultor.com/t/1454-69057833
. I have encountered this error before and would like to get your opinion
on my configuration. In my gpg directory is home/username/*.gnupg and
settings.*xml is in home/username/.m2

This is how my profile looks Inside settings.xml:
<profile>
<id>PSOARuleML-API</id> 
<properties>
<gpg.homedir>/home/r</gpg.homedir>
<gpg.keyname>7B02AFDF</gpg.keyname>
<gpg.passphrase>myPassphrase</gpg.passphrase>
</properties>
</profile>

  <servers>
    <server>
      <id>sonatype</id>
      <username></username>
      <password></password>
    </server>
  </servers>

I create the keys:

#rultor encrypt -p sadnanalmanir/PSOARuleML-API .gnupg/secring.gpg

*#rultor encrypt -p sadnanalmanir/PSOARuleML-API .gnupg/pubring.gpg#rultor
encrypt -p sadnanalmanir/PSOARuleML-API .m2/settings.xml*

Then I copy and the *.asc files

*#sudo cp .gnupg/pubring.gpg.asc NetBeansProjects/PSOARuleML-API/#sudo cp
.gnupg/secring.gpg.asc NetBeansProjects/PSOARuleML-API/#sudo cp
.m2/settings.xml.asc NetBeansProjects/PSOARuleML-API/*

I push to github and create .rultor.yml which contains:

decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml

What am doing wrong?

**Comment by yegor256** [comment]
Looks like you're doing everything right.. Something is wrong with the encryption of your files. Rultor can't decrypt them. Are you sure you're using the latest `rultor` gem? Try:

```
gem install rultor
```

**Comment by yegor256** [comment]
It's not an issue of `settings.xml`. The problem is that rultor can't decode your files. I have no idea what's going on... let me try to investigate

**Comment by sadnanalmanir** [comment]
Is there any update regarding the decryption error?

**Comment by yegor256** [comment]
@sadnanalmanir can you please run this:

```
rultor encrypt -p sadnanalmanir/PSOARuleML-API .gnupg/pubring.gpg
```

And post here the full output log.

**Comment by sadnanalmanir** [comment]
@yegor256
here they are
-----------------------------------
+ set -e
+ file=pubring.gpg
+ enc=pubring.gpg.enc
+ [ -e pubring.gpg.enc ]
+ asc=pubring.gpg.asc
+ [ -e pubring.gpg.asc ]
+ cd .gnupg
+ gpg --symmetric --armor --verbose --batch --no-tty --passphrase
rultor-key:sadnanalmanir/PSOARuleML-API -o pubring.gpg.enc pubring.gpg
gpg: using cipher CAST5
gpg: writing to `pubring.gpg.enc'
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys
9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
gpg: armor header: Version: SKS 1.1.5
gpg: armor header: Comment: Hostname: sks.fidocon.de
gpg: pub  2048R/9AF0FA4C 2014-08-17  Rultor.com <gpg@rultor.com>
gpg: key 9AF0FA4C: "Rultor.com <gpg@rultor.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ gpg --trust-model always --output pubring.gpg.asc --batch --no-tty
--armor --encrypt --verbose --recipient 9AF0FA4C pubring.gpg.enc
gpg: using subkey 9A839C3A instead of primary key 9AF0FA4C
gpg: No trust check due to `--trust-model always' option
gpg: reading from `pubring.gpg.enc'
gpg: writing to `pubring.gpg.asc'
gpg: RSA/AES256 encrypted for: "9A839C3A Rultor.com <gpg@rultor.com>"
+ rm -f pubring.gpg.enc
"pubring.gpg encrypted"
---------------------------------------------

**Comment by yegor256** [comment]
@sadnanalmanir what is your operating system and the version of gpg?

**Comment by sadnanalmanir** [comment]
Ubuntu 12.04LTS
gpg (GnuPG) 1.4.11
