### ISSUE TITLE
Qulice configuration

### ISSUE THREAD

**Issue by maurezen** [yegor256/rultor#723]
Qulice - a static analysis tool - is at the moment configured to run at the verify lifecycle phase. Is that really needed? Do we really need to run static analysis *after* the compilation and tests? Couldn't it be done before that?

I suggest moving qulice run to validate phase.

**Comment by yegor256** [comment]
The logic here is that the most important bugs should be detected first. Compilation failures are the most critical bugs. Unit test failures go next. Then, integration tests. Static analysis is the last. There is no point of static analysis if the code can't be compiled.
