### ISSUE TITLE
NULL instead of author names in release log

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#726]
see https://github.com/yegor256/rultor/releases/tag/1.46.6

**Comment by yegor256** [comment]
we tried to solve this in #671

**Comment by alex-palevsky** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by alex-palevsky** [comment]
@wb14123 this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-1f56f551

**Comment by alex-palevsky** [comment]
@wb14123 the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, at the moment it is: -225

**Comment by yegor256** [comment]
@alex-palevsky assign someone else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 got it, someone else will be assigned soon

**Comment by alex-palevsky** [comment]
@krzyk the task is yours, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.1`

**Comment by krzyk** [comment]
PR #770

**Comment by krzyk** [comment]
@yegor256 looks like it was finally fixed :) (https://github.com/yegor256/rultor/releases), please close this issue

**Comment by yegor256** [comment]
@krzyk indeed. many thanks!

**Comment by alex-palevsky** [comment]
@krzyk **30 mins** added to your account (payment number `51586757`), many thanks for your contribution!... +30 to your rating, your total score is [+3949](http://www.netbout.com/b/35035?open=rating)
