### ISSUE TITLE
Implement validation using Kwalify library... #699 

### ISSUE THREAD

**Issue by AlexDag** [yegor256/rultor#731]
For this task I use Kwalify library(I downloaded jar(binary&source) file). There are not the maven referenced resource for Kwalify. I ask for a solution for using Kwalify from rultor - Can I put/create the package "kwalify"(as the source files) inside rultor project?

**Comment by yegor256** [comment]
looks like this kwalify is rather old (latest Ruby version in 2010 and latest Java in 2005). maybe we can find something better/newer?

**Comment by AlexDag** [comment]
ok, it seems as abandoned project(web site,github kvs/kwalify,etc). I'll spend more time for find something newer.

**Comment by AlexDag** [comment]
I could find some newer, for ins.: github  yaml-schema, from 2012. There are not so much.

**Comment by yegor256** [comment]
yep, maybe that one. no matter what we use, we obviously can't add their code to our repository. we should either use a Maven dependency or write someone from scratch
