### ISSUE TITLE
IndexesRequestsTest.retrievesIndexFromSibling fails

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#733]
The test fails consistently, on Mac and on some Linux systems:

```
IndexesRequestsTest.retrievesIndexFromSibling:138
Expected: (an XML document with XPath /talk/request[@index='3'])
     but: an XML document with XPath /talk/request[@index='3'] was <<?xml version="1.0" encoding="UTF-8"?>
<talk later="false" name="third" number="1" public="true">
   <wire>
      <href>#5</href>
   </wire>
   <request id="a67890" index="5">
      <args/>
      <type>merge</type>
   </request>
</talk>>
```

For example, here: https://semaphoreapp.com/yegor256/rultor/branches/master/builds/114

**Comment by alex-palevsky** [comment]
this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@maurezen your task now go ahead when you have time

**Comment by alex-palevsky** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-8b26b787`

**Comment by maurezen** [comment]
@yegor256 I'm a bit at a loss here. The test in question has a puzzle to implement tested functionality; shouldn't these tests just be ignored for the time being?

**Comment by yegor256** [comment]
@maurezen I'm not sure, but currently the test fails. Find a way to fix it.

**Comment by maurezen** [comment]
@alex-palevsky @yegor256 please assign another developer to the task.

**Comment by yegor256** [comment]
@alex-palevsky assign someone else here pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else here pls

@yegor256 OK, I will try to assign someone else

**Comment by alex-palevsky** [comment]
@dpisarenko it is in your hands now, proceed when you can

**Comment by dpisarenko** [comment]
@yegor256 Probable cause of the error: `talks.get(third).read()` returns
```
<?xml version="1.0" encoding="UTF-8"?>
<talk later="false" name="third" number="1" public="true">
   <wire>
      <href>#5</href>
   </wire>
   <request id="a67890" index="5">
      <args/>
      <type>merge</type>
   </request>
</talk>
```
but is expected to return
```
<?xml version="1.0" encoding="UTF-8"?>
<talk later="false" name="third" number="1" public="true">
   <wire>
      <href>#5</href>
   </wire>
   <request id="a67890" index="3">
      <args/>
      <type>merge</type>
   </request>
</talk>
```

**Comment by yegor256** [comment]
@dpisarenko yes, probably that

**Comment by dpisarenko** [comment]
@yegor256 I think I tried to implement the code, which test test verifies and IMHO 5 is the correct value. Because if this value is 3, there would be two nodes in the document with index 3.

**Comment by dpisarenko** [comment]
First entry with `3`:

```
        talks.get(first).modify(
            new Directives().xpath("/talk")
                .add("wire").add("href").set("#3").up().up()
                .add("archive")
                .add("log").attr("id", "3").attr("title", "title3") // id=3
                .attr("index", "1").up()
        );
```

**Comment by dpisarenko** [comment]
@alex-palevsky Please find someone to review PR https://github.com/yegor256/rultor/pull/753 .

**Comment by dpisarenko** [comment]
@alex-palevsky Waiting for #762 .

**Comment by alex-palevsky** [comment]
> @alex-palevsky Waiting for #762 .

@dpisarenko yes, of course, we'll wait for #762

**Comment by alex-palevsky** [comment]
we waited for #762, it is closed already

**Comment by alex-palevsky** [comment]
@yegor256 since there is no milestone yet I set it to "0.3"

**Comment by alex-palevsky** [comment]
@skirpichenok it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by skirpichenok** [comment]
@alex-palevsky I've prepared invironment:

 - Ubuntu 15.10 
 - maven 3.3.9 
 - JDK 1.7.0_80
 - git
 - IDEA 15 (I've imported http://img.teamed.io/settings.jar)

is that enough to continue with bug fixing? Or I am missaed something?

**Comment by skirpichenok** [comment]
But I see the following output for command **mvn clean install -Pqulice**

    Results :

    Tests in error: 
      StartsDaemonITCase.startsDaemon:84 » IO Cannot run program "/usr/sbin/sshd": e...
      ArchivesDaemonITCase.archivesDaemon:70 » IO Cannot run program "/usr/sbin/sshd...
      EndsDaemonITCase.parsesHighlightedStdout:69->start:115 » IO Cannot run program...
      EndsDaemonITCase.readsExitCodeCorrectly:95->start:115 » IO Cannot run program ...

    Tests run: 16, Failures: 0, Errors: 4, Skipped: 4

**Comment by skirpichenok** [comment]
@alex-palevsky issue has gone or do I do something wrong?

**Comment by alex-palevsky** [comment]
> @alex-palevsky I could not reproduce this issue. The IndexesRequestsTest passes on my local PC. 
> This is output for command **mvn -Dtest=\*\*\IndexesRequestsTest test**
> 
>     Results :
> 
>     Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
> 
>     [INFO] ------------------------------------------------------------------------
>     [INFO] BUILD SUCCESS
>     [INFO] ------------------------------------------------------------------------
>     [INFO] Total time: 33.140 s
>     [INFO] Finished at: 2016-01-17T17:45:49+03:00
>     [INFO] Final Memory: 38M/123M
>     [INFO] ------------------------------------------------------------------------
> 

@skirpichenok address all technical questions to the author of the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by skirpichenok** [comment]
@yegor256 I could not reproduce this issue. The IndexesRequestsTest passes on my local PC. 
This is output for command **mvn -Dtest=\*\*\IndexesRequestsTest test**

    Results :

    Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 33.140 s
    [INFO] Finished at: 2016-01-17T17:45:49+03:00
    [INFO] Final Memory: 38M/123M
    [INFO] ------------------------------------------------------------------------

**Comment by skirpichenok** [comment]
@yegor256 But I see the following output for command **mvn clean install -Pqulice**

    Results :

    Tests in error: 
      StartsDaemonITCase.startsDaemon:84 » IO Cannot run program "/usr/sbin/sshd": e...
      ArchivesDaemonITCase.archivesDaemon:70 » IO Cannot run program "/usr/sbin/sshd...
      EndsDaemonITCase.parsesHighlightedStdout:69->start:115 » IO Cannot run program...
      EndsDaemonITCase.readsExitCodeCorrectly:95->start:115 » IO Cannot run program ...

    Tests run: 16, Failures: 0, Errors: 4, Skipped: 4

**Comment by yegor256** [comment]
@skirpichenok that's a separate problem (your errors), feel free to report them in a new ticket. I'm closing this, since it's not reproducible.

**Comment by skirpichenok** [comment]
@yegor256 after installing the ssh I do not get any errors
