### ISSUE TITLE
StarsTest.java:47-48: When MkStars (issues jcabi/jcabi-github#965 and...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#734]
Puzzle `498-a06fa417` in `src/test/java/com/rultor/agents/github/StarsTest.java:47-48` has to be resolved: When MkStars (issues jcabi/jcabi-github#965 and jcabi/jcabi-github#965) is implemented remove Ignore annotations.... The puzzle was created by krzyk on 10-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@maurezen it is in your hands now, proceed when you can

**Comment by maurezen** [comment]
@alex-palevsky @yegor256 what do I do in case the dependency is not closed before my own deadline approaches?

**Comment by yegor256** [comment]
@maurezen just say here that you need more time because of that. or inform @alex-palevsky that you waiting for that particular dependency. we all will wait. check this: http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by maurezen** [comment]
@alex-palevsky created a pull request here #745

**Comment by maurezen** [comment]
@alex-palevsky  jcabi/jcabi-github#965 is fixed and released, but rultor dependency is not updated yet. Created a ticket #746 for that, this issue depends on it.

**Comment by yegor256** [comment]
@alex-palevsky we're waiting for #746 here

**Comment by alex-palevsky** [comment]
> @alex-palevsky we're waiting for #746 here

@yegor256 issue #746 is closed already

**Comment by maurezen** [comment]
@alex-palevsky pull request #745 merged into master, please close the issue.

**Comment by maurezen** [comment]
@alex-palevsky the issue is resolved, please close it.

**Comment by alex-palevsky** [comment]
Done, thanks all, closing..

**Comment by alex-palevsky** [comment]
@maurezen Many thanks! **30 mins** were added to your account in Transaction ID `50601568`... +30 added to your rating, at the moment it is: [+825](http://www.netbout.com/b/35102?open=rating)
