### ISSUE TITLE
Rultor doesn't work (load average is 30.60, too high to run a new Docker container)

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#738]
There is some problem with rultor.com. In http://www.rultor.com/t/1605-70236821 I see lots of messages like this:

```
++ bc + '[' 1 -eq 1 ']' 
+ echo 'load average is 31.98, too high to run a new Docker container' load average is 31.98, too high to run a new Docker container 
+ echo 'I will try again in 15 seconds' I will try again in 15 seconds 
+ sleep 15 
+ true 
++ uptime 
++ sed 's/ /\n/g' 
++ tail -n 1 
+ load=32.05 
++ echo 32.05 '>' 30 
++ bc + '[' 1 -eq 1 ']' 
+ echo 'load average is 32.05, too high to run a new Docker container' load average is 32.05, too high to run a new Docker container 
+ echo 'I will try again in 15 seconds' I will try again in 15 seconds + sleep 15
```
Please fix this issue (make sure that rultor.com executes the merge requests or rejects them).

**Comment by yegor256** [comment]
it's a predictable behavior, not a bug. when the server is too busy, rultor doesn't start a new Docker container, to avoid too high server load. once the server gets less busy, rultor continues. so, it's by design, not a bug.
