### ISSUE TITLE
Github request limit

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#739]
looks like we're doing too many requests to Github (over 5000 per hour)

**Comment by caarlos0** [comment]
yeap, that's why I suggested to use webhooks in #778

**Comment by cvrebert** [comment]
Probably related: https://github.com/jcabi/jcabi-github/issues/1092

**Comment by original-brownbear** [comment]
@yegor256 can you close this or is Rultor still experiencing this with the above fix?

**Comment by yegor256** [comment]
@original-brownbear haven't seen this for months... closing.
