### ISSUE TITLE
Add documentation to talk.xsd

### ISSUE THREAD

**Issue by alevohin** [yegor256/rultor#742]
Add `<xs:documentation source="description">` to all elements in talk.xsd. Description must contain:
* Short description for element
* Short description how element used if it's not obviously

P.S. For example, look at XSD for pom.xml: http://maven.apache.org/xsd/maven-4.0.0.xsd

**Comment by yegor256** [comment]
@alevohin very good idea, thanks

**Comment by alex-palevsky** [comment]
this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@alevohin thanks for this report, I added 15 mins to your account, in transaction `50331042`

**Comment by alex-palevsky** [comment]
@oruam85 the issue is yours, help us

**Comment by oruam85** [comment]
The PR is https://github.com/yegor256/rultor/pull/750

**Comment by oruam85** [comment]
@alevohin The PR https://github.com/yegor256/rultor/pull/750#issuecomment-70991315 was merged. Please close this bug

**Comment by alevohin** [comment]
@oruam85 thanks!

**Comment by alex-palevsky** [comment]
@oruam85 **30 mins** sent to your balance (ID `50619306`), many thanks!... +30 to your rating, your total score is +120
