### ISSUE TITLE
Upgrade jcabi-github dependency version

### ISSUE THREAD

**Issue by maurezen** [yegor256/rultor#746]
Please upgrade jcabi-github dependency version to 0.18.7+

(Needed for #734)

**Comment by yegor256** [comment]
@maurezen It's a not a bug, since it doesn't explain what is broken, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken  Try to explain it better pls

**Comment by maurezen** [comment]
@yegor256 issue #734 depends on jcabi/jcabi-github#965 issue fix. While the latter was fixed and released in jcabi-github v0.18.7, rultor still depends on jcabi-github v0.18.6. 

Is it clearer now?

**Comment by yegor256** [comment]
@maurezen yes, it's clear, but why it's a problem here, in this ticket? If you need version 0.18.7 - use it while fixing the issue #734. What this new bug is about? What is wrong in master now?

**Comment by yegor256** [comment]
@maurezen bugs don't start with "please upgrade...". bugs start with "There is a bug in master branch, this doesn't work as expected..."

**Comment by maurezen** [comment]
@yegor256 0.18.7 introduced some interface changes, rultor [does not even compile](https://travis-ci.org/yegor256/rultor/builds/47563436) with it:
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rultor: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/yegor256/rultor/src/main/java/com/rultor/agents/github/Stars.java:[70,26] method starred in interface com.jcabi.github.Stars cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: java.lang.String,java.lang.String
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/travis/build/yegor256/rultor/src/main/java/com/rultor/agents/github/Stars.java:[71,25] method star in interface com.jcabi.github.Stars cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: java.lang.String,java.lang.String
[ERROR] reason: actual and formal argument lists differ in length

Is fixing compilation errors, possible tests errors and whatnot in the scope of #734? Or it is a separate issue?

**Comment by yegor256** [comment]
@maurezen you're trying to use a new library and your code doesn't compile. This problem is definitely in scope of your original task. The project doesn't need this new library, it works fine without it. You want to use it in order to fix your task. So, it's in your scope, for sure.

**Comment by maurezen** [comment]
@yegor256 ok, thanks.
