### ISSUE TITLE
Upgrade saxon dependency version

### ISSUE THREAD

**Issue by maurezen** [yegor256/rultor#747]
While running some of the tests (IndexesRequestsTest, for example), ran into the incorrect config of Saxon 9.1.0.8

>java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:%path%/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax

This is a [known bug](https://saxonica.plan.io/issues/1944#note-3).

Please upgrade dependency version to the one in which the issue is fixed.

**Comment by maurezen** [comment]
Whoops, this is an issue for jcabi-xml.

**Comment by yegor256** [comment]
@maurezen how can I reproduce this on master branch?
