### ISSUE TITLE
Amazon.java:42-47: Add implementation for com.rultor.agents.ec2.Amazon. It...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#755]
Puzzle `629-e67af157` in `src/main/java/com/rultor/agents/ec2/Amazon.java:42-47` has to be resolved: Add implementation for com.rultor.agents.ec2.Amazon. It must create com.amazonaws.services.ec2.AmazonEC2 client with config params "credentials", "zone", "type", "key". Use client.runInstances(com.amazonaws.services.ec2.model.RunInstancesRequest) to run on-demand instance. Method runOnDemand must finally wait for started instance and check if start was successful.... The puzzle was created by alevohin on 18-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@marczeeee help us,the task is yours

**Comment by yegor256** [comment]
@alex-palevsky assign someone else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 I will assign somebody else to this issue

**Comment by alex-palevsky** [comment]
@yegor256 there is no milestone yet, so I set it to `0.3`

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear sure, thanks, I added "postponed" label to it

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear right, I'll try to find someone else for this task

**Comment by alex-palevsky** [comment]
@original-brownbear The task is done, thanks all, I am closing it
