### ISSUE TITLE
Can't merge PR

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#762]
During attempts to merge PR https://github.com/yegor256/rultor/pull/753 , several errors occur, including this: Maven tries to access file https://oss.sonatype.org/content/groups/public/com/jcabi/parent/0.32.1/parent-0.32.1-site_en.xml , but it doesn't exist in that directory. `https://oss.sonatype.org/content/groups/public/com/jcabi/parent/0.32.1/` exists, but there is no file `parent-0.32.1-site_en.xml` there.

Full log: http://www.rultor.com/t/1705-71502185

Desired outcome: Rultor can successfully merge PR #753 .

**Comment by yegor256** [comment]
@dpisarenko it's not a bug, since it only happens in your particular branch. Master is broken? Can I reproduce this in master?
