### ISSUE TITLE
Add socat to Rultor build environment

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#767]
It would be useful to have the *nix command 'socat' available in the Rultor environment for testing.

**Comment by yegor256** [comment]
you can install it yourself, in `.rultor.yml` config of your specific project. we can't install all possible commands into our default image. just do this:

```yaml
install:
  - sudo apt-get install socat
```

**Comment by pinaf** [comment]
@yegor256 got it. thanks.
