### ISSUE TITLE
HTTP compression when serving text data

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/rultor#772]
I'm not aware of whether Rultor gzip compresses HTTP text data, but any pages that Rultor returns for me are not transmitted in compressed form. For example:

![image](https://cloud.githubusercontent.com/assets/1917892/6161718/1abcdf00-b2b0-11e4-9fb4-54e02d6498a1.png)

It would be very helpful if we can support this feature. Some of the logs that are produced are downright *colossal*!

![image](https://cloud.githubusercontent.com/assets/1917892/6161763/e9b3b8c4-b2b0-11e4-83bd-18f9be3ad678.png)

Yes, it took my browser two minutes to render a 4MB page, but it would be a huge help to users who don't have very fast Internet connections, or big mobile data allowances. :)

**Comment by alex-palevsky** [comment]
I'll ask someone to take care of this task soon

**Comment by alex-palevsky** [comment]
@carlosmiranda many thanks for the bug report, I added 15 mins to your acc, transaction `51639039`

**Comment by alex-palevsky** [comment]
@apocarteres the ticket is yours, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.8`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.8`

**Comment by yegor256** [comment]
@carlosmiranda looks like gzip works now, please check

**Comment by carlosmiranda** [comment]
Looks good, thanks!
