### ISSUE TITLE
Use Webhooks

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#778]
Current implementation is based on notifications, right?

I believe this is a little slow. Wouldn't it be best to, after a `@rultor hello`, add a webhook to the repository and use listen to that instead?

Kudos for @velo for helping point it out.

**Comment by yegor256** [comment]
@caarlos0 but to add a webhook rultor has to have admin rights to the repo, right?

**Comment by caarlos0** [comment]
@yegor256 unfortunately yes...

**Comment by caarlos0** [comment]
But I believe it will be good thing (using OAUTH), and will also reduce the amount of API calls...

**Comment by yegor256** [comment]
@caarlos0 that will change the entire "style" of rultor. We want to keep it admin-panel free, so that our users don't need to click any buttons or create any accounts. Everything is very light-weight and on-demand :)

**Comment by yegor256** [comment]
@caarlos0 but thanks for the suggestion! :)

**Comment by caarlos0** [comment]
@yegor256 ok, no problem :)
