### ISSUE TITLE
Rultor should not propose 2nd level review to the PR author

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#779]
Rultor should not propose 2nd level review to the PR author.
See xockets-hadoop-transport PR 439 for details :)

**Comment by alex-palevsky** [comment]
this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@longtimeago thanks for the ticket, your account was topped for 15 mins, payment 51997121

**Comment by alex-palevsky** [comment]
@adko-pl your task now plz proceed when you have time

**Comment by adko-pl** [comment]
@alex-palevsky please find another developer

**Comment by yegor256** [comment]
@alex-palevsky give this to somebody else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky give this to somebody else pls

@yegor256 no problem, I will try to find somebody else

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.7`

**Comment by yegor256** [comment]
@longtimeago this problem is fixed, please check and close, thanks

**Comment by longtimeago** [comment]
@yegor256 yep, thanks!
