### ISSUE TITLE
show only 50 commits in release description

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#785]
Let's limit the number of commits to show in `CommentsTag` to 50. Now we're showing all of them and Github crashes (it doesn't allow that many). If there are more than 50 let's add a message that there are more but we skipped them.

**Comment by alex-palevsky** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by alex-palevsky** [comment]
we will find someone to do this task, soon

**Comment by alex-palevsky** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-adc5c5fb`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.3`
