### ISSUE TITLE
Rultor is freezing for 2 hours

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#787]
please see http://www.rultor.com/t/2265-76414711 and http://www.rultor.com/t/2247-76414116
note it stops in different points in the build

**Comment by yegor256** [comment]
@pinaf how do you know it's not a bug inside the build itself? on other projects everything works just fine

**Comment by pinaf** [comment]
@yegor256 I don't know for sure. The only indication is that it stopped at 2 different points in the tests.

**Comment by yegor256** [comment]
@pinaf let's monitor the situation... I don't see how Docker may be a problem here. Rultor just starts a new Docker container with a Maven build inside it. If if suddenly stops, I would blame the app first. maybe we should try to get some additional stats from Docker at our `rultor status` report, to understand this problem better...

**Comment by pinaf** [comment]
@yegor256 I agree. I just got a successful deploy.. let's see a merge now. The issue might be some sort of race condition or starvation in the tests themselves that only arises when the machine is under high load.

**Comment by yegor256** [comment]
@pinaf I just started that project on my Mac and it's also hanging.. so, not a rultor problem

**Comment by pinaf** [comment]
@yegor256 on which step did it hang?

**Comment by yegor256** [comment]
I'll report a bug in the project
