### ISSUE TITLE
STOP doesn't really terminate Docker container

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#788]

**Comment by yegor256** [comment]
@pinaf I'm working on this one

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.7`

**Comment by pinaf** [comment]
@yegor256 thanks! if you could manually kill the sigzig rultor docker instance when this new version deploys it would be great!

**Comment by yegor256** [comment]
@pinaf yes, should work. as you see, there was a rather simple bug inside.

**Comment by yegor256** [comment]
@pinaf does it work now?

**Comment by pinaf** [comment]
@yegor256 let me try

**Comment by pinaf** [comment]
@yegor256 maybe kill -9?

**Comment by yegor256** [comment]
@pinaf seems to be working

**Comment by pinaf** [comment]
@yegor256 yup. thanks!
