### ISSUE TITLE
migrate to Takes

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#789]

**Comment by alex-palevsky** [comment]
I will find a developer for the task soon...

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by alex-palevsky** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-853f5e46

**Comment by yegor256** [comment]
@rultor release, tag is `1.50`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50`

**Comment by alex-palevsky** [comment]
@yegor256 Much obliged! I have added **30 mins** to your account in payment "000-381a4df3". +30 added to your rating, at the moment it is: [+7982](http://www.netbout.com/b/35008?open=rating)
