### ISSUE TITLE
Add new command "test"

### ISSUE THREAD

**Issue by alevohin** [yegor256/rultor#791]
Let's add new command `test`. This command must execute `mvn clean install -Pqulice` by default or it can be overriden by config `.rultor.yml`.

Dialog with rultor must be like `merge` dialog, for example
> username: @rultor test
> rultor: @username OK, I'll try to test now. You can check the progress of the test here
> rultor: @username OK, I'll try to test now. You can check the progress of the test here
> rultor: Oops, I failed. You can see the full log here (spent 1hr)

or
> rultor: @username Done! FYI, the full log is here (took me 8min)

This command is helpful for CR. If Travis build failed due to spurious test fails, reviewer has no ability to restart travis build. One more commit to restart Travis build looks strange. If we merge without Travis success status, we can broken master state (for example, cobertura doesn't check if test fails).

Rultor should accept `test` command from code reviewer or PR owner. In other cases it should get confirmation from project lead.

**Comment by yegor256** [comment]
@alevohin very good idea, thanks

**Comment by alex-palevsky** [comment]
I will find a developer for the task soon...

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now

**Comment by alex-palevsky** [comment]
@alevohin thanks for this report, I added 15 mins to your account, in transaction `52780195`

**Comment by alex-palevsky** [comment]
@alevohin I added milestone `0.3` to this issue, let me know if there has to be something else

**Comment by yegor256** [comment]
@alevohin we should use "rultor deploy" for this. The deployment operation is supposed to be **frequently** executed without any harm to the overall process. In other words, you should be able to "deploy" your product as many times per day as possible. Thus, no need to introduce a new "test" command
