### ISSUE TITLE
Rultor hangs on to docker container indefinitely?

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#792]
taken from http://www.rultor.com/t/2267-76508954
is it possible rultor doesnt forget about a container it launched?

>
 time="2015-02-28T21:07:01+01:00" level="fatal" msg="Error response from daemon: Conflict, The name teamed_sigzig_366 is already assigned to 97f769bf2aa1. You have to delete (or rename) that container to be able to assign teamed_sigzig_366 to a container again."

**Comment by yegor256** [comment]
@pinaf this is definitely a valid bug, but I'm not sure how to fix it. for some reason Docker may fail to delete a container and a new rultor request will try to create another one, with the same name. we need to find a way to detect these abandoned containers and destroy them

**Comment by pinaf** [comment]
@yegor256 if rultor knows their name, can't it just reap those that haven't ended in 2hrs by telling docker to kill them? I don't know how docker operates, but if the containers are separate processes rultor could kill them by itself, without resorting to docker.

**Comment by yegor256** [comment]
@pinaf rultor is rather stateless. it doesn't remember what happened a day ago. well, it does remember, but it is not designed to manipulate that information. anyway, I'll think about it

**Comment by pinaf** [comment]
@yegor256 it does remember because it prints out the docker container :) thanks!

**Comment by pinaf** [comment]
@yegor256 is it possible to manually delete some docker containers in order for some PRs to get merged? IF not, I guess I'll have to create new issues and ask for new PRs.

**Comment by yegor256** [comment]
@pinaf it's possible, give me their names

**Comment by yegor256** [comment]
@pinaf no need, I killed them all

**Comment by yegor256** [comment]
@pinaf the problem is that we're still using one and the same server all the time. it gets "tired". we should start a new EC2 machine for every build. hopefully we'll have this feature soon.

**Comment by pinaf** [comment]
@yegor256 nice! thank you!

**Comment by pinaf** [comment]
@yegor256 still stuck here http://www.rultor.com/t/2293-76599461
>
Error response from daemon: Conflict, The name teamed_sigzig_388 is already assigned to 0d40d50ec987. You have to delete (or rename) that container to be able to assign teamed_sigzig_388 to a container again."

**Comment by pinaf** [comment]
@yegor256 here's another one http://www.rultor.com/t/2296-76599895
>
+ docker run --rm -v /tmp/rultor-REVf:/main '--env=MAVEN_OPTS=-XX:MaxPermSize=256m -Xmx1g' --env=fork=git@github.com:alevohin/sigzig.git --env=fork_branch=365 --env=head=git@github.com:teamed/sigzig.git --env=head_branch=master --memory=4g --cidfile=/tmp/rultor-REVf/cid -w=/main --name=teamed_sigzig_383 yegor256/rultor /main/entry.sh time="2015-03-01T15:55:14+01:00" level="fatal" msg="Error response from daemon: Conflict, The name teamed_sigzig_383 is already assigned to 44fb1e56c4e1. You have to delete (or rename) that container to be able to assign teamed_sigzig_383 to a container again."

**Comment by longtimeago** [comment]
+1
same shit with xocket's builds

**Comment by yegor256** [comment]
@pinaf @longtimeago I added this line to crontab on the server:

```
*/10 * * * * sudo docker rm $(sudo docker ps -a | grep 'hours ago' | awk '{print $1}') >/dev/null
```

should be fine now

**Comment by yegor256** [comment]
Docker doesn't destroy containers (as it is supposed to do) after this error:

```
docker run --rm -v /tmp/rultor-vQto:/main '--env=MAVEN_OPTS=-XX:MaxPermSize=256m -Xmx1g' --env=head=git@github.com:yegor256/rultor.git --env=head_branch=master --env=tag=1.49.9 --memory=4g --cidfile=/tmp/rultor-vQto/cid -w=/main --name=yegor256_rultor_795 yegor256/rultor /main/entry.sh time="2015-03-01T20:31:20+01:00" level="fatal" msg="Post http:///var/run/docker.sock/v1.16/containers/2c706832da6ccf0e0ab05ba6c7f1930a26022302e1bcf2a987f8f9c4b71f3970/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?"
```

When this happens, the container stays in the list and can't be created again, with the same name

**Comment by yegor256** [comment]
Restart of Docker solves the original problem, but containers still have to be removed manually.

```
sudo service docker restart
```

**Comment by longtimeago** [comment]
```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

**Comment by yegor256** [comment]
@longtimeago yes, this will destroy all containers on the server, but Rultor is not the only citizen there. and this will destroy also running containers. we need to find a way to destroy containers that are not running any more.

**Comment by longtimeago** [comment]
seek and destroy ...

**Comment by pinaf** [comment]
@yegor256 but if rultor remembers every container it launched, we should be able to use that info to target the lingering ones.

**Comment by yegor256** [comment]
@pinaf rultor doesn't remember container IDs

**Comment by yegor256** [comment]
Rultor remembers the coordinates of the server where container is running (`b1.rultor.com:22`) and the path there (`/tmp/rultor-ABCD`). This is what is happening:

 1. rultor logins to the server via SSH
 2. it tries to start a container in `/tmp/rultor-ABCD`
 3. docker crashes and doesn't save container ID into `/tmp/rultor-ABCD/cid`
 4. rultor is trying to stop the container but `cid` file is absent
 5. docker is still keeping the container in its database and doesn't allow to start it again

**Comment by pinaf** [comment]
isn't '44fb1e56c4e1'  a container id?
>
Conflict, The name teamed_sigzig_383 is already assigned to 44fb1e56c4e1. You have to delete (or rename) that container to be able to assign teamed_sigzig_383 to a container again."

**Comment by pinaf** [comment]
@yegor256 also, the command 'status' prints out a docker container id
>
@rultor status
@pinaf This is what's going on here:

1 build(s) archived: 2294-76627895
request 76630710 is in processing, command is merge
request has 4 parameter(s):
fork: git@github.com:alevohin/sigzig.git
fork_branch: 339-2
head: git@github.com:teamed/sigzig.git
head_branch: master
build started 33.5 minutes ago
build is running in /tmp/rultor-wLnp directory
Docker container ID: a0d517191e03ef475fef...
working directory size: 180K
server load average: 0.66

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by alex-palevsky** [comment]
@pinaf many thanks for the bug report, I added 15 mins to your acc, transaction `AP-9HF62141R0486152E`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.6`

**Comment by yegor256** [comment]
@pinaf looks like this problem is fixed, let's wait for version 1.50.7 and check it

**Comment by pinaf** [comment]
@yegor256 how should we test it?

**Comment by yegor256** [comment]
@pinaf there is no way to test it, I believe. well, no easy way. let's just close the ticket and if the problem appears again - we open a new one.

**Comment by pinaf** [comment]
@yegor256 agreed

**Comment by alex-palevsky** [comment]
@yegor256 Many thanks! **30 mins** were added to your account in Transaction ID `000-981f21ad` (task took 652 hours and 54 mins)... added +30 to your rating, now it is equal to [+8466](http://www.netbout.com/b/35008?open=rating)
