### ISSUE TITLE
 Cannot start container: too many open files

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#794]
From http://www.rultor.com/t/2293-76580766
>
+ docker run --rm -v /tmp/rultor-vv8M:/main '--env=MAVEN_OPTS=-XX:MaxPermSize=256m -Xmx1g' --env=fork=git@github.com:pinaf/sigzig.git --env=fork_branch=387 --env=head=git@github.com:teamed/sigzig.git --env=head_branch=master --memory=4g --cidfile=/tmp/rultor-vv8M/cid -w=/main --name=teamed_sigzig_388 yegor256/rultor /main/entry.sh time="2015-03-01T07:35:54+01:00" level="fatal" msg="Error response from daemon: Cannot start container 0d40d50ec98735046321aeadf7bf6e4dcfe27566d196e9c32a29c26c899ea815: fork/exec /var/lib/docker/init/dockerinit-1.4.1: too many open files"

**Comment by yegor256** [comment]
similar to #783

**Comment by yegor256** [comment]
@pinaf I will reboot the server
