### ISSUE TITLE
BUI link is broken 

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#795]
There is a link on the rultor main page at the top:
BUI - https://github.com/yegor256/rultor/commit/BUILD
But it doesn't work (404)

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.9`

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.9`

**Comment by yegor256** [comment]
@longtimeago fixed, thanks

**Comment by alex-palevsky** [comment]
@yegor256 please don't close it.. @longtimeago could you please close it, if it is done?

**Comment by longtimeago** [comment]
@yegor256 for me it still 404

**Comment by yegor256** [comment]
@longtimeago of course, that link won't work. it was a wrong link. it won't happen again. open www.rultor.com and see the link on top of the page. it should be working.

**Comment by longtimeago** [comment]
@yegor256 yep, now it's good. Thanks!
