### ISSUE TITLE
Can't login to the rultor

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#797]
When pushing the "login" button url changed to
```
http://www.rultor.com/?error=redirect_uri_mismatch&
error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&
error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch
```
And I'm still not logged in, so can't view rultor build logs :(

**Comment by pinaf** [comment]
can't login here either but URL goes to `http://www.rultor.com/?PsByFlag=PsGithub&code=dc2477f0771c3aeb272a`
rultor goes back to home page and login link is still there

**Comment by yegor256** [comment]
I'm on it...

**Comment by yegor256** [comment]
@pinaf @longtimeago should be fine now
