### ISSUE TITLE
Rultor Logs: print java version / JAVA_HOME before build

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#801]
For debugging purposes, it makes sense for rultor to print out in each individual build log file some information about its environment such as:
- java -version
- echo $JAVA_HOME
- if possible, info on the docker container it is running in.

**Comment by yegor256** [comment]
@pinaf not each project is working with Java. some of them are in PHP, for example. So, it's up to the project owner what to show in the logs. If you want to know the version of java, just add `java -version` to the list of instructions. The docker container name you can find in logs. It is given to the `docker` command. By default it is `yegor256/rultor`

**Comment by pinaf** [comment]
@yegor256 thanks!
