### ISSUE TITLE
use HEAD rultor.yml during merge

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#802]
It's better to use `.rultor.yml` from HEAD branch during merge operation, instead of BASE one, like it's done now. Mostly because this will allow branch author to modify rultor configuration even when it's broken.

**Comment by alex-palevsky** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-554e757b`

**Comment by pinaf** [comment]
this is important.

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.5`

**Comment by pinaf** [comment]
@yegor256 this is in place now?

**Comment by yegor256** [comment]
@pinaf yes, it should work, try it

**Comment by pinaf** [comment]
@yegor256 there's a merge coming up that will test it :)

**Comment by pinaf** [comment]
@yegor256 doesn't look like it worked: http://www.rultor.com/t/2925-87281391
in that issue krzyk removed some lines from rultor.yml that were still executed in the merge.

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.9`

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.9`

**Comment by yegor256** [comment]
@pinaf should be fine now, please check

**Comment by alex-palevsky** [comment]
@yegor256 I added milestone `0.3` to this issue, let me know if there has to be something else

**Comment by carlosmiranda** [comment]
@yegor256 @pinaf It still didn't work when we tried to merge https://github.com/teamed/xockets-hadoop-transport/pull/605 [see log](http://www.rultor.com/t/3534-95457596). @longtimeago had to create a separate PR just to push the `.rultor.yml` change to `master`: https://github.com/teamed/xockets-hadoop-transport/pull/607.

**Comment by sils1297** [comment]
Hey, sorry to interrupt: this feature is a security risk. If e.g. logs are only readable by specified users I could change the yml to give myself access in a fork without collaborator permissions. Same with private assets which I could then simply cat out to the log to get to the secure assets of the original repository.

**Comment by yegor256** [comment]
@sils1297 yeah, indeed...

**Comment by sircharleswatson** [comment]
I came here to ask about this exact question. But now reading this issue it makes sense that it shouldn't use the HEAD `rultor.yml` during merge because of the security issue. So, just to verify, it would be better to merge this in manually correct?

**Comment by yegor256** [comment]
@sircharleswatson yes, seems so. Changes to `.rultor.yml` should be merged manually, by the owner of the repo

**Comment by sircharleswatson** [comment]
Sounds good! Thanks!

**Comment by sils1297** [comment]
> Hey, sorry to interrupt: this feature is a security risk. If e.g. logs are only readable by specified users I could change the yml to give myself access in a fork without collaborator permissions. Same with private assets which I could then simply cat out to the log to get to the secure assets of the original repository.

Actually I disagree with the previous me as the merge can only be triggered by an authenticated person.

**Comment by alex-palevsky** [comment]
@kujtimiihoxha could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by kujtimiihoxha** [comment]
@alex-palevsky  waiting for #986

**Comment by alex-palevsky** [comment]
> @alex-palevsky  waiting for #986

@kujtimiihoxha yes, waiting for #986

**Comment by longtimeago** [comment]
@yegor256 we are really waiting for this feature!

**Comment by yegor256** [comment]
@longtimeago I don't think we should implement this, due to security concerns expressed above. I'm closing it.
