### ISSUE TITLE
Cannot start container: too many open files

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#803]
>
yegor256/rultor /main/entry.sh time="2015-03-18T19:40:43+01:00" level="fatal" msg="Error response from daemon: Cannot start container 2a4f3c75b1796f4c93f00b9728d0fb79a6709a7bbd1248f1c87a108cb87b89c5: pipe2: too many open files"

**Comment by yegor256** [comment]
should be fine already

**Comment by pinaf** [comment]
@yegor256 thx
