### ISSUE TITLE
rultor can't fetch log text

### ISSUE THREAD

**Issue by jcai** [yegor256/rultor#804]
see:
https://github.com/ganshane/monad/releases/tag/5.0.4

**Comment by yegor256** [comment]
@jcai indeed, it's a bug with encoding, thanks for reporting!

**Comment by alex-palevsky** [comment]
I will find a developer for the task soon...

**Comment by yegor256** [comment]
@rultor release, tag is `1.50.4`

**Comment by yegor256** [comment]
@jcai I believe this issue is fixed, please try and close the ticket if it's gone

**Comment by jcai** [comment]
perfect!
https://github.com/ganshane/monad/releases/tag/5.0.7
