### ISSUE TITLE
Rultor should show tail of the build log in case of failed command

### ISSUE THREAD

**Issue by krzyk** [yegor256/rultor#807]
When rultor command fails and there is a log for it (e.g. when it is a build or deploy), rultor should show in a comment a configurable amount of lines from the tail of the log (e.g. last 100 lines), below the usual *Oops, I failed. You can see the full log here*
The lines of the log should be enclosed in triple backticks (the usual code tags).

This way one could see right away what's wrong and not download a multiple MB file and scroll to its bottom.

**Comment by yegor256** [comment]
@krzyk good idea, thanks!

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now, go ahead

**Comment by alex-palevsky** [comment]
@krzyk many thanks for the bug report, I added 15 mins to your acc, transaction `54248473`

**Comment by yegor256** [comment]
@rultor release, tag is `1.51`

**Comment by yegor256** [comment]
@rultor release, tag is `1.51`

**Comment by yegor256** [comment]
@rultor release, tag is `1.51`

**Comment by yegor256** [comment]
@rultor release, tag is `1.51`

**Comment by yegor256** [comment]
@krzyk looks like this feature works already, please close the ticket

**Comment by krzyk** [comment]
thanks

**Comment by alex-palevsky** [comment]
@yegor256 Much appreciated! **38 mins** was added to your account, payment ID `000-6d43a4df`, time spent is 115 hours and 30 mins

the bonus for fast delivery (age=2933)

+38 added to your rating, current score is: [+8538](http://www.netbout.com/b/35008?open=rating)
