### ISSUE TITLE
rultor is failing

### ISSUE THREAD

**Issue by LeanderK** [yegor256/rultor#808]
i followed this tutorial: http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html
and tried it: https://github.com/intellimate/izou-pf4j/issues/4#issuecomment-86938408
here is the log: http://www.rultor.com/t/2895-1
i don't even see a failure and don't know if it is mine or rultors error.

**Comment by yegor256** [comment]
@LeanderK the problem is that your project is _already_ in version 1.1: https://github.com/intellimate/izou-pf4j/blob/master/pom.xml#L8 Your `mvn versions:set` command has no effect, it doesn't change anything in `pom.xml`, that's why `git commit` fails. Change version to `2.0-SNAPSHOT` in pom.xml and run it again.

**Comment by LeanderK** [comment]
ok, now i have another problem...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project pf4j: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
is rultor able to compile for target java 8?

**Comment by yegor256** [comment]
@LeanderK rultor is working with `yegor256/rultor` Docker container, which has Java 7 inside (https://registry.hub.docker.com/u/yegor256/rultor/). If you want to use Java 8, pick one of Docker containers with Java 8 (search for them in hub.docker.com) and use them inside your `.rultor.yml`, see http://doc.rultor.com/reference.html#docker-image

**Comment by LeanderK** [comment]
ok i fixed most issues, but it is failing to commit to git.
https://github.com/intellimate/izou-pf4j/pull/9#issuecomment-88487742
here is an example, i have always wondered how rultor got permission.
have i forgot something? is there any way i can authorise him?

**Comment by LeanderK** [comment]
ok, i invited rultor to our organization...i don't know if it fixes the problem. Is this the preferred way?
If yes, you should add this to your tutorial :)

**Comment by yegor256** [comment]
@LeanderK yes, we received your invitation and accepted it already. Try to run it again, should work. You're right, we will update the documentation.

**Comment by LeanderK** [comment]
ok, now i have another problem (possibly bug). if i add the rultor team as a collaborator to a project, the command authentication fails. You can see it here:
https://github.com/intellimate/izou-pf4j/issues/11

**Comment by LeanderK** [comment]
and a question occurred me....what happens if our default branch is not named master? i am currently struggling with this project: https://github.com/intellimate/IzouSDK, here is the log: http://www.rultor.com/t/3056-88897334
i seems it doesn't pick up the .rultor.yml. We are currently migrating from naming our default branch master to reflecting version numbers as branches with the current version number as default. And this project is the first. I wonder if thats possible.

**Comment by yegor256** [comment]
@LeanderK rultor must have "write" (!) access to the repository. make sure you not only add rultor as a collaborator but also give write-access to it. about master branch, it's a bug in rultor: https://github.com/yegor256/rultor/issues/818 we're planning to fix it in a few days. I will update you!

**Comment by LeanderK** [comment]
ok, thank you for your awesome work! :) I have added rultor to a team with write access (which is added as a collaborator to every repo)...weird, i'll try it later again.

**Comment by LeanderK** [comment]
i just added the write-access team containing rultor to a repo and again discovered the weird behaviour thinking i am not an authorised commander: https://github.com/intellimate/IzouSDK/issues/3
the second request was with rultor added.

**Comment by yegor256** [comment]
@LeanderK this time everything is fine with rultor, you have a problem in your `pom.xml`: 

```
Invalid POM: /org/intellimate/izou/sdk/0.5.21/sdk-0.5.21.pom: License information missing
```

**Comment by LeanderK** [comment]
yeah, i know....but l mean the request before.

**Comment by LeanderK** [comment]
https://github.com/intellimate/IzouSDK/issues/5, here i added the team write (which has write access) containing rultor.

**Comment by yegor256** [comment]
@LeanderK try to follow the instructions and add your account to the list of `commanders` in `.rultor.yml`. Let me know if it doesn't work, I'll try to help

**Comment by LeanderK** [comment]
if i delete the team from collaborators it works...it also works in the other repos (where i haven't added rultor until now)

**Comment by LeanderK** [comment]
'....
architect:
  - LeanderK
  - jundl77
....'
ah ok, so if i am already an architect, i also have to be an commander? I'll try

**Comment by LeanderK** [comment]
ok, its working now, if it need commanders when its added then thank you! :)
"By default, only Github repository collaborators can give commands." i am a collaborator, i don't know if this is a bug!
