### ISSUE TITLE
master is used instead of default repo branch

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#818]
At the moment, `master` is always used as a default branch of a repository. Let's fix that and use the branch configured as "default".

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now,go ahead

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-2168db69`

**Comment by alex-palevsky** [comment]
@yegor256 attached this issue to milestone "0.3" (let me know if this is wrong)

**Comment by yegor256** [comment]
@alex-palevsky assign someone else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 -30 points to your rating :(

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 right, I will find someone else, no problem

**Comment by alex-palevsky** [comment]
@kujtimiihoxha please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by kujtimiihoxha** [comment]
@alex-palevsky assign someone else

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else  

@kujtimiihoxha deducted 30 from your rating :(

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else  

@kujtimiihoxha OK, I will try to assign someone else

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear OK, I put "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear I will ask somebody else to pick this up

**Comment by yegor256** [comment]
fixed
