### ISSUE TITLE
StartsEC2.java:58-59: Write documentation for configuring ec2...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#824]
Puzzle `629-b8fe2cc2` in `src/main/java/com/rultor/agents/ec2/StartsEC2.java:58-59` has to be resolved: Write documentation for configuring ec2 via .rultor.yml at 2014-07-13-reference.md... The puzzle was created by alevohin on 18-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 I added milestone `0.3` to this issue, let me know if there has to be something else

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear thanks, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear no problem, I will try to find somebody else

**Comment by alex-palevsky** [comment]
@original-brownbear The issue is closed
