### ISSUE TITLE
StartsEC2.java:48-50: Implement com.rultor.agents.ec2.StopsEC2 agent. It must...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#825]
Puzzle `629-7845a57e` in `src/main/java/com/rultor/agents/ec2/StartsEC2.java:48-50` has to be resolved: Implement com.rultor.agents.ec2.StopsEC2 agent. It must stopped EC2 on-demand instance if it was started at StartsEC2 agent. StopsEC2 must use instance id from /talk/ec2/[@id] to stop it.... The puzzle was created by Yuriy.Alevohin on 20-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 I set milestone here to `0.3`, let me know if it is wrong

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear thanks, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear someone else will help in this task, no problem at all

**Comment by alex-palevsky** [comment]
@original-brownbear The task is done, thanks all, I am closing it
