### ISSUE TITLE
StartsEC2.java:55-57: Add new instance creation classes...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#826]
Puzzle `629-50db40cf` in `src/main/java/com/rultor/agents/ec2/StartsEC2.java:55-57` has to be resolved: Add new instance creation classes for StartsEC2 and StopsEC2 to com.rultor.agents.Agents. StartsEC2 must be invoked before RegistersShell agent. StopsEC2 must be invoked after RemovesShell agent.... The puzzle was created by alevohin on 18-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear I will try to find someone else

**Comment by alex-palevsky** [comment]
@original-brownbear Closed, thanks all
