### ISSUE TITLE
StartsEC2.java:51-54: RegistersShell must register SSH params...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#827]
Puzzle `629-1e130e87` in `src/main/java/com/rultor/agents/ec2/StartsEC2.java:51-54` has to be resolved: RegistersShell must register SSH params "host", "port", "login", "key" for ec2 on-demand instance, if this one was successfully started. Successfully start means that these parameters exist in /talk/ec2... The puzzle was created by alevohin on 18-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 since there is no milestone yet I set it to "0.3"

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear OK, I put "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear right, I will find someone else, no problem

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks all, closed
