### ISSUE TITLE
Mails.java:54-56: Describe in file 2014-07-13-reference.md config...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#828]
Puzzle `748-bb1cb5c5` in `src/main/java/com/rultor/agents/Mails.java:54-56` has to be resolved: Describe in file 2014-07-13-reference.md config parameters for email after release and how it works shortly. Config format described in issue #748.... The puzzle was created by alevohin on 20-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 I added milestone `0.3` to this issue, let me know if there has to be something else

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear sure, thanks, I added "postponed" label to it

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear no problem, I will try to find somebody else

**Comment by alex-palevsky** [comment]
@original-brownbear I'm closing the issue...
