### ISSUE TITLE
MailsTest.java:95-96: Implement method sendsToRecipients. It must...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#829]
Puzzle `748-a3bd319f` in `src/test/java/com/rultor/agents/MailsTest.java:95-96` has to be resolved: Implement method sendsToRecipients. It must check that mail is sent to all recipients. Recipients are defined in Profile.... The puzzle was created by alevohin on 20-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear got it, "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear all right, we'll find someone else for this task

**Comment by alex-palevsky** [comment]
@original-brownbear The task is closed, thanks everybody
