### ISSUE TITLE
Mails.java:47-53: Implement Mails agent. Similar to...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#830]
Puzzle `748-9cbe7474` in `src/main/java/com/rultor/agents/Mails.java:47-53` has to be resolved: Implement Mails agent. Similar to what we do in CommentsTag we should do here - send an email to all listed addresses. The body of the email should contain similar text to what we create for the tag comment. Postman's parameters are stored in Manifest.MF. We need 4 parameters: Rultor-SMTPHost, Rultor-SMTPPort, Rultor-SMTPUsername, Rultor-SMTPPassword. New instance of Mails must be created at Agents, after CommentsTag.... The puzzle was created by alevohin on 20-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 attached this issue to milestone "0.3" (let me know if this is wrong)

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear OK, I put "postponed" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear I will try to find someone else

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks, closing it now.
