### ISSUE TITLE
timeout shut down doesn't destroy the container

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#831]
When rultor stops a command because of a time out, its Docker container keeps working and doesn't stop. Well, will never stop, if the command inside it doesn't stop. We should use `docker rm -f` to stop it, instead of `kill -9`

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now, go ahead

**Comment by alex-palevsky** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-3eecfa4a`

**Comment by alex-palevsky** [comment]
@yegor256 since there is no milestone yet I set it to "0.3"

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.4`

**Comment by alex-palevsky** [comment]
@yegor256 Thanks for your contribution, **38 mins** was added to your account, payment ID is `000-65d53bb4`, 550 hours and 27 mins spent total

age=3188, that's why a bonus here for fast delivery

+38 added to your rating, current score is: [+9208](http://www.netbout.com/b/35008?open=rating)
