### ISSUE TITLE
Rultor should try to build with `.rultor.yml` from branch

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/rultor#841]
in https://github.com/teamed/xockets-hadoop-transport/pull/605, we made a change in the project that required the change in the build scripts of that project, including Travis and Rultor. However, the build failed, because Rultor tried to get the `.rultor.yml` from `master` which does not contain the necessary changes.

In this case, we need to change `.rultor.yml` separately, before being able to successfully merge this branch. Let's make it so that it uses `.rultor.yml` from the incoming branch, to save from doing this extra step.

**Comment by yegor256** [comment]
that's exactly how it works now, see https://github.com/yegor256/rultor/issues/802 are you sure it doesn't work for you?

**Comment by carlosmiranda** [comment]
@yegor256 Hmmm, it didn't work when we tried it on that PR. But either way this is a duplicate and I should close it. :)
