### ISSUE TITLE
upgrade to takes 0.14

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#843]

**Comment by alex-palevsky** [comment]
@yegor256 milestone set to `2.0` (correct me if I am wrong)

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by alex-palevsky** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-266eb701

**Comment by alex-palevsky** [comment]
@yegor256 No messages from you above, won't pay for now. If I'm wrong, correct me.
