### ISSUE TITLE
Not merging or deploying

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#845]
Deploying ( taken from http://www.rultor.com/t/3583-97236269 ):
>
+ use_image=yegor256/rultor
+ docker pull yegor256/rultor
time="2015-04-29T00:18:20Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.18/images/create?fromImage=yegor256%2Frultor%3Alatest: dial unix /var/run/docker.sock: permission denied"

Merging: fails with comment
>
com.jcraft.jsch.JSchException: Auth fail

**Comment by yegor256** [comment]
@pinaf yeah, work in progress, thanks for reporting, will be fixed in less than an hour
