### ISSUE TITLE
add log to stdout on container killing

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#850]

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.8`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.8`

**Comment by alex-palevsky** [comment]
@yegor256 milestone set to `2.0` (correct me if I am wrong)

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by alex-palevsky** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-01b16369`

**Comment by alex-palevsky** [comment]
@yegor256 **1 hour** sent to your balance (ID `000-c7dc051a`), many thanks! It took 22 hours and 52 mins.... m=1372, that's why a bonus here for fast delivery... added +60 to your rating, now it is equal to [+8784](http://www.netbout.com/b/35008?open=rating)
