### ISSUE TITLE
Architect names are case-sensitive when GitHub usernames are not

### ISSUE THREAD

**Issue by Winwardo** [yegor256/rultor#851]
You can see a rather funny exchange here
https://github.com/Pzazz/Zing/pull/198#issuecomment-99629247

> > @rultor please merge

> @Winwardo Thanks for your request. @winwardo Please confirm this.

Note I updated my .rultor.yml between it asking me and me then confirming the merge.

**Comment by yegor256** [comment]
@Winwardo definitely a bug on our side, thanks for reporting

**Comment by alex-palevsky** [comment]
@winwardo attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.9`

**Comment by yegor256** [comment]
@Winwardo I believe it's fixed, please check and close the ticket

**Comment by alex-palevsky** [comment]
@yegor256 thanks, paid, **38 mins** to your account, payment ID is `000-a6c90c72`, task took 70 hours and 58 mins to complete

the bonus for fast delivery (m=4258)

+38 added to your rating, at the moment it is: [+8567](http://www.netbout.com/b/35008?open=rating)
