### ISSUE TITLE
Rultor "stop" command issues wrong/confusing messages

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/rultor#864]
In https://github.com/teamed/xockets-layer/pull/359, I tried to stop Rultor but it failed (the PR was merged). It replied with this confusing message:

![image](https://cloud.githubusercontent.com/assets/1917892/8122754/78e893b8-10f1-11e5-8f2e-17ceebee9ffb.png)

Look carefully, I asked it to merge and then tried to issue a `@rultor stop` command. However, it was able to proceed with the merge, but it quoted my "stop" message and said that it was "successful", when it fact it was not (the merge succeeded which meant the stop command failed).

The message is confusing. In this situation, it should say something like:

> @carlosmiranda Sorry, I failed to stop the previous [merge/deploy/release] command, however it [succeeded/failed]. (took x mins.)

And then it should print the error trace if applicable (in case it failed).

**Comment by alex-palevsky** [comment]
@yegor256 please pay attention to this issue

**Comment by alex-palevsky** [comment]
@carlosmiranda attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@carlosmiranda many thanks for the bug report, I added 15 mins to your acc, transaction `59143332`

**Comment by original-brownbear** [comment]
@alex-palevsky this is urgent.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is urgent.

@original-brownbear right, I added "urgent" label

**Comment by alex-palevsky** [comment]
@xupyprmv you may proceed, it's yours

**Comment by xupyprmv** [comment]
@carlosmiranda PR #1046 was merged. Please close this ticket.

**Comment by carlosmiranda** [comment]
@xupyprmv thanks!

**Comment by xupyprmv** [comment]
@alex-palevsky PR #1046 was merged. This ticket is closed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky PR #1046 was merged. This ticket is closed.

@xupyprmv thanks for that

**Comment by alex-palevsky** [comment]
@xupyprmv **30 mins** sent to your balance (ID `AP-51A5220577577171K`), many thanks! It took 117 hours and 33 mins.... +30 to your rating, your total score is [+240](http://www.netbout.com/b/35999?open=rating)
