### ISSUE TITLE
Need a workflow for a restricted branch

### ISSUE THREAD

**Issue by alxn** [yegor256/rultor#866]
This is an idea that supersedes #865.

Issue #675 brought the concept of an `architect:` that can be configured in the [`.rultor.yml`](http://doc.rultor.com/reference.html).

Here, we are not validating the quality of what is being commit, but ordering the scheduling of fixes for a short time.

What is proposed is that a branch can be placed into a locked state, so that only a [`gatekeeper:`](https://en.wikipedia.org/wiki/Gatekeeper) can finally authorise a merge after the architect has approved.

The recommended workflow for this, is that the `gatekeeper:` creates a new issue:

> *Prepare a 0.X.Y hotfix release:*
> Waiting for issues `#22` and `#33`
> `@rultor lock branch=master, gatekeepers are @yegor256 and @alxn`
> `@alxn ok, master is locked, with gatekeepers @yegor256 and @alxn`

Now, when the `architect:` confirms a merge, the gatekeepers are asked for approval.

The gatekeepers will have to manually track whether the PR matches one on the approved list.

When all the tasks are completed:

> *Prepare a 0.X.Y hotfix release:*
> Waiting for issues `#22` and `#33`
> `<snip>`
> `@rultor release tag=0.X.Y`
> `@rultor unlock branch=master`

**Comment by alxn** [comment]
@yegor256 maybe this one is better...

**Comment by yegor256** [comment]
@alxn looks good, thanks, I'll implement it soon

**Comment by alex-palevsky** [comment]
@alxn I added milestone `2.0` to this issue, let me know if there has to be something else

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by yegor256** [comment]
@rultor lock

**Comment by yegor256** [comment]
@rultor lock

**Comment by yegor256** [comment]
@rultor unlock

**Comment by yegor256** [comment]
@rultor unlock

**Comment by yegor256** [comment]
@rultor unlock

**Comment by yegor256** [comment]
@rultor lock users=`@test, @test2`

**Comment by yegor256** [comment]
@rultor lock users=`@test, @test2`

**Comment by yegor256** [comment]
@rultor unlock

**Comment by yegor256** [comment]
@rultor release, tag is `1.53`

**Comment by yegor256** [comment]
@alxn looks like it works. Let's experiment and report bugs separately. This ticket can be closed, I guess.

**Comment by yegor256** [comment]
@alxn I didn't document it :( will do now

**Comment by alxn** [comment]
@yegor256 thanks!

**Comment by alex-palevsky** [comment]
@yegor256 thanks, paid, **45 mins** to your account, payment ID is `000-0ca4032c`, task took 28 hours and 34 mins to complete; there is a bonus for fast delivery (m=1714); +45 to your rating, your total score is [+5920](http://www.netbout.com/b/35008?open=rating)
