### ISSUE TITLE
RFE: Fast forward merges only

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#868]
It would be nice to be able to configure rultor such that it allows ff merges only. (I tried to do a `git config merge.ff=only` in the install step but you seem to do the merge before that.) Some people might also be interested in forcing a merge commit (`--no-ff`).

**Comment by yegor256** [comment]
@sils1297 maybe something like this in `.rultor.yml`:

```yaml
merge:
  fast-forward: true
```

What do you think?

**Comment by sils1297** [comment]
@yegor256 that looks good.

However note that a bool property is not sufficient as there are three modes people will want:

- Forcing a merge commit (thats what GitHub does)
- Doing merge only when needed (default of git and rultor)
- Forcing a fastforward, failing if merge needed (what we want for our project)

I.e. dependent on how you parse the yml you might want to accept `true` `false` and unset value or maybe a bit more verbose `only`, `never`, `sometimes` or so. Git seems to do the former.

Thinking this a bit ahead you might simply allow the user to give rultor a .gitconfig, then he simply can set `merge.ff` to what he wants and at the same time set other needed properties. This provides the most flexibility for your users while they can reuse their existant gitconfig and you simply need to use it.

**Comment by yegor256** [comment]
@rultor release, tag is `1.54`

**Comment by yegor256** [comment]
@sils1297 I think it's working now, check my commits above. Please try and let me know..

**Comment by sils1297** [comment]
Commits look sane, how can I try? I assume rultor hasn't been updated to that yet as your added documentation doesn't appear there.

**Comment by yegor256** [comment]
@sils1297 it's updated already. The documentation is not updated, because of a bug on Github side. But the functionality works. Try it.

**Comment by sils1297** [comment]
works, thanks :)
