### ISSUE TITLE
new version not pushed on github

### ISSUE THREAD

**Issue by msuret** [yegor256/rultor#871]
Hi,
I'm using rultor to release to Maven Central.
Everything works fine, except that the pom.xml with the new version is not pushed on github: It looks like Rultor is resetting and deleting its branch before pushing.
The project is [here](https://github.com/dhatim/business-hours-java) and the log [here](http://www.rultor.com/t/3752-112942428).
What am I doing wrong ?

Thanks a lot !

**Comment by yegor256** [comment]
@msuret I can't understand what's going on... take a look at a similar log: http://www.rultor.com/t/3549-96025647 It's done in this project: https://github.com/jcabi/jcabi-github/releases/tag/0.23 Its tail looks exactly the same as yours, but it does create a new tag in Github.

Maybe it's a temporary issue with Github?

**Comment by msuret** [comment]
@yegor256 You're right, I asked rultor to release it again today and the tag has been created.
But my question was more about how to push the pom.xml after it is updated by the Versions Maven Plugin and before the tag is created.
I worked around this by adding these commands in rultor release script:
 >   git checkout master
    git merge __rultor

Is there a cleaner way to do it ?

**Comment by yegor256** [comment]
@msuret you don't need to do it manually. It happens automatically. You just do `git commit` (already in your script) and rultor automatically tags that branch. So, the changes should **not** be in master, but only in the tag. Here is your tag: https://github.com/dhatim/business-hours-java/tree/1.0.0 As you see, `pom.xml` is modified

**Comment by msuret** [comment]
@yegor256 Thanks a lot! I'm closing the ticket.
