### ISSUE TITLE
Multiple Script Commands are not Parsed

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#872]
After changing my rultor.yml to

```
merge:
  script:
    - "bash .misc/fail_if_HEAD_is_merge.sh"
    - "bash .misc/.deploy.zanata.sh"
```

the `config` command gives me:

> @sils1297 This is how I understand the `.rultor.yml` file in the root directory of this repository:
> 
> ```xml
> <?xml version="1.0" encoding="UTF-8"?>
> <p>
>    <entry key="merge">
>       <entry key="script">
>          <item>bash .misc/fail_if_HEAD_is_merge.sh</item>
>       </entry>
>    </entry>
> </p>
> ```
> 
>  [This page](http://doc.rultor.com/reference.html) explains how to configure it.

Your docs (http://doc.rultor.com/reference.html) state however that this should be possible.

(See https://github.com/coala-analyzer/coala/pull/673 for my discussion with rultor)

**Comment by sils1297** [comment]
Ah sorry, that's my bad. You parse the config of the base branch of course which makes totally sense solely from security view.

Maybe you could state that explicitly in that message to make that clearer.

**Comment by sils1297** [comment]
Opened https://github.com/yegor256/rultor/issues/873 for that.

**Comment by sils1297** [comment]
(Maintainers may want to mark this one as invalid or so.)

**Comment by yegor256** [comment]
@sils1297 I added "invalid" tag
