### ISSUE TITLE
rultor config: Improve message

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#873]
> @sils1297 This is how I understand the `.rultor.yml` file in the root directory of this repository:
> 
> ```xml
> <?xml version="1.0" encoding="UTF-8"?>
> <p>
>    <entry key="merge">
>       <entry key="script">
>          <item>bash .misc/fail_if_HEAD_is_merge.sh</item>
>       </entry>
>    </entry>
> </p>
> ```
> 
>  [This page](http://doc.rultor.com/reference.html) explains how to configure it.

I think this message should contain a hint that it only takes the .rultor.yml from the base branch.

**Comment by alex-palevsky** [comment]
@rultor rultor closed it by mistake, @sils1297 please take a look

**Comment by sils1297** [comment]
> please take a look

I don't get what you want from me, are you aware that the merged commit is by me?

**Comment by yegor256** [comment]
@sils1297 just close this ticket if we're done here. thanks
