### ISSUE TITLE
CI listings in README

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#874]
You do list a bunch of CIs in your README. However they all seem to fail. This probably scares off developers and decreases the trust in your product, the intent of using that stuff is nice but if your master branch isn't stable it's pretty useless isn't it?

**Comment by yegor256** [comment]
@sils1297 sometimes they fail, sometimes they pass. It's more for experiments there, not to add trust to the project. But I see your point. We just have to put more efforts into making these CI systems stable.. Maybe you can help?

**Comment by sils1297** [comment]
I don't have time to help you out fixing your CI, sorry. I can provide a bit of generic advice:

 * reduce it to the minimum, keeping CI stable is a maintenance overhead. Choose one CI for one usecase. Use that.
 * I'd recommend circleci.com as they have very good support and lightning fast build times; you can build in parallel against several versions, take a look at the circle.yml of the coala project for an example of that. (They don't support that natively but the performance boost pays off against travis)
 * Don't support windows if you don't have a reason. Interprocess communication kills all. Plus dependency installation and that stuff. If you do, AppVeyor is the way to go although it's comparatively slow with other services. We have one who thinks windows is important for coala and he's basically full time on finding workarounds for windows. Get's worse with GUIs as there's no such thing like a virtual framebuffer.
 * If you have test coverage, use coveralls and codecov. One of them is cool because it puts comments on PR detailing if even branch coverage goes down, the other is cool for failing the build if statement coverage goees down. Both almost no maintenance overhead.
 * There are services for code quality metrics (we use scrutinizer and codacy for python) which may pay off, I'd suggest not letting them execute the build too if they offer it, maintenance overhead.
 * Build against any version and OS you support.
 * Don't allow any PR to fail anything.
 * I'd seperate the merging checks from CI, i.e. letting builds run on build servers and letting rultor just check their statuses makes the whole process more visible to the single devs. Rultor could be used for things like pushing translation for a web UI (we're trying to do that) instead of a deployment clause in CI for the master branch but the latter is easier to realize as we didn't find a good way to debug rultor yet.
 * Remove failing CI from your readme or add a comment why it fails and fix it fast. (We do that when our hosting services have internal problems only. Otherwise revert causing commits instantly.) Don't scare devs off by you trying to show off  with something that doesn't work. Show them you have a working quality assurance. At least if you want to attract devs with a sense for high quality.

Let me know if you need anything else.

**Comment by sils1297** [comment]
> I don't have time to help you out fixing your CI

Not meant as an insult or so, I'm doing all of this free time.

**Comment by yegor256** [comment]
@sils1297 all this makes perfect sense, many thanks! I will try to improve this situation
