### ISSUE TITLE
RFE: Merge: Add rebase option

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#877]
From https://github.com/yegor256/rultor/issues/870

---

There is however the other usecase for people who don't care so much about that stuff but still want a linear commit history for change tracability (I'm obviously not among them but they exist :)). They will want to have a "rebased merge", which you probably want to do as a parameter for the `merge` command. Something like

```
merge:
  rebase: true  # Rebases before doing the merge
```

which then just does

```
# Wildly assuming pseudo-environment variables you probably don't have in that form
git checkout $(TARGET)
git rebase $(BASE)
git checkout $(BASE)
git merge $(TARGET)
git push origin $(BASE)
```

**Comment by yegor256** [comment]
@sils1297 good idea, thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `1.55`

**Comment by sils1297** [comment]
commit lgtm

**Comment by yegor256** [comment]
@sils1297 should be working now. Please check it out and close the ticket if we're done here

**Comment by sils1297** [comment]
See comment on https://github.com/yegor256/rultor/commit/1659828359225e6191a487af24f1d7abcec51c9f , I tested on https://github.com/sils1297/rultor-test/pull/9 and it doesn't seem to work because you're in a detached head state after checking out so you're not tracking the rebase with your branch.

**Comment by yegor256** [comment]
@rultor release, tag is `1.55.1`

**Comment by yegor256** [comment]
@sils1297 try again pls

**Comment by yegor256** [comment]
@rultor release, tag is `1.55.2`

**Comment by yegor256** [comment]
@sils1297 try now

**Comment by sils1297** [comment]
@yegor256 sorry, that still didn't work. https://github.com/sils1297/rultor-test/pull/13

**Comment by yegor256** [comment]
@sils1297 try a new pull request, this one seems to be merged already: https://github.com/sils1297/rultor-test/pull/13/files

**Comment by sils1297** [comment]
@yegor256 I'm testing using empty commits.

**Comment by yegor256** [comment]
@sils1297 ah... that's another story. let's close this ticket and open a new one, about this bug with empty commits

**Comment by original-brownbear** [comment]
@sils1297 Created the empty commit issue here https://github.com/yegor256/rultor/issues/1016, can you close this unless there is anything left here ? :)

Thanks!
