### ISSUE TITLE
Rultor release command adds quotes to the release tag

### ISSUE THREAD

**Issue by krzyk** [yegor256/rultor#882]
See: http://www.rultor.com/t/4325-115774869
In this release rultor added a single quotes around the release tag and uploaded such jar to the repo.
If you look at the beginning of this log you can see that all enviroment variables passed have additional quote (`'`) added around them:
```
+ vars=('--env=MAVEN_OPTS=-XX:MaxPermSize=256m -Xmx1g' '--env=head='\''git@github.com:teamed/xockets-hadoop-transport.git'\''' '--env=head_branch='\''master'\''' '--env=tag='\''0.3.5'\''')
```

Please remove unnecessary quote around the above variables (tag, head_branch, head).

**Comment by yegor256** [comment]
@krzyk definitely a bug, I'll fix it now

**Comment by yegor256** [comment]
@rultor release, tag is `1.55.5`

**Comment by yegor256** [comment]
@rultor release, tag is `1.55.5`

**Comment by alex-palevsky** [comment]
@krzyk this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@krzyk there is no milestone yet, so I set it to `2.0`

**Comment by alex-palevsky** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `59996403`

**Comment by yegor256** [comment]
@krzyk should be fixed now, please check

**Comment by krzyk** [comment]
@yegor256 it is working now, thanks
