### ISSUE TITLE
col: Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#884]
This is what I found in logs today:

```
Jun 28 16:56:59 www.rultor.com user: [ERROR] 0862cb7 java.lang.Boolean: 
col: Invalid or incomplete multibyte or wide character
```

**Comment by alex-palevsky** [comment]
@yegor256 I tagged this as "bug"

**Comment by alex-palevsky** [comment]
@yegor256 I set milestone here to `2.0`, let me know if it is wrong

**Comment by alex-palevsky** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-75504625`

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.1`

**Comment by original-brownbear** [comment]
@yegor256 this is happening because we're piping output to `col` for example here and have the locale set to UTF-8:
```
@Override
        public InputStream read() throws IOException {
            final Shell shell = new TalkShells(this.xml).get();
            final ByteArrayOutputStream baos = new ByteArrayOutputStream();
            shell.exec(
                String.format(
                    // @checkstyle LineLength (1 line)
                    "dir=%s; (cat \"${dir}/stdout\" 2>/dev/null || echo \"file $file is gone\") | col -b",
                    SSH.escape(this.xml.xpath("/talk/daemon/dir/text()").get(0))
                ),
                new NullInputStream(0L), baos,
                Logger.stream(Level.SEVERE, true)
            );
            return new ByteArrayInputStream(baos.toByteArray());
        }
    }
```

If the output contains invalid utf-8 chars this error is hard to avoided unless we generally pipe Stderr to /dev/null or something ( and we really shouldn't suppress errors here imo :) ).
This should not be resolved in isolation but by a more stable interface to the Docker daemon, all add an issue for and on how to achieve this, for now I'm postponing this as it makes no sense having anyone work on it.

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by yegor256** [comment]
@original-brownbear well, I thought that there are some tools in Linux, which can simply remove that invalid UTF characters from the stream. something like:

```
cat ... | kill-bad-utf8-chars | col -b
```

You think it's impossible to find such tools?

**Comment by original-brownbear** [comment]
@yegor256 no actually that would just be [iconv](https://en.wikipedia.org/wiki/Iconv) :)
Sorry, this was somewhat pointless, converting to UTF-8 should be fine in all cases actually.
Forget I pinged you, yea I think for the time being implementing this with iconv is fine for sure.

**Comment by yegor256** [comment]
@original-brownbear yes, exactly, `iconv`. Let's do it.

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear yep, it is yours, go ahead

**Comment by original-brownbear** [comment]
Fix using iconv + integration test that reproduces the issue added in the PR.

**Comment by original-brownbear** [comment]
@yegor256 for this is merged, can you close this ? :)

**Comment by yegor256** [comment]
@original-brownbear thanks!

**Comment by original-brownbear** [comment]
@alex-palevsky can you handle payment here please and close this for good :) ?

**Comment by alex-palevsky** [comment]
@original-brownbear I added **30 mins** to your account, many thanks for working with the project (AP-3JC31476WM1809223)! The completion time here was 115 hours and 35 mins.... added +30 to your rating, now it is equal to [+368](http://www.netbout.com/b/36646?open=rating)
