### ISSUE TITLE
Rultor is not answering after asking for release

### ISSUE THREAD

**Issue by GilraenBurland** [yegor256/rultor#888]
Hi there,

I am trying to use Rultor in my project https://github.com/GilraenBurland/roster.

I've got an issue https://github.com/GilraenBurland/roster/issues/7 in which I am asking Rultor to release with the tag=`0.1` but nothing is happening.

Asking Rultor for the config is working.

Could you please have a look and tell me what I'm missing?

Regards

**Comment by yegor256** [comment]
@GilraenBurland should be fixed in #889

**Comment by GilraenBurland** [comment]
Thanks, rultor is now answering :)
