### ISSUE TITLE
pom.xml versions still 1.0-SNAPSHOT after release

### ISSUE THREAD

**Issue by GilraenBurland** [yegor256/rultor#891]
Is it correct that the version in the pom.xml of a released tag is still 1.0-SNAPSHOT and not the version of the release?

**Comment by yegor256** [comment]
@GilraenBurland it's not correct and it's probably a bug in your `.rultor.yml` script. can you share it here?

**Comment by GilraenBurland** [comment]
https://github.com/GilraenBurland/roster/blob/master/.rultor.yml

**Comment by yegor256** [comment]
@GilraenBurland did you try to run this locally:

```
mvn versions:set "-DnewVersion=1.0"
```

Does it change your `pom.xml`? I don't think so...

**Comment by GilraenBurland** [comment]
@yegor256 I am doing a `cat pom.xml` at the and to check if the version is set.
A rultor log [here](http://www.rultor.com/t/4426-119277358) shows that the pom version is set to 0.1

**Comment by yegor256** [comment]
@GilraenBurland I don't see any releases created in the repo. No tag, no releases. There is some problem in Github probably. Try to release again.

**Comment by GilraenBurland** [comment]
@yegor256 I released again. pom.xml for tag 0.1 is https://github.com/GilraenBurland/roster/blob/0.1/pom.xml

**Comment by yegor256** [comment]
@GilraenBurland maybe it's because of this bug: https://github.com/yegor256/rultor/issues/892 Let's wait until it's released/fixed and try to release your project again. I'm not sure it's the problem, but let's try...

**Comment by yegor256** [comment]
@GilraenBurland please try to release again

**Comment by GilraenBurland** [comment]
@yegor256 now it's working! Thanks :)

**Comment by yegor256** [comment]
@GilraenBurland thank you for spotting the issue!
