### ISSUE TITLE
rultor encrypt -p user/repo path/to/settings.xml should output settings.xml.asc to $CWD instead of the directory where settings.xml is located

### ISSUE THREAD

**Issue by Suseika** [yegor256/rultor#893]
How to reproduce
```bash
mkdir far_away
vim far_away/settings.xml # Create proper settings.xml rultor would accept
rultor encrypt -p user/repo far_away/settings.xml
```
Expected output: settings.xml.asc in current directory
Actual output: settings.xml.asc in far_away directory

I expect settings.xml.asc to appear in the current directory because it is the standard behavior for unix tools that create a new file and are not provided the explicit location for it, e.g. `wget http://github.com`

**Comment by yegor256** [comment]
@Suseika it's a valid bug, but should be reported here: https://github.com/yegor256/rultor-remote
