### ISSUE TITLE
Docs: Inconsistent naming of $tag

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#894]
In http://doc.rultor.com/basics.html you use `$tag` in the text and `${tag}` in the source samples which is a bit confusing especially for people who avoid bash where possible. What's the real thing to do? Is both possible?

**Comment by sils1297** [comment]
-> Please clear up the docs :)

**Comment by yegor256** [comment]
@sils1297 fixed in 1e9b4be thanks!

**Comment by sils1297** [comment]
@yegor256 so am I right to assume it doesn't make any difference?

**Comment by yegor256** [comment]
@sils1297 yes, it's exactly the same. The brackets are there in order to allow this, for example:

```
${very long and strange variable name}
```
