### ISSUE TITLE
Release: Prerelease or Not

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#895]
How does rultor figure out wether to do a prerelease or a regular one?

**Comment by sils1297** [comment]
If rultor is not doing that it would be cool to get that to some degree configurable, if some handling is there documentation is missing at least IMO.

**Comment by yegor256** [comment]
@sils1297 at the moment rultor is making all releases "pre-", allowing you to decide which one is a regular one and drop the flag manually. make sense?

**Comment by sils1297** [comment]
Yeah, thought so. However the idea of automation is to not having to do
anything manually, right?

2015-07-16 22:38 GMT+02:00 Yegor Bugayenko <notifications@github.com>:

**Comment by yegor256** [comment]
@sils1297 Yes, but in this case it's a personal decision of a project architect. Also, it's good to add some words to the description of a release, when making it "regular". We can't automate this... someone has to do it manually.

**Comment by sils1297** [comment]
@yegor256 depends. I'm a very young maintainer (just making my bachelors degree actually) so I have much to learn but I feel just maintaining a RELEASE_NOTES.md is a fine thing to do, a static text linking to that file would suffice for me, especially since we (and probably many others) use GitHub releases only complementary, i.e. the *real* release is on the Python Package Index.

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.

**Comment by original-brownbear** [comment]
@sils1297 can you close this or is there anything left here ? :)

**Comment by sils1297** [comment]
if you say it's invalid you should close it
