### ISSUE TITLE
Rultor is badly testable

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#897]
This is kind of a usability report: After some time of using rultor I find it is badly testable. It's really luck if it works and you can't test it before it's on master. So every time you have to try it out in a fork or so which is rather cumbersome and you end up not doing it. (After all we're doing software because we like being lazy.)

In the docs you note that it can be tested using that docker image but tbh. that at least doesn't feel very comfortable. Not one of our devs including me has even dared to even try it.

So it would be cool, if one could do a dry-run or so with tthe rultor config which isn't on master. (That means for security you must not expose the rultor ssh key there you probably use to push to prevent somebody to do malicious things from a fork)

**Comment by sils1297** [comment]
...or alternatively make the docker stuff a bit more explicitly while still short so devs actually read it.

**Comment by yegor256** [comment]
@sils1297 can you explain what kind of problem you're solving and why it takes too much time? I mean, give me an example. I didn't understand where exactly is the bottleneck - in rultor config, in Docker config, in Github integration... Give me an example

**Comment by sils1297** [comment]
@yegor256 
Well, let's take a common usecase: I want to use rultor for merging and releasing.

I need to write the release script and somehow test if it works on rultor. If I want to test the merge and release command I needed to make an extra fork for doing this, needed to resync a lot of branches which is cumbersome and errorprone (working with several remotes, would be bad to push on the wrong master with WIP commits).

Programs like git have a `--dry-run` for this, and I think this would be great for rultor: e.g. a rultor merge could simply do `git push --dry-run` and the developer can easily inspect if a config would merge before actually merging it to master. This would rely on https://github.com/yegor256/rultor/issues/802 ...

Get the idea?

**Comment by yegor256** [comment]
@sils1297 yes, this makes sense, but why can't you just run "rultor deploy" a few times, until it works? then, "rultor release 0.0.1" a few times, until it releases, etc. Rultor is a production tool, and testing its scripts is not really what people need in production... For example, you can't "test" Travis scripts. You just run and see the error. If there is an error, you fix it. See the point?

**Comment by original-brownbear** [comment]
@alex-palevsky invalid issue.

**Comment by original-brownbear** [comment]
@sils1297 as explained by @yegor256 , this is not something CI platforms like Travis offer either.
I think the best advice I can give you here for the time being is to have your devs give a glance over https://github.com/yegor256/rultor/blob/master/src/main/resources/com/rultor/agents/req/_head.sh 

This script sets up the folder structure in the container and creates the entry.sh script that is to be run in the container from your provided script.sh and the setting of whether to use the root user or not.
Maybe your devs can simply create a working entry.sh depending on your setting for a project from that script and then run your image with that same command provided in the script?
```
docker run --rm -v "$(pwd):/main" "${vars[@]}" \
    --hostname=docker \
    --memory=6g --memory-swap=16g --oom-kill-disable \
    "--cidfile=$(pwd)/cid" -w=/main \
    --name="${container}" "${image}" /main/entry.sh
```

You can leave out the cidfile part and the naming of the container from the above and this should be very possible to figure out.

I'm afraid it's beyond the scope of Rultor/CI to provide a --dry-run though :/

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.
