### ISSUE TITLE
Decrypt API is confusing

### ISSUE THREAD

**Issue by sils** [yegor256/rultor#899]
This is wrt http://doc.rultor.com/reference.html , section Decrypt

You do expect from your users to add the `repo/` prefix to the file to decrypt. Thats not very obvious, I think we spend 3 manhours to figure that out with several people looking at it.

So first, I'd love it if the documentation could state explicitly that the repo prefix is needed.

Second, your users shouldn't deal with your internal directory structure IMO so I'd recomment removing the need for this prefix. (Which would break the API for existent projects though.)

**Comment by yegor256** [comment]
@sils1297 yeah, make sense... I don't know why it's done like this... let me investigate and fix.

**Comment by alex-palevsky** [comment]
@sils1297 milestone set to `2.0` (correct me if I am wrong)

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by yegor256** [comment]
@sils1297 we will document it better. We need this `repo/` prefix in order to keep "foreign" files outside of the main directory of the project. We'll improve the documentation

**Comment by yegor256** [comment]
@alex-palevsky assign someone else here pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else here pls

@yegor256 I deducted 30 points from your rating

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else here pls

@yegor256 right, I'll try to find someone else for this task

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear got it, someone else will be assigned soon

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#899` is not assigned, can't get performer
