### ISSUE TITLE
yegor256 / rultor docker image isn't open source

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#902]
at least I wasn't able to find the dockerfile. Would be nice if you had an own repo for it so one could file bugs and request environment changes, IMO  that would make sense and ease maintenance for you.

Also it would ease building own docker images and help debugging rultor because one knows how the image was created.

**Comment by yegor256** [comment]
@sils1297 this is a very valid bug, thanks. I thought about this for a long time, maybe it's time to do it...

**Comment by sils1297** [comment]
@yegor256 thanks. :) While we're at it, let me file a few more bugs about your docker image...

**Comment by alex-palevsky** [comment]
@sils1297 since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
@yegor256 it's your task now

**Comment by yegor256** [comment]
@sils1297 I think it's done. The image is here: https://registry.hub.docker.com/u/yegor256/rultor/ Source are in `/src/docker` in this repo. Feel free to submit any changes you want to make to it.

**Comment by sils1297** [comment]
Much better, thanks.

**Comment by alex-palevsky** [comment]
@yegor256 Much obliged! I have added **30 mins** to your account in payment "000-25e40374", 90 hours and 32 mins spent... +30 added to your rating, current score is: [+9355](http://www.netbout.com/b/35008?open=rating)
