### ISSUE TITLE
pathspec '%s' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by AbdealiJK** [yegor256/rultor#905]
I was trying to use rultor on my fork of coala, so I made a branch `ajk/master` which had been updated with coala's `master` and I was merging the branch `ajk/ci` into it.

I get the following log : http://www.rultor.com/t/4558-122687101
and here is the PR : https://github.com/AbdealiJK/coala/pull/7

**Comment by AbdealiJK** [comment]
Seems to be because I tried to merge into `ajk/master` ... when i merge into `master` it works

**Comment by yegor256** [comment]
@AbdealiJK hm... interesting.. I will look into it soon

**Comment by alex-palevsky** [comment]
@abdealijk I will find a developer for the task soon...

**Comment by alex-palevsky** [comment]
@abdealijk since the ticket has no milestone I set it to 2.0

**Comment by original-brownbear** [comment]
@alex-palevsky this is a duplicate of https://github.com/yegor256/rultor/issues/935

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a duplicate of https://github.com/yegor256/rultor/issues/935

@original-brownbear sure, thanks, I added "invalid", "duplicate" labels to it

**Comment by alex-palevsky** [comment]
@abdealijk I am closing it
