### ISSUE TITLE
default python encoding is ascii

### ISSUE THREAD

**Issue by AbdealiJK** [yegor256/rultor#907]
Currently, the filesystem encoding (according to python atleast) is ascii.

```
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.getfilesystemencoding()
'ascii'
>>> 
```

It would be good to change this to UTF or give an option to set it as UTF in the config file.

Some packages fail to install if it isn't UTF

**Comment by AbdealiJK** [comment]
I was able to fix this by:
```
export LANG=en_US.UTF-8
locale-gen en_US.UTF-8
```

**Comment by sils1297** [comment]
See https://github.com/coala-analyzer/rultor-python/commit/9fd9a9d96ff1336c873b201a4c0b23980c8a9147

**Comment by yegor256** [comment]
@AbdealiJK I think it's fixed already, see https://github.com/yegor256/rultor/blob/master/src/docker/Dockerfile

**Comment by AbdealiJK** [comment]
Yep, thanks

-----Original Message-----

**Comment by yegor256** [comment]
@AbdealiJK please, close the ticket
