### ISSUE TITLE
rultor merge failed: "mkdir: cannot create directory ‘/home/r/.ssh’: File exists" 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#910]
rultor merge failed with the message
> mkdir: cannot create directory ‘/home/r/.ssh’: File exists" 

see details here http://www.rultor.com/t/4607-124227081

**Comment by yegor256** [comment]
@dmzaytsev I believe it's fixed already. can you try again?

**Comment by dmzaytsev** [comment]
@yegor256 yes, I merged it
Thanks!
