### ISSUE TITLE
Rultor installation wants to override rake

### ISSUE THREAD

**Issue by tmoreira2020** [yegor256/rultor#913]
I'm getting the following message during rultor's installation. 
```
 rake's executable "rake" conflicts with /usr/bin/rake
 Overwrite the executable? [yN]
```
This is the result of uname -a

```
Darwin Thiagos-MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```
and rake's version
```
rake, version 0.9.6
```

Not sure if I should accept the overwrite request. Is there a workaround?

**Comment by yegor256** [comment]
@tmoreira2020 what is "rultor installation"? what exactly are you doing? how can I reproduce it?

**Comment by tmoreira2020** [comment]
@yegor256 When I try to run this command: sudo gem install rultor

**Comment by tmoreira2020** [comment]
Forgot to post ruby's version
```
ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by yegor256** [comment]
@tmoreira2020 ah, right, could you please post this ticket here: https://github.com/yegor256/rultor-remote (it's Ruby gem repo)

**Comment by tmoreira2020** [comment]
Ok, done!

https://github.com/yegor256/rultor-remote/issues/8

Thanks
