### ISSUE TITLE
Add on option to not close parent tickets

### ISSUE THREAD

**Issue by Suseika** [yegor256/rultor#914]
When a pull request is merged by rultor, rultor always closes the parent issue, then a project manager reopens it and reports to ticket author that "rultor closed this issue by mistake". In all the cases I've seen rultor shouldn't have closed the parent issue, can we do something about that? Maybe introduce a configuration parameter for rultor that disables closing the parent issue?

**Comment by yegor256** [comment]
@Suseika Github is doing this, not rultor :( We can't do anything about it. This happens when one of your commits say `close #123` or something like that

**Comment by Suseika** [comment]
How about we establish a policy on how should one link to the parent issue in commit messages?

https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

Maybe writing "For #12345678" instead of "Fixes #12345678" would do.

**Comment by Suseika** [comment]
@yegor256 How about we establish a policy on how should one link to the parent issue in commit messages?

https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

Maybe writing "For #12345678" instead of "Fixes #12345678" would do.

**Comment by Suseika** [comment]
@yegor256 The problem is that waiting for the issue to be reopened by a project manager takes additional time. If commits don't close issues, that time would not be wasted.

**Comment by yegor256** [comment]
@Suseika how can we establish such a policy? we can't control how programmers label their commits :(
