### ISSUE TITLE
 Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign

### ISSUE THREAD

**Issue by pavanputhra** [yegor256/rultor#915]
I tried your tutorial at http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html , I am unable to release software.

It is showing following error

```
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project smsowl-client: Exit code: 2 -> [Help 1]
```

You can see rultor's complete error message here https://github.com/mahoujas/smsowl-java/issues/1

Please help me with this issue.

**Comment by yegor256** [comment]
@pavanputhra looks like you don't have `.gpg` key files in your repo, according to the log

**Comment by pavanputhra** [comment]
@yegor256 Isn't following three files enough which contains encrypted key.
1. pubring.gpg.asc
2. secring.gpg.asc
3. settings.xml.asc
(Out put of  rultor encrypt -p mahoujas/smsowl-java file)

Should I include any other files as well?

**Comment by yegor256** [comment]
@pavanputhra files are in place. The problem is that your gpg-maven-plugin is not configured to find them in the current directory: https://github.com/mahoujas/smsowl-java/blob/master/pom.xml#L69-L81 You have to set `gpg.home` property on command line or in your `settings.xml`

**Comment by pavanputhra** [comment]
I have specified `gpg.homedir` as specified in tutorials. Following is the file.

```xml
<settings>
  <profiles>
    <profile>
      <id>smsowl-client</id> <!-- give it the name of your project -->
      <properties>
        <gpg.homedir>/home/r</gpg.homedir>
        <gpg.keyname>A0B92F96</gpg.keyname>
        <gpg.passphrase>******</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
  <servers>
    <server>
      <id>oss.sonatype.org</id>
      <username>*****</username>
      <password>*****</password>
    </server>
  </servers>
</settings>
```

**Comment by yegor256** [comment]
@pavanputhra and? works?

**Comment by pavanputhra** [comment]
@yegor256 Nope same issue. :(

**Comment by yegor256** [comment]
@pavanputhra you're doing something wrong, not according to the tutorial. give me more information, I will try to help

**Comment by pavanputhra** [comment]
@yegor256 Now I tried to do every thing afresh as in tutorial. This time instead of doing manual configuration I have used  jcabi-parent as parent.

It seems build is happening successfully. But at the last stage it gives following output

```
+  git commit -am 1.0.0
On branch __rultor
nothing to commit, working directory clean
```

Full log it at.

 http://www.rultor.com/t/4678-128294944

**Comment by yegor256** [comment]
@pavanputhra that is because `mvn versions:set` doesn't change anything in your project, but it has to. Your `pom.xml` has to have `1.0-SNAPSHOT` version to be set.

**Comment by pavanputhra** [comment]
@yegor256 Now getting `COMPILATION ERROR` for same source code which was compiling successfully last time! Am I doing something wrong?

**Comment by yegor256** [comment]
@pavanputhra this is something in your project :) try to compile it locally in Docker image we're using. If you need my help, post more information in your messages. Don't expect me to guess what's wrong in your project :) if you need help, explain the problem properly

**Comment by pavanputhra** [comment]
@yegor256 Got to work on this project after a long time. I am glad that I could able to figure out last issue.

Now build is successful and seems like it has uploaded to repository 

```
....
Uploading: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/mahoujas/smsowl/smsowl-client/maven-metadata.xml
Uploaded: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/mahoujas/smsowl/smsowl-client/maven-metadata.xml (312 B at 0.5 KB/sec) 
[INFO]
------------------------------------ [INFO] BUILD SUCCESS [INFO] ---------
....

```

But, instead of success message I get "failure" with following messge.

```
....
Deleted branch __rultor (was dec2495). 
+ git push --all origin 
ERROR: Permission to mahoujas/smsowl-java.git denied to rultor.
fatal: Could not read from remote repository.
....
```

Seeing above log, I figured out that rultor needs write permission to my repo, if am not wrong. With this assumption I have invited rultor for my repo. Is my assumption right? Is accepting of invite by rultor automatic?

**Comment by yegor256** [comment]
@pavanputhra yes, you're right, you have to invite rultor to your repo. We accept such invitations manually. I believe it was accepted a few hours ago... Please verify

**Comment by pavanputhra** [comment]
@yegor256 Yes, it was verified and rultor ran successfully. Thanks for building rultor. :)

As first time maven dev I would like to know, what is average time it takes for published jar to appear on maven central? Is there any immediate way to confirm jar is published to sonotype?

**Comment by yegor256** [comment]
@pavanputhra it takes up to 15 minutes, according to my experience... welcome to Rultor :)

**Comment by pavanputhra** [comment]
@yegor256 Thanks :)

I feel some is not right in my configuration. Rultor ran successfully but i couldn't find my jar in http://search.maven.org/

As in the blog I had following settings in .rultor.yml for release. It ran successfully, but not released.

```yml
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml
```

So I logged in to https://oss.sonatype.org/ and checked staging repo. I found following errors

1. javadocs wasn't uploaded
2. source wasn't uploaded.
3. asc file for pom and jar wasn't uploaded.

So I visited https://github.com/jcabi/jcabi/blob/master/.rultor.yml to study your rultor.yml file. I tried to run new script one by one, but following line didn't work.

```bash
mvn clean deploy -Psonatype -Pjcabi --errors --settings ../settings.xml
```


I get following error, which basically says 404 resource not found. Interesting thing is first time it makes request to `GET /service/local/staging/repository/commahoujas-1013 HTTP/1.1` it succeeds with 200 and xml response, but second time it fails with following output.


```log
[DEBUG] >> GET /service/local/staging/repository/commahoujas-1013 HTTP/1.1
[DEBUG] >> Content-Type: application/xml; charset=UTF-8
[DEBUG] >> Accept: application/xml; charset=UTF-8
[DEBUG] >> Host: oss.sonatype.org:443
[DEBUG] >> Connection: Keep-Alive
[DEBUG] >> User-Agent: Nexus-Client/2.9.1-02
[DEBUG] >> Authorization: Basic ********************
[DEBUG]  << "HTTP/1.1 404 Not Found[\r][\n]"
[DEBUG]  << "Content-Type: application/xml; charset=UTF-8[\r][\n]"
[DEBUG]  << "Date: Fri, 02 Oct 2015 07:49:19 GMT[\r][\n]"
[DEBUG]  << "Server: nginx[\r][\n]"
[DEBUG]  << "Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept[\r][\n]"
[DEBUG]  << "X-Content-Type-Options: nosniff[\r][\n]"
[DEBUG]  << "X-Frame-Options: SAMEORIGIN[\r][\n]"
[DEBUG]  << "Content-Length: 147[\r][\n]"
[DEBUG]  << "Connection: keep-alive[\r][\n]"
[DEBUG]  << "[\r][\n]"
[DEBUG] Receiving response: HTTP/1.1 404 Not Found
[DEBUG] << HTTP/1.1 404 Not Found
[DEBUG] << Content-Type: application/xml; charset=UTF-8
[DEBUG] << Date: Fri, 02 Oct 2015 07:49:19 GMT
[DEBUG] << Server: nginx
[DEBUG] << Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
[DEBUG] << X-Content-Type-Options: nosniff
[DEBUG] << X-Frame-Options: SAMEORIGIN
[DEBUG] << Content-Length: 147
[DEBUG] << Connection: keep-alive
[DEBUG] Connection can be kept alive indefinitely
[DEBUG] Authentication succeeded
[DEBUG]  << "<nexus-error>[\n]"
[DEBUG]  << "  <errors>[\n]"
[DEBUG]  << "    <error>[\n]"
[DEBUG]  << "      <id>*</id>[\n]"
[DEBUG]  << "      <msg>No such repository: commahoujas-1013</msg>[\n]"
[DEBUG]  << "    </error>[\n]"
[DEBUG]  << "  </errors>[\n]"
[DEBUG]  << "</nexus-error>"
```

**Comment by yegor256** [comment]
@pavanputhra your `pom.xml` must generate all sonatype-required artifacts. I would recommend just use [jcabi-parent](http://parent.jcabi.com) as a parent POM and you will be fine

**Comment by pavanputhra** [comment]
@yegor256 yes i have included it as parent I tested with version 37

**Comment by yegor256** [comment]
@pavanputhra than you need help with your Maven POM configuration, not with rultor. Rultor is just doing what you tell: `mvn clean install`. How your POM works - it's a different story :)

**Comment by pavanputhra** [comment]
@yegor256 Yes, you are right. I know rultor executes cmd given at it. In fact error output shown above are by running maven in local machine - no rultor involved.

 I think this error is due to jcabi-parent parent POM. So, I thought you would be able to help me better as you are the author of jcabi-parent. (Or should I create issue in that repo?)

Brief about my POM. It contains only artifact coordinate details and 2 dependancy httpclient & gson, thats it. Even after jcabi-parent failed to upload to Sonatype, I could able to upload jars manually and get published to Maven Central.

**Comment by yegor256** [comment]
@pavanputhra yes, indeed, if you think that the problem is in jcabi-parent, submit an issue there. But keep in mind that there are many projects that use jcabi-parent and have no issues with releasing to Maven Central. for example this one: https://github.com/jcabi/jcabi-http

**Comment by tvd12** [comment]
Hi @yegor256,

How long rultor.com response my invitation (collaborator)?
