### ISSUE TITLE
Upload Assets To Github Release

### ISSUE THREAD

**Issue by jeromebridge** [yegor256/rultor#920]
Is there a way to upload assets to the Github release after it is created?  Secondary question: is there a way to update the release to `latest` after it is created?

**Comment by yegor256** [comment]
@jeromebridge we'll be able to attache assets/artifacts soon, see https://github.com/yegor256/rultor/issues/662 Would be great if you create a separate issue for the "latest" feature, we'll implement it.

**Comment by jeromebridge** [comment]
Thanks @yegor256 .  This is very neat tool.
