### ISSUE TITLE
Mark Release As "Latest"

### ISSUE THREAD

**Issue by jeromebridge** [yegor256/rultor#921]
Releases are created as `pre-release` currently.  Can we add the ability to mark them as `latest` through Rultor?

**Comment by yegor256** [comment]
@jeromebridge something like this, in `.rultor.yml`:

```yaml
release:
  pre: false
```

By default it's set to `true`, as it works now. Make sense?

**Comment by jeromebridge** [comment]
Yeah

**Comment by alex-palevsky** [comment]
@jeromebridge I will find a developer for the task soon...

**Comment by alex-palevsky** [comment]
@jeromebridge since there is no milestone yet I set it to "2.0"

**Comment by alex-palevsky** [comment]
@maurezen this is your task now, help us

**Comment by maurezen** [comment]
@alex-palevsky created pr #929

**Comment by alex-palevsky** [comment]
> @alex-palevsky created pr #929 

@maurezen OK thanks

**Comment by alex-palevsky** [comment]
@maurezen it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, at the moment it is: [-74](http://www.netbout.com/b/35102?open=rating)

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear thanks, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear I will ask somebody else to pick this up

**Comment by yegor256** [comment]
@maurezen this feature works now
