### ISSUE TITLE
Kill command for the container with current build

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#926]
It would be really useful to have this feature.
```@rultor kill``` or something like that.

Sometime build is obviously stuck (due to bug), but the is no way to stop it ... just wait for ~2h :(

**Comment by yegor256** [comment]
@longtimeago try `@rultor stop`

**Comment by longtimeago** [comment]
@yegor256 maybe you should update doc with this command?
http://doc.rultor.com/commands.html

**Comment by yegor256** [comment]
@longtimeago right, updated at 277024a

**Comment by longtimeago** [comment]
@yegor256 thanks

**Comment by longtimeago** [comment]
@yegor256 stop doesn't work in case when container is stuck.
Maybe, we could add a possibility to kill the container related to some project to the architect of that project?
See the reason https://github.com/teamed/xockets-hadoop-transport/pull/918

**Comment by yegor256** [comment]
@longtimeago `stop` is killing the container, check this: https://github.com/yegor256/rultor/blob/1.57.1/src/main/resources/com/rultor/agents/daemons/stop.sh

**Comment by yegor256** [comment]
@longtimeago maybe it doesn't work (for some reason), but it does do `docker stop`...

**Comment by longtimeago** [comment]
@yegor256 docker stop is not a kill 
http://superuser.com/questions/756999/whats-the-difference-between-docker-stop-and-docker-kill

**Comment by yegor256** [comment]
@longtimeago OK, let's try them both, see 0ce9b49

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.2`

**Comment by longtimeago** [comment]
@yegor256 thank you! Will check it

**Comment by yegor256** [comment]
@rultor  release, tag is `1.57.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.2`
