### ISSUE TITLE
Teamed.io icon is not shown on the Rultor's index page

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#928]
Teamed.io icon is not shown on the Rultor's index page
![screenshot from 2015-09-02 13 23 35](https://cloud.githubusercontent.com/assets/1388994/9628770/4ba98de2-5176-11e5-873f-cd4025affd56.png)

**Comment by yegor256** [comment]
@longtimeago works for me... are you sure?

**Comment by longtimeago** [comment]
@yegor256 arg ... shit .. it's because of our corporate proxy ... sorry for wasting your time :(
