### ISSUE TITLE
sudo: command not found 

### ISSUE THREAD

**Issue by nicofr69** [yegor256/rultor#931]
To allow a Gradle build, I added 
- sudo apt-get install gradle-2.4
into the install section of .rultor.yml
https://github.com/LibGdxCiSample/test/blob/master/.rultor.yml
and get from "@rultor merge" the error message
"/home/r/script.sh: line 7: sudo: command not found"

Any idea what to change?
Is it a rultor bug, or an error in my YAML file?

Thanks,
Nikolas

PS: I already tried 
- "sudo apt-get install gradle-2.4"
but it didn't work neither

**Comment by yegor256** [comment]
@nicofr69 are you sure you have `sudo` installed in `ubuntu:12.10` Docker image?

**Comment by nicofr69** [comment]
Hello Yegor,

 

No, not sure at all.

I won’t mind another Ubuntu image/version, if it helps.

What should I use instead of

 

docker:

  image: "ubuntu:12.10"

 

Best regards,

Nikolas

 

De : Yegor Bugayenko [mailto:notifications@github.com] 
Envoyé : vendredi 11 septembre 2015 12:26
À : yegor256/rultor
Cc : nicofr69
Objet : Re: [rultor] sudo: command not found (#931)

 

@nicofr69 <https://github.com/nicofr69>  are you sure you have sudo installed in ubuntu:12.10 Docker image?

**Comment by yegor256** [comment]
@nicofr69 just remove the definition of the image. The default one will be used, which is based on Ubuntu 14.04

**Comment by yegor256** [comment]
@nicofr69 what is the status here? works?

**Comment by nicofr69** [comment]
@yegor256  The build passed, and merge into master works. You can close this issue, thanks a lot.
