### ISSUE TITLE
EndsDaemon.java:63-64: Refactor this class to use...

### ISSUE THREAD

**Issue by alex-palevsky** [yegor256/rultor#934]
Puzzle `567-359f8c66` in `src/main/java/com/rultor/agents/daemons/EndsDaemon.java:63-64` has to be resolved: Refactor this class to use less objects and remove checkstyle exception above.... The puzzle was created by Yegor Bugayenko on 18-Sep-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alex-palevsky** [comment]
@yegor256 I set the milestone to 2.0 since there is nothing set yet

**Comment by original-brownbear** [comment]
Suggested refactoring here #1004 :)

**Comment by alex-palevsky** [comment]
@original-brownbear The issue should be closed..
