### ISSUE TITLE
Rultor errors out while checking out branch

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#935]
This occurred on http://www.rultor.com/t/5216-142002718 and my *guess* would be that this happens because the source branch on my fork has the same name than the target branch.

**Comment by alex-palevsky** [comment]
@yegor256 please pay attention to this issue

**Comment by sils1297** [comment]
Actually it isn't related to the fork branch being the same as the base one. Maybe it's the dot in the branch name, another failure: http://www.rultor.com/t/5246-143065979

**Comment by yegor256** [comment]
@sils1297 it's a bug in rultor. The problem is that you have branch `2.x-maintenance` in your fork, which hides a branch with the same name in the destination repository. If you delete this branch from your fork, everything will just work fine.

**Comment by yegor256** [comment]
@sils1297 I think this should do the fix: 8bedf9e

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.4`

**Comment by yegor256** [comment]
@sils1297 what do you think? works now?

**Comment by sils1297** [comment]
@yegor256 we've stopped using rultor because I can't expose the team to too much testing right now as we're stil forming the team and the policies. Testing this under production circumstances may take a while.

**Comment by yegor256** [comment]
@sils1297 no problem. I think you can close the ticket, since (I believe) the problem is solved. If you experience it again, you can always open a new ticket.

**Comment by sils1297** [comment]
The commit was reverted so this bug is up and open again, right?

**Comment by alex-palevsky** [comment]
@sils1297 there is no milestone yet, so I set it to `2.0`

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now

**Comment by yegor256** [comment]
@sils1297 that's right, it's still a bug

**Comment by yegor256** [comment]
@alex-palevsky assign someone else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 deducted 30 from your rating :(

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 someone else will help in this task, no problem at all

**Comment by alex-palevsky** [comment]
@jimdeanspivey this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by original-brownbear** [comment]
@jimdeanspivey  how's it going with this? Are you working/planning to work on this issue? 
It's been 7 days since you were assigned to it and an issue of some importance and stuck for some time now as you can see.
I don't think it would benefit anyone if this timed out needlessly again.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear done, the task is yours, go ahead

**Comment by original-brownbear** [comment]
@sils1297 fix for this has been merge in #1034, can we close here ? :)

**Comment by sils1297** [comment]
if you have a confirmed fix why not?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-29 22:53 GMT+01:00 Armin Braun <notifications@github.com>:

**Comment by original-brownbear** [comment]
@sils1297 I see no reason why not, it's simply policy to ask the person who created the issue to close it :)

**Comment by sils1297** [comment]
/me dislikes the policy as this'll keep him from filing potentially helpful bugs for you because at the end he actually has to invest time again.

**Comment by original-brownbear** [comment]
@alex-palevsky can you close this one in my agenda please :) ?

**Comment by alex-palevsky** [comment]
@original-brownbear **1 hour** added to your account (payment number `AP-6EV75314K3469290X`), many thanks for your contribution! 17 hours and 49 mins spent here.; the bonus for fast delivery (m=1069); +60 to your rating, your total score is [+534](http://www.netbout.com/b/36646?open=rating)
