### ISSUE TITLE
rultor merge behaves very weird

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#938]
Sorry for the bad title, but please look at this conversation, beginning from the rultor commands:

https://github.com/coala-analyzer/coala/pull/966

As you see there are three rultor merges on the same data and *all three yield different results*! I'd love it if @yegor256 could take a deep look - there might be several underlying issues here, I'd see two right now:

1. There seem to be connectivity issues with your server, i.e. an issue with the rultor as a service, not necessarily the software.
2. Rultor didn't merge our stuff and performed everything in detached head mode again.

The second issue *might be* because of https://github.com/yegor256/rultor/commit/8bedf9ea1d85439a74e83c327a2ddb026af83b42 , I don't know.

I don't want to assault anyone with the following, if anyone feels this way I'm truly sorry. I'll try to remain factual and constructive.

The truth is that this is not the first time the second issue occurred and I do keep failing to understand why you seem to keep actually releasing stuff that you've never properly tested. An issue like this is really avoidable, after all rultor *is a quality assurance product*.

Rultor is the most often breaking component in our workflow and it takes a long time to get it set up on top. With all the love for the concept you promote this is *really really bad*, we as a team devote our free time to open source (and we do appreciate the free service you offer.) Time is the most valuable asset we have and there is no justification for spending too much of it with telling you about obvious bugs that could've been avoided by very simple things:

- Properly unit tested code.
- Actually reviewing code before merging it to master or even *thinking* about releasing it and shipping it to many users to production. (I'm also looking at you, [Commit History](https://github.com/yegor256/rultor/commits/master)!)
- Setting up a test instance for people wanting to test new features maybe?

I hope this helps a bit and I'd love seeing you increasing tests, setting up proper review and/or a test instance to actually bring some stability to rultor.

**Comment by yegor256** [comment]
@sils1297 don't worry, you're not assaulting anyone :) your concerns are very valid, we definitely don't have enough tests in the projects and we do fail in production, very often. We'll pay more attention to quality. In the mean time, let's try to resolve this issue you're having. I will try to analyze it now...

**Comment by yegor256** [comment]
@sils1297 I reverted the change recently introduced (8bedf9ea1d85439a74e83c327a2ddb026af83b42). You're right, they make merging impossible

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.5`

**Comment by sils1297** [comment]
@yegor256 many thanks. As I said those will probably turn out as several issues and I'd recommend opening new ones for each of them as the investigation reveals them, closing this "investigation" bug in the end.

**Comment by original-brownbear** [comment]
@sils1297 as far as I can tell this ticket is being handled in two existing tickets now and the "investigation" part of things is finished as far as I can tell :)

https://github.com/yegor256/rultor/issues/942 deals with the first issue I can see in your ticket [here](https://github.com/coala-analyzer/coala/pull/966).

https://github.com/yegor256/rultor/issues/935 deals with the git (detached head mode) issue and is being handled now too.

The third issue ( error 500 ) I could see [here](https://github.com/coala-analyzer/coala/pull/966#issuecomment-143503085) does not look like a Rultor issue to me, but coming from a server (https://pypi.python.org I think), your build communicates with returning a 500 response.

Unless you think I missed something in the above (and hence making the investigation incomplete yet :)), could you please close this?
Thanks!

**Comment by sils1297** [comment]
> The third issue ( error 500 ) I could see here does not look like a Rultor issue to me, but coming from a server (https://pypi.python.org I think), your build communicates with returning a 500 response.

That is correct, sorry for raising that here.

About what issues are behind this I don't know , assuming you've got this covered I'm just closing this.
