### ISSUE TITLE
Unexpected error while merge jcabi-github issue

### ISSUE THREAD

**Issue by pecko** [yegor256/rultor#940]
While merge the PR https://github.com/jcabi/jcabi-github/pull/1162, rultor fails with this error:

```
/var/lib/gems/1.9.1/gems/pdd-0.15/lib/pdd/source.rb:144:in `rescue in puzzles': ["in /home/r/repo/src/main/java/com/jcabi/github/Notification.java", #<PDD::Error: Suspicious TODO in line #41>] (PDD::Error)
```

The src/main/java/com/jcabi/github/Notification.java has not changed since January 26 - https://github.com/jcabi/jcabi-github/pull/985 (commit https://github.com/jcabi/jcabi-github/commit/c3bac3a3e0c5e8a972bc8f61ffff4e6e719081bf)

**Comment by yegor256** [comment]
@pecko it is not a bug in rultor, but may be a problem with PDD tool: https://github.com/teamed/pdd

**Comment by yegor256** [comment]
@pecko but it doesn't look like a bug to me. Just the line of code contains incorrect "todo". Just fix it and everything will be fine.

**Comment by pecko** [comment]
@yegor256 

I'm wasnt sure because this line is in src/main/java/com/jcabi/github/Notification.java has not changed since January 26.
Since https://github.com/jcabi/jcabi-github/issues/920 is closed, I will remove todo. Is it OK?

**Comment by pecko** [comment]
@yegor256 

I have changed the commit. It is fixed instead of removed. Please see https://github.com/jcabi/jcabi-github/issues/932#issuecomment-143796385

**Comment by yegor256** [comment]
@pecko yes, you did it right. It's better to fix than remove. The problem is that jcabi-github is using **the latest** version of PDD. And this extra check was introduced in PDD just recently, see https://github.com/teamed/pdd/issues/42

**Comment by pecko** [comment]
@yegor256 

Now, rultor returns two failures as first time :(
Would we ignore that?

**Comment by pecko** [comment]
I'm wrong. These failures are new:

```
{"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}>) out of org.hamcrest.MatcherAssert#assertThat[20] in 144ms Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.679 sec <<< FAILURE! - in com.jcabi.github.RtReleaseAssetsITCase
```
