### ISSUE TITLE
Google search is showing rultor title wrong

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#945]
This doesn't seem right:

<img width="767" alt="screen shot 2015-10-18 at 7 46 29 pm" src="https://cloud.githubusercontent.com/assets/245435/10566858/ff742f5c-75d0-11e5-9240-7d2746d4dffd.png">

Should't it show something like "Rultor: DevOps Team Assistant"?

**Comment by alex-palevsky** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@caarlos0 definitely a bug, caused by https://github.com/yegor256/takes/issues/414

**Comment by yegor256** [comment]
@rultor release, tag is `1.57.12`

**Comment by yegor256** [comment]
@caarlos0 it'll be fixed soon, thanks for reporting
