### ISSUE TITLE
README file: description for What Is Rultor? missing

### ISSUE THREAD

**Issue by niinat** [yegor256/rultor#948]
Problem: Description for What Is Rultor? on the product specification is missing.
https://github.com/niinat/rultor/blob/master/README.md

**Comment by niinat** [comment]
@rultor hello

**Comment by niinat** [comment]
Suggested solution: Add description "Rultor is a solution that helps DevOps teams automate merge, deploy and release routine operations." 
Comment: I might find a better term for "solution" after learning more about Rultor, but would use it for now.

**Comment by yegor256** [comment]
@alex-palevsky role is SA here

**Comment by alex-palevsky** [comment]
@niinat I am aware of the task, give me some time to find a developer...

**Comment by alex-palevsky** [comment]
@niinat I added milestone `2.0` to this issue, let me know if there has to be something else

**Comment by niinat** [comment]
Not being fully familiar with the process yet, may I double check the next step here. Since this ticket has been labeled as SA, next point of action is for me to suggest a solution (see the suggested text/description in an earlier comment above), which then goes to DEV to be reviewed?

**Comment by yegor256** [comment]
@niinat nope, your job is done here. You reported a problem and another SA will fix it and will present a fix to you. You will close the ticket, if you like the solution. That's it. Implementation is a different story and you won't be involved there.

**Comment by niinat** [comment]
Got it! Thanks!

**Comment by alex-palevsky** [comment]
> @alex-palevsky role is SA here

@yegor256 OK, role is set to SA

**Comment by alex-palevsky** [comment]
@niinat thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-5XT95471GC427790F`

**Comment by alex-palevsky** [comment]
@sargisbudaghyan can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by sargisbudaghyan** [comment]
@alex-palevsky I have done the task and please review it. Also I guess I was right that I have used the following URL in order to come up with "What is Rultor" section of README.md file. 

If I need to write something in more details please let me know I will handle it.

Thanks.

**Comment by alex-palevsky** [comment]
@sargisbudaghyan the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/35952?open=rating)

**Comment by sargisbudaghyan** [comment]
@alex-palevsky I will finish it today.

**Comment by sargisbudaghyan** [comment]
@alex-palevsky I have finished it. @yegor256 Could you please review it once more? https://github.com/sargisbudaghyan/rultor/commit/8b868623545fa805c0b3c7b60527e0b4f5f283fc

**Comment by yegor256** [comment]
@sargisbudaghyan such a message should be posted to the pull request. Here it doesn't make sense. There is nothing to review here.

**Comment by alex-palevsky** [comment]
> @alex-palevsky I will finish it today.

@sargisbudaghyan ok thanks

**Comment by alex-palevsky** [comment]
> @alex-palevsky I have finished it. @yegor256 Could you please review it once more? https://github.com/sargisbudaghyan/rultor/commit/8b868623545fa805c0b3c7b60527e0b4f5f283fc

@sargisbudaghyan address your comments to the reviewer, he will work with you to close the ticket

**Comment by sargisbudaghyan** [comment]
@alex-palevsky But I have finished the task. I am waiting it to be reviewed? What else I can do?

**Comment by sargisbudaghyan** [comment]
@alex-palevsky However, you can reassign the task. For the rest of tasks I will be more careful and will do everything on time. And this time I guess I have messed up some branches.

**Comment by alex-palevsky** [comment]
@sfarley85 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by sfarley85** [comment]
@niinat @alex-palevsky I have submitted a pull request to the forked niinat branch with proposed changes. Please review and let me know if anything additional is needed, or close the ticket if the changes are correct. Thanks!

**Comment by niinat** [comment]
I have reviewed and approved the latest version and happy to close the ticket. @alex-palevsky, please confirm you're happy too before I do so. Thanks!

**Comment by niinat** [comment]
Since there is no additional comments I approve and close the ticket.

**Comment by alex-palevsky** [comment]
@sfarley85 I just added **30 mins** to your account, many thanks for your contribution (AP-45X3296310437900E).. 118 hours and 38 mins spent here

+30 added to your rating, current score is: [+60](http://www.netbout.com/b/35863?open=rating)
