### ISSUE TITLE
README file: Description for What Problem Does Rultor Solve? is missing

### ISSUE THREAD

**Issue by niinat** [yegor256/rultor#949]
Problem: Description for the section "What Problem Does Rultor Solve?" on the product specification is missing.
https://github.com/niinat/rultor/blob/master/README.md
Solution: in progress

**Comment by yegor256** [comment]
@alex-palevsky role is SA here

**Comment by alex-palevsky** [comment]
@niinat we will find someone to do this task, soon

**Comment by alex-palevsky** [comment]
@niinat I added milestone `2.0` to this issue, let me know if there has to be something else

**Comment by alex-palevsky** [comment]
> @alex-palevsky role is SA here

@yegor256 OK, role is set to SA

**Comment by alex-palevsky** [comment]
@niinat many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-49L914754P872613D`

**Comment by alex-palevsky** [comment]
@sfarley85 please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by sfarley85** [comment]
@alex-palevsky @niinat I have created a pull-request with proposed changes. I used the existing documentation and blog posts regarding Rultor to inform the section. Please let me know if anything is incorrect or not in the desired format.

**Comment by alex-palevsky** [comment]
> @alex-palevsky @niinat I have created a pull-request with proposed changes. I used the existing documentation and blog posts regarding Rultor to inform the section. Please let me know if anything is incorrect or not in the desired format.

@sfarley85 yes, everything is correct so far, thanks

**Comment by sfarley85** [comment]
@alex-palevsky @yegor256 Anything else I need to do here with this task?

**Comment by alex-palevsky** [comment]
> @alex-palevsky @yegor256 Anything else I need to do here with this task?

@sfarley85 in order to close the ticket (and get paid) you have to make sure the ticket is closed by its author, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by sfarley85** [comment]
@alex-palevsky Sure I understand that. Just wanted to make sure no one was waiting on me for something. @niinat Please review the changes and close the ticket or let me know if something further is needed. Thanks!

**Comment by niinat** [comment]
@sfarley85 Based on the following documents the suggested changes look correct.
- http://www.yegor256.com/2014/07/24/rultor-automated-merging.html
- http://www.yegor256.com/2014/09/11/deployment-script-vs-rultor.html
- http://www.yegor256.com/2015/03/29/rultor-with-appveyor.html
- http://www.yegor256.com/2014/10/08/continuous-integration-is-dead.html
 I close the ticket.

**Comment by alex-palevsky** [comment]
> @alex-palevsky Sure I understand that. Just wanted to make sure no one was waiting on me for something. @niinat Please review the changes and close the ticket or let me know if something further is needed. Thanks!

@sfarley85 sure, thanks

**Comment by alex-palevsky** [comment]
@sfarley85 **30 mins** added to your account (payment number `AP-9NP34890DU6165912`), many thanks for your contribution! 259 hours and 55 mins spent here.

+30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/35863?open=rating)
