### ISSUE TITLE
README file: Description for How Rultor Works? is missing

### ISSUE THREAD

**Issue by niinat** [yegor256/rultor#950]
Problem: Description for the section "How Rultor Works?" on the product specification is missing.
https://github.com/niinat/rultor/blob/master/README.md
Solution: in progress

**Comment by niinat** [comment]
Solution: in progress

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@alex-palevsky this is a valid bug

**Comment by yegor256** [comment]
@alex-palevsky and the role is SA

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a valid bug

@yegor256 I added `bug` tag to this ticket

**Comment by alex-palevsky** [comment]
@niinat attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@niinat thanks for the ticket, your account was topped for 15 mins, payment AP-9ND23810D3693773C

**Comment by alex-palevsky** [comment]
> @alex-palevsky and the role is SA

@yegor256 OK, it is SA here

**Comment by yegor256** [comment]
@alex-palevsky roles is SA here

**Comment by alex-palevsky** [comment]
> @alex-palevsky roles is SA here

@yegor256 right, role is set to SA here

**Comment by alex-palevsky** [comment]
@gumbelmj please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by alex-palevsky** [comment]
@gumbelmj you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); -30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/36306?open=rating)

**Comment by gumbelmj** [comment]
@alex-palevsky I have been working on this ticket from shortly after it was assigned.  I have been trying to get this reviewed and merged.  There is some problem with the merging, unrelated to this ticket.

**Comment by alex-palevsky** [comment]
> @alex-palevsky I have been working on this ticket from shortly after it was assigned.  I have been trying to get this reviewed and merged.  There is some problem with the merging, unrelated to this ticket.

@gumbelmj keep this in mind: http://at.teamed.io/policy.html#10

**Comment by gumbelmj** [comment]
@alex-palevsky more time

**Comment by alex-palevsky** [comment]
> @alex-palevsky more time

@gumbelmj agreed, take your time

**Comment by gumbelmj** [comment]
@niinat the changes have been merged into master.  Can you please close this?

**Comment by alex-palevsky** [comment]
@gumbelmj I added **30 mins** to your account, many thanks for working with the project (AP-3KE69228FM386912K)! The completion time here was 723 hours and 35 mins.. added +30 to your rating, now it is equal to [-60](http://www.netbout.com/b/36306?open=rating)
