### ISSUE TITLE
Run rultor build/merge locally

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/rultor#954]
It would be really helpful to have a possibility to easily run container locally.
It appears that some of the issues are relevant only during rultor `merge` procedure and can't be debugged easily.

See
* [xockets-hadoop-transport - 945](https://github.com/teamed/xockets-hadoop-transport/issues/945)
* [xockets-xjm - 138](https://github.com/teamed/xockets-xjm/issues/138)

[Here](https://github.com/teamed/xockets-hadoop-transport/issues/1124) is the original discussion

**Comment by ekondrashev** [comment]
@yegor256 could you please comment if that is achievable in some workaround form?

**Comment by yegor256** [comment]
@ekondrashev it's a duplicate of https://github.com/yegor256/rultor/issues/549 (see my answer there)
