### ISSUE TITLE
Maven Release: Sonatype errors: "Missing: no sources jar found" & "Missing: no javadoc jar found" & "Missing Signature: '*.pom.asc' does not exist"

### ISSUE THREAD

**Issue by benjwarner** [yegor256/rultor#957]
Hi there!
Thanks for the service you are providing.
Am trying to get my github project released to maven central.
Am getting these three errors when I try and "close" the release in sonatype.

1. Missing: no sources jar found in folder '/org/fix4j/fix4j-assert-core/1.0'
2. Missing: no javadoc jar found in folder '/org/fix4j/fix4j-assert-testcommon/1.0'
3. Missing Signature: '/org/fix4j/fix4j-assert/1.0/fix4j-assert-1.0.pom.asc' does not exist for 'fix4j-assert-1.0.pom'.

(The errors are repeated for each module in my project).

* The issue I triggered the build from is here: https://github.com/fix4j/fix4j-assert/issues/1
* The build log which uploaded to sonatype is here: http://www.rultor.com/t/5720-157148994

(Please ignore the very last request to Rultor.  It failed because repo already had the 1.0 tag)

So I guess there are 3 different problems here.  No source jars being generated and/or uploaded, no javadoc jars being generated and/or uploaded.  And no encrypted pom files.

I saw in your setup instructions at http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html that there was no need to add javadoc, sources, and gpg plugins as long as I had the recommended parent pom referenced (which I have).

Any help would be greatly appreciated.

Cheers!
Ben

**Comment by yegor256** [comment]
@benjwarner run your Maven build with this option: `-Psonatype`. That should solve the problem. See how it's done in this project, for example: https://github.com/jcabi/jcabi-http (pay attention to `.rultor.yml`)

**Comment by benjwarner** [comment]
Hi Yegor,
Thanks for your reply.

That definitely got me closer!

Am now getting this error when the release is closed:

Missing Signature: '/org/fix4j/fix4j-assert/1.1/fix4j-assert-1.1.pom.asc'
does not exist for 'fix4j-assert-1.1.pom'.

(repeated for each pom)

Full build log is here: http://www.rultor.com/t/5720-157282393

yml file content is:

decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Psonatype --settings /home/r/settings.xml

Any help would be appreciated.

Cheers,
Ben

**Comment by benjwarner** [comment]
Solved in https://github.com/yegor256/rultor/issues/958
