### ISSUE TITLE
Missing Signature: '....pom.asc' does not exist for 'fix4j-assert-1.1.pom'.  (asc files not being uploaded for poms and jars)

### ISSUE THREAD

**Issue by benjwarner** [yegor256/rultor#958]
Hi Yegor, 
am getting closer to a sonatype release working. 

Am now getting this error when the release is closed: 

```
Missing Signature: '/org/fix4j/fix4j-assert/1.1/fix4j-assert-1.1.pom.asc' does not exist for 'fix4j-assert-1.1.pom'. 
(error is repeated for each pom & jar file) 
```

Full build log is here: http://www.rultor.com/t/5720-157282393 
yml file content is: 

```
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Psonatype --settings /home/r/settings.xml
```

Any suggestions would be appreciated.
Cheers, 
Ben

**Comment by alex-palevsky** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@benjwarner it seems the required `pom.asc` file is not created. Try to run `mvn clean install -Psonatype` locally (on your computer) and see what you have in `target` directory. I bet `pom.asc` won't be there, and that is the problem

**Comment by benjwarner** [comment]
Thanks @yegor256 that lead me to a solution.

My settings.xml had the wrong profile name.
