### ISSUE TITLE
check for release versions that are lower than already existing ones

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#960]
At the moment Rultor doesn't make any check for the release version. 
It is possible to release versions that are lower than already existing ones.
It would better if Rultor will  prevent such releases.

**Comment by alex-palevsky** [comment]
@dmzaytsev this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@dmzaytsev since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 71681605

**Comment by alex-palevsky** [comment]
@jimdeanspivey please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by JimDeanSpivey** [comment]
Here is my understanding of the problem:

```
[at-sign]rultor release, tag is `0.1`
[at-sign]rultor release, tag is `0.2`
[at-sign]rultor release, tag is `0.8`
[at-sign]rultor release, tag is `0.3`
```


And that the problem is that I should not be able to release version `0.3` since the current version is `0.8` ?

**Comment by dmzaytsev** [comment]
@JimDeanSpivey yep, Rultor shouldn't allow release `0.3` in this case

**Comment by dmzaytsev** [comment]
@yegor256 on the other note it would be nice to be able to force any release
so if i say `rultor release, tag='0.3' force`
rultor will release it in any case

what do you think?

**Comment by JimDeanSpivey** [comment]
Not sure if Rultor enforces version **numbers**. So I want to mentioned that version numbers in git releases can be any string, which means that is not always possible to validate that they must be *high enough*.


* `1.2.3` - most common and valid. This can be validated to make sure that `1.2.3.` is not lower than the current version.
* `my-tagged-release` - obviously there is no way to apply version ordering here
* `1.2.3-beta` - Some people put characters after or in with many different reasons. I think these should be ignored.

**Comment by JimDeanSpivey** [comment]
Currently have it rejecting if the version number is too low via this PR: #989  But still waiting for input regarding the `force` functionality.

Also, I have some questions/concerns about qulice's enforcement. Because I cannot use the `new` keyword in a for loop, I had to use Guava's transformation utils to convert a list from one object type to another. I think the code looks much cleaner without Guava (using manual for loops and the new keyword). Performance-wise, it's probably also faster than using guava or the same. Should I raise an issue, using code samples of before and after, on qulice issues ?

**Comment by yegor256** [comment]
@JimDeanSpivey make sure you address your comments to someone, by adding the name in front of it. otherwise, who are you talking to? :)

**Comment by yegor256** [comment]
@dmzaytsev I think that "force" is not required now. maybe, in the future, if someone will ask for that, we'll implement it

**Comment by JimDeanSpivey** [comment]
@alex-palevsky code-review needed for #989

**Comment by alex-palevsky** [comment]
> @alex-palevsky code-review needed for #989 

@jimdeanspivey OK

**Comment by alex-palevsky** [comment]
@jimdeanspivey the task is your hands for the last 16 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: [+8](http://www.netbout.com/b/36321?open=rating)

**Comment by alex-palevsky** [comment]
@jimdeanspivey this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 to your rating, your total score is [-112](http://www.netbout.com/b/36321?open=rating)

**Comment by alex-palevsky** [comment]
@gumbelmj please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by original-brownbear** [comment]
@gumbelmj I'm sorry but this task has been with you for more than 10 days now. 
Given that you did not address the criticism in the PR today and this is the last task missing for the next release, this cannot wait any longer.

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by gumbelmj** [comment]
@original-brownbear  I did not know this was holding up a release.  I will address the comments.

**Comment by original-brownbear** [comment]
@gumbelmj as per [#16](http://at.teamed.io/policy.html#16) you had 10 days to complete this task, more than 10 days have passed now.
As per [#26](http://at.teamed.io/policy.html#26) it is my obligation to ensure no task becoming stuck.
In accordance with [#29](http://at.teamed.io/policy.html#29) my tool towards achieving this is asking to reassign issues.

You were given repeated advice in the PR by me and the code reviewer and there still are a number of issues with your PR. Hence I'm asking @alex-palevsky to address this by reassigning this ticket to me or in whatever other way he sees fit.

**Comment by gumbelmj** [comment]
@original-brownbear I understand that it is within policy to reassign the issue.  At this moment I believe I have addressed all concerns.  I didn't realize how much time had elapsed.  I apologize.  In the future, I will pay more attention to that.

**Comment by original-brownbear** [comment]
@gumbelmj I have addressed your PR, it is not acceptable for a wide number of reasons, see my comments there.

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear OK, it is yours, please proceed

**Comment by original-brownbear** [comment]
@dmzaytsev alright, merged at last after a million delays :) Could you close here please ?

**Comment by dmzaytsev** [comment]
@original-brownbear sure :)
thank you

**Comment by original-brownbear** [comment]
@alex-palevsky can you close ? This is still open in my agenda, thanks :)

**Comment by alex-palevsky** [comment]
@original-brownbear **30 mins** sent to your balance (ID `AP-43453076WK620521H`), many thanks! It took 126 hours and 55 mins.. +30 added to your rating, at the moment it is: [+812](http://www.netbout.com/b/36646?open=rating)
