### ISSUE TITLE
EndDaemon doesn't stop when Docker container is dead

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#963]

**Comment by yegor256** [comment]
@rultor release, tag is `1.58.4`

**Comment by pinaf** [comment]
@yegor256 is this what's causing the hangs?

**Comment by yegor256** [comment]
@pinaf this is why hangs are not detected immediately

**Comment by yegor256** [comment]
@pinaf should be fine now

**Comment by pinaf** [comment]
@yegor256 Excellent. But we have to wait for the release, right?

**Comment by pinaf** [comment]
@yegor256 looks like it is monitoring just fine but the docker image cannot be downloaded.

**Comment by yegor256** [comment]
@rultor release, tag is `1.58.4`

**Comment by sils1297** [comment]
@yegor256 it seems to hang again. Is it related to this issue? https://github.com/coala-analyzer/coala/pull/1151

**Comment by sils1297** [comment]
seems to hang here: http://www.rultor.com/t/6025-166382612 , same as https://github.com/yegor256/rultor/issues/963#issuecomment-165289739 it seems

**Comment by yegor256** [comment]
@sils1297 I will try to make it more transparent here: #968
