### ISSUE TITLE
Rultor not responding

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#964]
Are you having a downtime currently? Rultor currently does not respond to our requests:

https://github.com/coala-analyzer/coala/pull/1139

**Comment by sils1297** [comment]
Ok, everything got done after a 30 minute delay, was there any problems on your side or is this a potential bug?

**Comment by yegor256** [comment]
@sils1297 it's a bug on our side, should be fixed soon

**Comment by yegor256** [comment]
@sils1297 dup of #963
