### ISSUE TITLE
not working after exit 1 (?)

### ISSUE THREAD

**Issue by hovancik** [yegor256/rultor#970]
so I forked https://github.com/yegor256/jekyll-github-deploy to https://github.com/hovancik/middleman-github-deploy and wanted to release the functionality for middleman app but seems that I broke rultor

https://github.com/hovancik/middleman-github-deploy/pull/1 
I followed http://www.yegor256.com/2014/08/26/publish-to-rubygems.html

so then I released gem by myself. 

then I tried https://github.com/hovancik/middleman-github-deploy/pull/2 with different syntax

but seems that rultor is still broken for me.

**Comment by hovancik** [comment]
ah, so it just took long time to figure out it failed. 

but anyway now it fails with `./test.sh: line 6: middleman: command not found` 

not sure why is that. how should I figure out what is the problem? I am not familiar with rultor internals.

**Comment by alex-palevsky** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@hovancik `middleman` is, I believe, a Linux software. You should install it first, via `apt-get`. Something like this in your `.rultor.yml`:

```yaml
install:
  - apt-get install middleman
```

Make sense?

**Comment by hovancik** [comment]
@yegor256 I understand how `.rultor.yml` works. 

What I wanted to know, thought,  is how would I test it. Middleman is ruby gem, and as I am not familiar with rultor internals (eg. not at all with docker), I am not sure how to test how to put it in `yml`. Putting in what I manage to google about docker and then trying to call `rultor release` seems at least wrong way.

**Comment by yegor256** [comment]
@hovancik what do you have in `.rultor.yml` now? Post it here please

**Comment by hovancik** [comment]
```
decrypt:
  rubygems.yml: repo/rubygems.yml.asc
release:
  script: |-
    git config --global user.email "test@example.com"
    git config --global user.name "Test"
    ./test.sh
    rm -rf *.gem
    sed -i "s/1.0.snapshot/${tag}/g" mgd.gemspec
    gem build mgd.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - hovancik
architect:
- hovancik
merge:
  commanders: []
deploy: {}
```

unfortunately  I screwed my repo a bit and I had to start again, so my previous PRs not there anymore.

**Comment by yegor256** [comment]
@hovancik I assume, you're using `middleman` somewhere in `./test.sh`. right? you have to install it first. add this line to your `.rultor.yml`:

```
install: |-
  gem install middleman
```

**Comment by hovancik** [comment]
I'll try once I have new release, thanks for help
