### ISSUE TITLE
Rultor not responding

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#971]
We're trying to get a release done since 30 minutes on https://github.com/coala-analyzer/coala/issues/1176 , the first attempt seemed to fail (IMO the parameters for commands aren't that intuitive btw.) and since then it didn't react.

**Comment by alex-palevsky** [comment]
@yegor256 please do something about this issue

**Comment by sils1297** [comment]
FWIW after two hours or so rultor did the stuff, still the delay is an issue.

**Comment by yegor256** [comment]
@sils1297 looks like it worked, right? or you are still having this problem?

**Comment by sils1297** [comment]
@yegor256 my problem is the huge delay. (Yes it worked)

**Comment by yegor256** [comment]
@sils1297 then I need a more detailed description of the problem... so that I can reproduce it. can you explain the steps I should follow?

**Comment by sils1297** [comment]
Sorry, I currently have no time for this, though I can't say more than explain when we left which comment and how rultor responded/how long it took it.
