### ISSUE TITLE
Disallow usage of commits that close issues

### ISSUE THREAD

**Issue by krzyk** [yegor256/rultor#974]
Right now rultor will merge any commit builds successfully, but some commits are special for github and will automatically close issue mentioned in the message.
This [page](https://help.github.com/articles/closing-issues-via-commit-messages/) gives a list of such commit messages, an example of such case is here: https://github.com/teamed/qulice/issues/544#event-507433326

Rultor should not merge a PR if it contains any commit that matches the definition mentioned in githubs [Closing Issues via Commit Messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by alex-palevsky** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@krzyk good idea, but, I believe, it's outside of scope of rultor. not every project may need this. if you want this functionality, just add something like this to your `.rultor.yml`:

```yaml
merge:
  script: |-
    git log | grep -v 'fixes|fixed|closes|closed'
    mvn clean install
```

Not sure about the syntax, but you got the idea
