### ISSUE TITLE
rultor doesn't ignore a text in back-ticks

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#978]
I think Rultor should ignore if someone mention him in back-ticks

https://github.com/yegor256/netbout/issues/889#issuecomment-170103496

![image](https://cloud.githubusercontent.com/assets/9972909/12207987/cd4af250-b66b-11e5-9c5f-bfd6c9b0da4e.png)

**Comment by yegor256** [comment]
@dmzaytsev it was discussed somewhere already (can't find it). we can't do it, technically. we will have to parse Markdown to implement this. that's too much of a hassle for a such a small feature
