### ISSUE TITLE
Update the Copyright year

### ISSUE THREAD

**Issue by oruam85** [yegor256/rultor#981]
In some files like as license.txt the Copyright year should be 2016

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@oruam85 we'll fix it right after this one is solved https://github.com/teamed/qulice/issues/583 (we'll copy their solution here)

**Comment by original-brownbear** [comment]
@alex-palevsky valid bug.

https://github.com/teamed/qulice/issues/583 is closed and we can go ahead here.

**Comment by alex-palevsky** [comment]
> @alex-palevsky valid bug.
> 
> https://github.com/teamed/qulice/issues/583 is closed and we can go ahead here.

@original-brownbear added "bug" tag to this issue

**Comment by alex-palevsky** [comment]
@oruam85 there is no milestone yet, so I set it to `2.0`

**Comment by alex-palevsky** [comment]
@vkuchyn can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by alex-palevsky** [comment]
@oruam85 thanks for this report, I added 15 mins to your account, in transaction `78545196`

**Comment by vkuchyn** [comment]
@original-brownbear Just to clarify scope of task. Correct me if I am wrong:
1. Create years.sh test file to ensure that all years are correct.
2. Add it to travis build
3. Change all licenses headers in project to current year 2016.
Can I just copy-paste years.sh, seems it should work for rultor

**Comment by original-brownbear** [comment]
@vkuchyn sure as pointed out by @yegor256 above we are going for copying that solution,
so your plan is just fine.
Please make sure that it not only seems to, but actually does work though :)

**Comment by vkuchyn** [comment]
@original-brownbear is there are some rule what files should contain copyright? 
Qulice solution contains lots of exclusion. In rultor the same approach makes script too big and terrible. 
I have an idea - check all files that contains line starts with `Copyright (c) 2009-*` and check last year. What do you think?

**Comment by original-brownbear** [comment]
@vkuchyn I think that's ok just be careful with white-space maybe. 
You could also grep for lines that also contain rultor.com for example to lower the risk for that.
But I'm fully on board with constraining the result-set of this a little if you run into false positives, nothing else you can do :)

**Comment by krzyk** [comment]
@vkuchyn what exclusions do you have to do here? I see only base64, key, jekyl folder, and maybe svg files, Procfile. But the rest probably should have copyrights (*.sh, *.vm, *.txt, *.properties), unless I missed something.

**Comment by krzyk** [comment]
@vkuchyn also, I'm not sure if that's the responsibility of years.sh, but the one in qulice, will also find files that don't have copyright, but should have (like *.sh files, which don't have it in rultor)

**Comment by vkuchyn** [comment]
@krzyk jekyl folder contains css/layout.css that have Copyright. As far as grep doesn't support negative lookahead - I need to exclude each folder except css. Will be something `egrep -v "(src/jekyl/_layout|src/jekyl/_plugins)"` and so on. The same situation with src/main/resources/com/rultor/agents. All files except github/qtn/status.xsl doesn't contains copyright
> that don't have copyright, but should have
Probably that's good point, but it is not scope of the task. And for me is not clear policy of what files should contain Copyright.

**Comment by vkuchyn** [comment]
@original-brownbear After year fixed, I got violation `/src/test/java/com/rultor/web/TkTicksTest.java[2]: Line does not match expected header line of ' * Copyright (c) 2009-2014, rultor.com'. (HeaderCheck)` How to fix it?

**Comment by vkuchyn** [comment]
@original-brownbear I found it by myself - thanks.

**Comment by vkuchyn** [comment]
@alex-palevsky fixed in #1029 need review

**Comment by alex-palevsky** [comment]
> @alex-palevsky fixed in #1029 need review

@vkuchyn thanks

**Comment by vkuchyn** [comment]
@oruam85 merged #1029, please close issue

**Comment by oruam85** [comment]
Closed

**Comment by alex-palevsky** [comment]
@vkuchyn Much obliged! I have added **30 mins** to your account in payment "79299991", 165 hours and 18 mins spent

+30 added to your rating, current score is: [+150](http://www.netbout.com/b/36353?open=rating)
