### ISSUE TITLE
rultor rejects deploy command

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#982]
I have no idea why rultor accepts `deploy` command from the architect on [Qulice](https://github.com/teamed/qulice/blob/master/.rultor.yml) and rejects the same on [Netbout](https://github.com/yegor256/netbout/blob/master/.rultor.yml)
Please assist

Update of snaphot.netbout.com is possible only after the deployment.
Right now I need wait several days while PM make `deploy`
actually it's real issue in my work

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@dmzaytsev it's happening because the owner of netbout is a personal account, while qulice belongs to the organization. I'm on it...

**Comment by original-brownbear** [comment]
@alex-palevsky valid bug

**Comment by original-brownbear** [comment]
@alex-palevsky this is urgent

**Comment by alex-palevsky** [comment]
> @alex-palevsky valid bug

@original-brownbear I tagged this as "bug"

**Comment by alex-palevsky** [comment]
@dmzaytsev since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
@dmzaytsev thanks for the report, I topped your acc for 15 mins, payment ID `78370348`

**Comment by original-brownbear** [comment]
@alex-palevsky please assign me.

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please :)

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is urgent

@original-brownbear got it, "urgent" label here

**Comment by alex-palevsky** [comment]
> @alex-palevsky please assign me.

@original-brownbear done, the task is yours, go ahead

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please :)

@original-brownbear sure, it was yours before, go ahead

**Comment by original-brownbear** [comment]
Ok PR in for this one too :)

**Comment by original-brownbear** [comment]
@dmzaytsev fix for this was merged, can you close this please ? :)

**Comment by dmzaytsev** [comment]
@original-brownbear sure

**Comment by dmzaytsev** [comment]
@original-brownbear please release the fix

**Comment by original-brownbear** [comment]
@rultor release tag is `1.61.5`

**Comment by original-brownbear** [comment]
@dmzaytsev damn not working, appears we also have some issue reading the architects from the .yml not only using that result, I fear you have to reopen here :/

**Comment by dmzaytsev** [comment]
@original-brownbear no problem

**Comment by original-brownbear** [comment]
@rultor release tag is `1.61.6`

**Comment by original-brownbear** [comment]
@dmzaytsev fixed trivial issue here with test + production code :/, should be good now though.

**Comment by dmzaytsev** [comment]
@original-brownbear thanks,
it seems the test didn't test :)

**Comment by original-brownbear** [comment]
@dmzaytsev check it out #1027 works fine now, tests have a more general issue here. Will add a ticket asap :)

**Comment by dmzaytsev** [comment]
@original-brownbear it works now
thank you!

**Comment by original-brownbear** [comment]
@alex-palevsky can you handle payment here please and close this for good :) ?

**Comment by alex-palevsky** [comment]
@original-brownbear **30 mins** added to your account (payment number `AP-3AT32702HB2006512`), many thanks for your contribution! 89 hours and 11 mins spent here.; +30 to your rating, your total score is [+398](http://www.netbout.com/b/36646?open=rating)
