### ISSUE TITLE
'cid' file is absent, container wasn't started correctly

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#985]
Hi, seems rultor currently can't start any container prohibiting us from doing any merges :/

It happened here twice: https://github.com/coala-analyzer/coala/pull/1214

**Comment by sils1297** [comment]
ah the second time the error differed:

```
Error response from daemon: Conflict. The name "coala-analyzer_coala_1214" is already in use by container 19d29bf1e4f1. You have to delete (or rename) that container to be able to reuse that name.
'cid' file is absent, container wasn't started correctly
```

**Comment by yegor256** [comment]
@sils1297 working on it, thanks for reporting...

**Comment by yegor256** [comment]
@sils1297 I believe it works now, please check

**Comment by sils1297** [comment]
will try it at the next occasion, thanks

2016-01-15 19:58 GMT+01:00 Yegor Bugayenko <notifications@github.com>:

**Comment by sils1297** [comment]
I'm getting internal server errors now: https://github.com/coala-analyzer/coala/pull/1218

Why is this marked `invalid` anyway?

**Comment by yegor256** [comment]
@sils1297 to avoid full processing of it via our management workflow. Looks like that "internal server error" is related to the content of your project, not to rultor. no?

**Comment by sils1297** [comment]
Actually it feels like the HTTP 500 occurs when rultor is processing high loads or something, on my PC the scripts always work and I never get a 500. I think it's rultor related but can't prove it. It happens *sometimes* on rultor and only on rultor. (Though this is not the bug where we started from, that one is fixed indeed.)

**Comment by yegor256** [comment]
@sils1297 could be the problem of performance, of course. try to run your project inside Docker, on your machine. that will help you reproduce rultor environment better.
