### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/rultor#986]
There is no documentation available on how to run rultor locally  to perform tests.

**Comment by yegor256** [comment]
@kujtimiihoxha `mvn clean install -Pqulice` (as README suggests) should be fine. All tests will be executed, including integration ones. Or I didn't understand your question?

**Comment by kujtimiihoxha** [comment]
After using ```mvn clean install -Pqulice ``` i got this error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.394 s
[INFO] Finished at: 2016-01-18T23:26:08+01:00
[INFO] Final Memory: 101M/857M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:verify (default) on project rultor: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/kujtimiihoxha/TeamedIO/rultor/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by yegor256** [comment]
@kujtimiihoxha how this is related to the question about documentation?

**Comment by kujtimiihoxha** [comment]
@yegor256 I was referring to your answer, If I try to use ```mvn clean install -Pqulice```  (without making any change to the master branch), it results in that error, so i can not test the changes.

**Comment by yegor256** [comment]
@kujtimiihoxha but that's another problem, irrelevant to the absence of documentation. should be reported in a new ticket. keep in mind that tickets are not chats. they are here to resolve problems, one by one. please, read this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html
