### ISSUE TITLE
Better badge quality

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#988]
http://shields.io/ aims to make badges Pixel-perfect, Retina-ready, Fast, Consistent, Hackable and with No tracking.

Currently, rultor badge has a different size from other badges:

![image](https://cloud.githubusercontent.com/assets/245435/12513835/23acabde-c107-11e5-8f22-c18ef5af487f.png)

Maybe we could use the shields.io service to generate rultor badges, or just make it the same size as other badges.

What do you guys think?

**Comment by yegor256** [comment]
@caarlos0 I can make another one, with 25px height (this is what Travis and others are using).

**Comment by caarlos0** [comment]
@yegor256 yeah, I think it will look nicer on the readmes to have them all the same height :D

**Comment by yegor256** [comment]
@rultor release tag is `1.61`

**Comment by yegor256** [comment]
@caarlos0 try 

```
http://www.rultor.com/b/yegor256/rultor?size=s
http://www.rultor.com/b/yegor256/rultor?size=m
```

**Comment by caarlos0** [comment]
@yegor256 neat, thanks!
