### ISSUE TITLE
Rultor won't build on AppVeyor

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#992]
```
[INFO]  
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (fail-on-windows) @ rultor ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.AlwaysFail failed with message:
You should use Unix-like or Mac OS to successfully build Rultor.
                                                With an other OS you are still able to check sources with the command:
                                                'mvn qulice:check -Pqulice'
Always fails! 
[INFO] ------------------------------------------------------------------------ 
```

Example build: https://ci.appveyor.com/project/yegor256/rultor/build/625

I think we should either fix this or remove the appveyor integration...

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@alex-palevsky this falls under http://at.teamed.io/policy.html#13 this is cosmetic only and trivial to find given that the maven file contains:

```
<execution>
    <id>fail-on-windows</id>
    <goals>
        <goal>enforce</goal>
    </goals>
    <phase>validate</phase>
    <configuration>
        <rules>
            <alwaysFail>
                <message>
                    You should use Unix-like or Mac OS to successfully build
                    Rultor.
                    With an other OS you are still able to check sources with
                    the command:
                    'mvn qulice:check -Pqulice'
                </message>
            </alwaysFail>
        </rules>
    </configuration>
</execution>
```

**Comment by caarlos0** [comment]
@original-brownbear than I think we can just remove appveyor integration, right?

**Comment by original-brownbear** [comment]
@caarlos0 Jup, that's the plan in the #1017 :)

**Comment by original-brownbear** [comment]
@yegor256 I think we need you here, removing the Appveyor config file caused Travis and Semaphore  not to run on that PR. This seems to come from the repo settings in Github and the now missing Appveyor file, I think you need to remove Appveyor from those before we can merge #1017.

**Comment by caarlos0** [comment]
@original-brownbear so this is a valid bug, right?

**Comment by original-brownbear** [comment]
@caarlos0 please keep in mind that this is the first time I ever have to make this call in this setting, but honestly:

> Small, easy-to-find, easy-to-fix, or cosmetic bugs and tasks are not paid, even if they lead to a code change and project improvement. 

I mean this bug fits all excluded categories at once, the fact that I need to ping @yegor256 is immaterial imo, given that the only productive outcome of this removing an ugly icon from the readme and PRs (cosmetic) and literally took me 30s to fix (easy-to-fix).

Sorry.

**Comment by caarlos0** [comment]
@original-brownbear ok

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.
