### ISSUE TITLE
Won't build on Vexor, can't see logs

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#993]
Build always fail on Vexor: https://ci.vexor.io/ui/builds/a4344420-391e-4ab9-9e81-50758ea41ab5

Seems like I don't have permission to see the logs, so I don't know what's going on.

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by original-brownbear** [comment]
@yegor256 pinging you here, I can't see the logs either :)

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.

Same reasoning as for #992 sorry.

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.
