### ISSUE TITLE
Rultor is unable to merge itself

### ISSUE THREAD

**Issue by JimDeanSpivey** [yegor256/rultor#994]
In this PR: https://github.com/yegor256/rultor/pull/990 Yegor issued command for rultor to merge. Despite that `maven clean install -Pqulice` running fine in my local (and the fact that the PR is very small), it should have merged. It appears that the Ruby environment that Rultor depends on, wherever that is, has issues. See the logs from PR 990: http://www.rultor.com/t/6581-174764783

Also, others have ran into this version conflict with ruby, and there are various solutions here: https://github.com/dtao/safe_yaml/issues/72

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by original-brownbear** [comment]
@alex-palevsky The fix to this broke https://github.com/yegor256/rultor/issues/1001.
Evidently this works again and the other ticket is closed already, I think this can also be closed.

**Comment by original-brownbear** [comment]
@JimDeanSpivey can you close this please, this is evidently not an issue anymore :)

**Comment by original-brownbear** [comment]
@alex-palevsky actually could you please close this? #1001 contains a detailed analysis that includes how the above error came about and the fix for it. No need to wait here I think.

**Comment by original-brownbear** [comment]
@alex-palevsky this is duplicate.
