### ISSUE TITLE
more memory for docker

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#995]

**Comment by yegor256** [comment]
@rultor release, tag is `1.61.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.61.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.61.2`

**Comment by yegor256** [comment]
@caarlos0 @longtimeago please try again in other projects, should be fine now

**Comment by pinaf** [comment]
@yegor256 this is fixed? I believe builds are still failing.

**Comment by yegor256** [comment]
@pinaf seems to be fixed. we have 6gb RAM, which is exactly how much we had before. everything should be good now

**Comment by pinaf** [comment]
@yegor256 great, thank you.

**Comment by longtimeago** [comment]
@yegor256 looks good, thank you!

**Comment by caarlos0** [comment]
@yegor256 thanks!
