### ISSUE TITLE
README does not explain why someone should use Rultor

### ISSUE THREAD

**Issue by mafagafogigante** [yegor256/rultor#997]
Which is on of the main reasons to have a readme.

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by mafagafogigante** [comment]
@alex-palevsky I created this issue so that the PR and commit would be contextualized and documented in the tracker. I hope this (that seems to be considered a good practice in several projects) is well accepted in this repository.

**Comment by yegor256** [comment]
@mafagafogigante yeah, right, thanks for making this issue

**Comment by mkordas** [comment]
@mafagafogigante you need to refer to PR here

**Comment by mafagafogigante** [comment]
@mkordas Mention #998 Done

**Comment by alex-palevsky** [comment]
@rultor @mafagafogigante please look at this issue, rultor closed it automatically

**Comment by mkordas** [comment]
@mafagafogigante please close

**Comment by mafagafogigante** [comment]
@mkordas OK.
