### ISSUE TITLE
Attach VM core dump in case of JVM crash during the build 

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#999]
Sometimes JVM crashes during the build of client code (it happens more frequent in case of JNI code).
It would be really helpful to attach core dump and error report to the build (have a link on them in build logs).

Error report usually stored on Rultor's container filesystem like this `/home/r/repo/hs_err_pid19753.log`.
Same for core dump `/home/r/repo/core`

**Comment by yegor256** [comment]
@longtimeago good idea, but we can't do it at the level if rultor. We simply don't know what exactly are you executing - JVM or Ruby or C++ compiler or whatever...  you should do it in your `.rultor.yml` script. Something like this:

```
deploy:
  script: |-
    mvn clean install || echo "maven crashed" > crash
    if [ -e crash -a -e hs_err_*.log ]; then
      cat hs_err_*.log
    fi
```

It's pseuo-code, but you got the idea.

**Comment by longtimeago** [comment]
@yegor256 cool, thanks!

**Comment by longtimeago** [comment]
@yegor256 question - suppose, `deploy` section contains several scripts and first script fails. What would be with subsequent scripts? Will they be executed?

**Comment by longtimeago** [comment]
@yegor256 please, take a look at my comment above. Thanks!

**Comment by alxn** [comment]
@longtimeago @yegor256 and no wait to attach the core file, unless perhaps we uuencode it and send it to the log file, could be a **lot** of lines though, which may get truncated by the system iirc?

**Comment by yegor256** [comment]
@longtimeago that's why you need this:

```
mvn clean install || echo 'crashed'
```

This `||` will make sure the failure of `mvn` doesn't stop the script

**Comment by longtimeago** [comment]
@yegor256 thanks, will try
